Repository rilldata/rill, pull requests merged in 2022-12, with the labels that each got.

#1382 Fix dashboard routing
  web-local/src/lib/errors/messages.ts
  web-local/src/routes/(application)/dashboard/[name]/+page.svelte
  web-local/src/routes/(application)/dashboard/[name]/+page.ts
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.ts
Labels: bug, _application_

#1423 Using the common method for mapping to file name
  web-local/src/lib/components/navigation/Navigation.svelte
  web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte
  web-local/src/lib/components/navigation/models/ModelMenuItems.svelte
  web-local/src/lib/components/navigation/models/createModel.ts
  web-local/src/lib/components/navigation/sources/SourceMenuItems.svelte
  web-local/src/lib/components/navigation/sources/createSource.ts
  web-local/src/lib/components/navigation/sources/refreshSource.ts
  web-local/src/lib/components/workspace/metrics-def/MetricsDefWorkspace.svelte
  web-local/src/lib/components/workspace/model/ModelBody.svelte
  web-local/src/lib/components/workspace/model/inspector/header/CreateDashboardButton.svelte
  web-local/src/lib/components/workspace/model/inspector/header/ModelInspectorHeader.svelte
  web-local/src/lib/svelte-query/actions.ts
  web-local/src/lib/util/entity-mappers.ts
  web-local/src/routes/(application)/dashboard/[name]/+page.ts
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.ts
Labels: Blocker

#1428 Fix bug that prevented remote source refresh
  web-local/src/lib/components/navigation/sources/refreshSource.ts
Labels: bug

#1427 Sort files case-insensitive
  web-local/src/lib/svelte-query/dashboards.ts
  web-local/src/lib/svelte-query/models.ts
  web-local/src/lib/svelte-query/sources.ts
Labels: _application_

#1424 Support analytical APIs for column names containing '/'
  proto/gen/rill/runtime/v1/api.pb.go
  proto/gen/rill/runtime/v1/api.pb.gw.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/rill/runtime/v1/api.proto
  web-common/src/runtime-client/gen/index.schemas.ts
  web-common/src/runtime-client/gen/runtime-service/runtime-service.ts
  web-local/src/lib/http-request-queue/HttpRequestQueue.spec.ts
  web-local/src/lib/http-request-queue/HttpRequestQueue.ts
  web-local/src/lib/http-request-queue/priorities.ts
  web-local/test/ui/utils/helpers.ts
Labels: Blocker

#1430 Model to dashboard invalidations
  web-local/src/lib/svelte-query/invalidation.ts
Labels: Blocker

#1415 Rill Install script
  .github/workflows/cli-release.yml
  scripts/install.sh
Labels: Blocker

#1413 Cleanup browser console
  web-local/src/lib/components/navigation/NavigationEntry.svelte
  web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte
Labels: Blocker

#1412 Improve the default display name for a new dashboard
  web-local/src/lib/application-state-stores/metrics-internal-store.ts
  web-local/src/lib/components/metrics-definition/MetricsDefinitionGenerateButton.svelte
  web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte
  web-local/src/lib/components/navigation/models/ModelMenuItems.svelte
  web-local/src/lib/components/workspace/model/inspector/header/CreateDashboardButton.svelte
  web-local/src/lib/svelte-query/actions.ts
Labels: Blocker

#1463 Add SQL keywords
  web-local/src/lib/components/Editor.svelte
Labels: _application_

#1508 Remove old global declarations
  .eslintrc.cjs
  web-local/global.d.ts
  web-local/vite.config.ts
Labels: code quality

#1528 Move onboarding into `web-common/features/onboarding` directory
  web-common/src/features/onboarding/OnboardingWorkspace.svelte
  web-common/src/features/onboarding/index.ts
  web-local/src/lib/components/workspace/index.ts
  web-local/src/routes/(application)/+page.svelte
Labels: code quality

#1506 Remove unused util files
  web-local/src/lib/util/RillActionsChannel.ts
  web-local/src/lib/util/Throttler.ts
  web-local/src/lib/util/getParquetFiles.ts
  web-local/src/lib/util/initLocalConfig.ts
  web-local/src/lib/util/queryUtils.ts
  web-local/src/lib/util/shallowCopy.ts
Labels: code quality
