Repository rilldata/rill, pull requests merged in 2022-09, with the labels that each got.

#870 Cleanup console warnings
  src/lib/components/column-profile/CollapsibleTableSummary.svelte
  src/lib/components/leaderboard/LeaderboardMeasureSelector.svelte
  src/lib/components/menu/compositions/SelectMenu.svelte
  src/lib/components/menu/triggers/SelectButton.svelte
  src/routes/_surfaces/inspector/SourceInspector.svelte
  src/routes/dev/source-gallery.svelte
Labels: code quality

#871 Use "metrics view" not "metric view" terminology
  src/cli/StartCommand.ts
  src/common/database-service/DatabaseMetricsExplorerActions.ts
  src/common/database-service/utils.ts
  src/common/rill-developer-service/MetricsViewActions.ts
  src/common/rill-developer-service/RillDeveloperService.ts
  src/lib/application-state-stores/explorer-stores.ts
  src/lib/components/leaderboard/LeaderboardMeasureSelector.svelte
  src/lib/components/metrics-definition/MetricsDefinitionExploreMetricsButton.svelte
  src/lib/redux-store/model/model-apis.ts
  src/lib/redux-store/utils/invalidateExplorerThunk.ts
  src/lib/svelte-query/queries/metrics-view.ts
  src/routes/_surfaces/workspace/explore/ExploreHeader.svelte
  src/routes/_surfaces/workspace/explore/filters/Filters.svelte
  src/routes/_surfaces/workspace/explore/leaderboards/Leaderboard.svelte
  src/routes/_surfaces/workspace/explore/leaderboards/LeaderboardDisplay.svelte
  src/routes/_surfaces/workspace/explore/time-controls/TimeControls.svelte
  src/routes/_surfaces/workspace/explore/time-controls/TimeRangeNameSelector.svelte
  src/routes/_surfaces/workspace/explore/time-series-charts/MetricsTimeSeriesCharts.svelte
  src/routes/_surfaces/workspace/metrics-def/MetricsDefWorkspace.svelte
  src/server/ExpressServer.ts
  src/server/controllers/MetricsViewController.ts
  src/server/serverFactory.ts
  test/data/MetricsExplorer.data.ts
  test/functional/metrics-view.spec.ts
  test/functional/time-series.spec.ts
  test/utils/time-series-helpers.ts
Labels: code quality

#887 Remove tailwind console warning
  tailwind.config.cjs
Labels: code quality

#886 Upgrade SvelteKit
  Dockerfile
  docs/docs/contributors/development.md
  package-lock.json
  package.json
  src/lib/components/Portal.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/dev/+layout.svelte
  svelte.config.js
  test/ui/DataModeler.spec.ts
  tsconfig.json
  vite.config.ts
Labels: _application_

#922 Fix "Quick Metrics" bug in dashboard
  src/lib/application-state-stores/explorer-stores.ts
  src/lib/components/metrics-definition/MetricsDefinitionGenerateButton.svelte
  src/lib/redux-store/measure-definition/measure-definition-slice.ts
Labels: bug

#866 handle more sql node types
  sql/src/main/java/com/rilldata/protobuf/SqlNodeProtoBuilder.java
Labels: _platform_

#884 initial support for duckdb numeric operators
  sql/pom.xml
  sql/src/main/java/com/rilldata/calcite/CalciteToolbox.java
  sql/src/main/java/com/rilldata/calcite/operators/RillOperatorTable.java
  sql/src/main/java/com/rilldata/calcite/utility/CalciteUtils.java
  sql/src/test/java/com/rilldata/CalciteTests.java
  sql/src/test/java/com/rilldata/StaticSchemaTest.java
Labels: _platform_

#885 Information Schema Impl for Druid
  go.mod
  go.sum
  runtime/infra/druid/druid.go
  runtime/infra/druid/druid_test.go
  runtime/infra/duckdb/duckdb.go
  runtime/infra/duckdb/duckdb_test.go
  runtime/infra/infra.go
Labels: _platform_

#926 Druid dialect
  sql/src/main/java/com/rilldata/SqlConverter.java
  sql/src/main/java/com/rilldata/SqlConverterEntrypoint.java
  sql/src/main/java/com/rilldata/SqlConverterMain.java
  sql/src/main/java/com/rilldata/calcite/CalciteToolbox.java
  sql/src/main/java/com/rilldata/calcite/dialects/Dialects.java
  sql/src/main/java/com/rilldata/calcite/dialects/DruidDialect.java
  sql/src/main/java/com/rilldata/calcite/extensions/SqlCreateMetric.java
  sql/src/main/java/com/rilldata/calcite/operators/RillOperatorTable.java
  sql/src/main/java/com/rilldata/calcite/utility/CalciteUtils.java
  sql/src/test/java/com/rilldata/CalciteTests.java
  sql/src/test/java/com/rilldata/StaticSchemaTest.java
Labels: _platform_

#943 Automatically navigate to newly created source
  src/lib/util/file-upload.ts
Labels: _application_

#947 Fix navigation to expanded dimension tables
  src/lib/components/workspace/explore/leaderboards/DimensionDisplay.svelte
  src/routes/dashboard/[id]/+page.svelte
Labels: bug, _application_

#958 Fix href
  web-local/src/lib/components/assets/index.svelte
Labels: bug

#952 Redirect 500 errors to the metrics definition page
  web-local/src/common/errors/ErrorMessages.ts
  web-local/src/common/rill-developer-service/MetricsViewActions.ts
  web-local/src/lib/components/assets/MetricsDefinitionAssets.svelte
  web-local/src/routes/dashboard/[id]/+page.ts
  web-local/src/routes/dashboard/[id]/edit/+page.ts
Labels: bug

#951 Create a basic error page
  web-local/src/routes/+error.svelte
Labels: _application_

#931 Create source syntax
  sql/src/main/codegen/config.fmpp
  sql/src/main/codegen/includes/create-metric.ftl
  sql/src/main/codegen/includes/create-source.ftl
  sql/src/main/java/com/rilldata/SqlConverter.java
  sql/src/main/java/com/rilldata/SqlConverterEntrypoint.java
  sql/src/main/java/com/rilldata/SqlConverterMain.java
  sql/src/main/java/com/rilldata/calcite/CalciteToolbox.java
  sql/src/main/java/com/rilldata/calcite/models/ArtifactType.java
  sql/src/main/java/com/rilldata/calcite/models/SqlCreateMetricsView.java
  sql/src/main/java/com/rilldata/calcite/models/SqlCreateSource.java
  sql/src/main/java/com/rilldata/calcite/validators/CreateMetricsViewValidator.java
  sql/src/main/java/com/rilldata/calcite/validators/CreateSourceValidator.java
  sql/src/main/java/com/rilldata/calcite/validators/S3ConnectorValidator.java
  sql/src/main/java/com/rilldata/calcite/visitors/ExtractArtifact.java
  sql/src/main/java/com/rilldata/calcite/visitors/MetricsViewExpander.java
  sql/src/main/java/com/rilldata/protobuf/SqlNodeProto.proto
  sql/src/main/java/com/rilldata/protobuf/SqlNodeProtoBuilder.java
  sql/src/test/java/com/rilldata/CalciteTests.java
Labels: _platform_
