Repository rilldata/rill, pull requests merged in 2022-08, with the labels that each got.

#726 Edit microcopy
  src/routes/_surfaces/assets/MetricsDefinitionAssets.svelte
  src/routes/_surfaces/assets/ModelAssets.svelte
  src/routes/_surfaces/assets/TableAssets.svelte
Labels: nit

#761 Use Rill logo for favicon
  static/favicon.png
Labels: task

#756 Edit copy
  src/routes/_surfaces/assets/TableAssets.svelte
Labels: nit

#816 Use prepare instead of execute for metrics validation
  src/common/database-service/DatabaseMetricsExplorerActions.ts
Labels: performance
