Repository rilldata/rill, pull requests merged in 2022-10, with the labels that each got.

#993 create source syntax improvements
  sql/src/main/codegen/includes/create-source.ftl
  sql/src/main/java/com/rilldata/calcite/models/SqlCreateSource.java
  sql/src/test/java/com/rilldata/CalciteTests.java
Labels: _platform_

#1006 single method to get ast
  runtime/sql/sql.go
  runtime/sql/sql_test.go
  sql/pom.xml
  sql/src/main/java/com/rilldata/SqlConverter.java
  sql/src/main/java/com/rilldata/SqlConverterEntrypoint.java
  sql/src/main/java/com/rilldata/calcite/CalciteToolbox.java
  sql/src/main/java/com/rilldata/calcite/models/InMemoryArtifactManager.java
  sql/src/main/java/com/rilldata/calcite/visitors/MetricsViewExpander.java
  sql/src/test/java/com/rilldata/CalciteTests.java
Labels: _platform_

#1035 Fix broken link
  docs/docs/defining-metrics.md
Labels: bug, documentation

#1078 Edit copy
  runtime/connectors/gcs/gcs.go
  runtime/connectors/s3/s3.go
  web-local/build-tools/postinstall_runtime.sh
  web-local/src/lib/components/assets/sources/RemoteSource.svelte
Labels: _application_

#1102 Handle a few more error cases in Remote Sources form
  web-local/src/lib/components/assets/sources/RemoteSource.svelte
Labels: bug

#1128 Fixing npm build
  package-lock.json
  web-local/package.json
Labels: Blocker
