Repository rilldata/rill, pull requests merged in 2023-11, with the labels that each got.

#3362 Adding support for round_to_grain for APIs
  runtime/queries/metricsview_aggregation.go
  runtime/queries/metricsview_comparison_toplist.go
  runtime/queries/metricsview_timeseries.go
  runtime/queries/metricsview_timeseries_test.go
  runtime/queries/timeutil.go
  runtime/queries/timeutil_test.go
  runtime/reconcilers/report.go
Labels: blocker

#3319 use sqlite as catalog for local
  cli/pkg/local/app.go
  runtime/compilers/rillv1/init.go
  runtime/compilers/rillv1beta/project.go
  runtime/connection_cache_test.go
  runtime/connections.go
  runtime/drivers/registry.go
  runtime/drivers/registry_test.go
  runtime/drivers/sqlite/migrations/0015.sql
  runtime/drivers/sqlite/registry.go
  runtime/registry_test.go
  runtime/runtime.go
  runtime/testruntime/testruntime.go
Labels: blocker

#3435 Wrap longer labels for big number
  web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
Labels: applications

#3463 docs: add timezone for dashboard.yaml
  docs/docs/reference/project-files/dashboards.md
Labels: applications

#3455 Send corring time controls to shceduled exports
  web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte
  web-common/src/features/dashboards/dimension-table/dimension-table-export-utils.ts
Labels: blocker

#3466 Scheduled reports creation fixes
  web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte
  web-common/src/features/dashboards/scheduled-reports/CreateScheduledReportModal.svelte
Labels: blocker

#3459 Make scheduled reports timezone-aware
  web-admin/src/features/scheduled-reports/history/ReportHistoryTable.svelte
  web-admin/src/features/scheduled-reports/history/ReportHistoryTableCompositeCell.svelte
  web-admin/src/features/scheduled-reports/listing/ReportsTable.svelte
  web-admin/src/features/scheduled-reports/listing/ReportsTableCompositeCell.svelte
  web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte
  web-admin/src/features/scheduled-reports/metadata/utils.ts
  web-admin/src/features/scheduled-reports/tableUtils.ts
  web-common/src/components/menu-v2/MenuItem.svelte
  web-common/src/components/menu-v2/MenuItems.svelte
  web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte
  web-common/src/features/dashboards/scheduled-reports/CreateScheduledReportModal.svelte
  web-common/src/lib/time/timezone/index.ts
Labels: blocker

#3410 Bugbash: bar sizing
  web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
  web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardListItem.svelte
  web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
  web-common/src/features/dashboards/state-managers/selectors/dimension-table.ts
Labels: bug, blocker

#3432 3429: Fallback to a query execution if BQ Storage API cannot be used
  runtime/drivers/bigquery/sql_store.go
Labels: bug, blocker

#3460 Update tooltips for Big number
  web-common/app.d.ts
  web-common/src/app.css
  web-common/src/features/dashboards/big-number/BigNumberTooltipContent.svelte
  web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
  web-local/test/ui/dashboards.spec.ts
Labels: blocker

#3465 Refactor: Remove defaults for dimension comparison
  web-common/src/features/dashboards/dimension-table/DimensionFilterGutter.svelte
  web-common/src/features/dashboards/dimension-table/DimensionTable.svelte
  web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardItemFilterIcon.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardListItem.svelte
  web-common/src/features/dashboards/leaderboard/__stories__/LeaderboardListItem.stories.svelte
  web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
  web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
  web-common/src/features/dashboards/time-series/multiple-dimension-queries.ts
  web-common/src/features/dashboards/time-series/utils.spec.ts
  web-common/src/features/dashboards/time-series/utils.ts
Labels: blocker

#3473 Rill Developer: account for long file names
  web-common/src/components/button/Button.svelte
  web-common/src/features/sources/modal/SourceImportedModal.svelte
  web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte
  web-common/src/layout/workspace/WorkspaceHeader.svelte
Labels: bug

#3474 Fix: fallback to dashboard `name` when no `title` in the Cloud UI dashboards table
  web-admin/src/features/dashboards/listing/DashboardsTableCompositeCell.svelte
Labels: bug

#3469 Improve design of the Scheduled Report page
  web-admin/src/features/scheduled-reports/history/ReportHistoryTable.svelte
  web-admin/src/features/scheduled-reports/history/ReportHistoryTableHeader.svelte
  web-admin/src/features/scheduled-reports/metadata/MetadataLabel.svelte
  web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte
  web-admin/src/features/scheduled-reports/metadata/ReportOwnerBlock.svelte
  web-admin/src/routes/[organization]/[project]/-/reports/[report]/+page.svelte
  web-common/src/components/menu-v2/MenuItem.svelte
Labels: blocker

#3470 Bugfixes in Scheduled Reports table
  web-admin/src/features/scheduled-reports/listing/ReportOwnerBullet.svelte
  web-admin/src/features/scheduled-reports/listing/ReportsTable.svelte
  web-admin/src/features/scheduled-reports/listing/ReportsTableCompositeCell.svelte
Labels: blocker

#3486 fix: handle missing time zone as UTC in Scheduled Report's Next run date
  web-admin/src/features/scheduled-reports/metadata/utils.ts
Labels: bug

#3501 Fix "Your project is hibernating" CTA
  web-admin/src/features/projects/RedeployProjectCTA.svelte
  web-admin/src/routes/[organization]/[project]/+layout.svelte
  web-admin/src/routes/[organization]/[project]/+page.svelte
Labels: bug

#3495 Dimension label exporting fix
  runtime/queries/metricsview_comparison_toplist.go
  runtime/queries/metricsview_comparison_toplist_test.go
  runtime/testruntime/testdata/ad_bids_2rows/dashboards/ad_bids_metrics.yaml
Labels: bug

#3498 Druid comparison fix: ResourceLimitExceededException: Subquery generated results beyond maximum rows
  runtime/queries/metricsview_comparison_toplist.go
Labels: bug

#3491 Fix "no data", "prev_value", and a tooltip issue
  web-common/src/components/data-types/FormattedDataType.svelte
  web-common/src/components/data-types/MeasureChange.svelte
  web-common/src/components/data-types/PercentageChange.svelte
  web-common/src/components/data-types/type-utils.ts
  web-common/src/features/dashboards/dimension-table/dimension-table-types.ts
  web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
  web-common/src/lib/formatters.ts
Labels: bug, applications

#3431 Refactoring time controls to use iso time ranges instead of labels
  web-common/src/features/dashboards/dimension-table/dimension-table-export-utils.ts
  web-common/src/features/dashboards/proto-state/fromProto.ts
  web-common/src/features/dashboards/proto-state/proto.spec.ts
  web-common/src/features/dashboards/proto-state/toProto.ts
  web-common/src/features/dashboards/stores/dashboard-stores-test-data.ts
  web-common/src/features/dashboards/stores/dashboard-stores.spec.ts
  web-common/src/features/dashboards/stores/dashboard-stores.ts
  web-common/src/features/dashboards/time-controls/TimeComparisonSelector.svelte
  web-common/src/features/dashboards/time-controls/TimeControls.svelte
  web-common/src/features/dashboards/time-controls/TimeRangeSelector.svelte
  web-common/src/features/dashboards/time-controls/time-control-store.spec.ts
  web-common/src/features/dashboards/time-controls/time-control-store.ts
  web-common/src/features/dashboards/time-dimension-details/time-dimension-data-store.ts
  web-common/src/lib/time/comparisons/index.ts
  web-common/src/lib/time/config.ts
  web-common/src/lib/time/ranges/index.ts
  web-common/src/lib/time/ranges/iso-ranges.ts
  web-common/src/lib/time/types.ts
Labels: Type:Feature, Area:Time, Release Notes

#3552 Clean up web dependencies
  package-lock.json
  package.json
  web-admin/package.json
  web-admin/src/features/projects/ProjectDeploymentStatusChip.svelte
  web-auth/package.json
  web-common/package.json
  web-common/src/features/dashboards/dashboard-fetch-mocks.ts
  web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte
  web-common/svelte.config.js
  web-local/package.json
  web-local/test/ui/dashboards.spec.ts
Labels: dependencies

#3565 Remove disabled test and unused dependency
  package-lock.json
  web-common/package.json
  web-common/src/features/sources/ExtractTableName.spec.disabled.ts
Labels: dependencies

#3582 Add back Storybook smoketest dependencies
  package-lock.json
  web-common/package.json
Labels: dependencies

#3581 Fix time zone bug in "Edit report" form
  web-common/src/features/scheduled-reports/EditScheduledReportDialog.svelte
Labels: Type:Bug
