Repository rilldata/rill, pull requests merged in 2023-12, with the labels that each got.

#3607 Remove leftover `jest` dependencies
  .gitignore
  package-lock.json
  web-common/jest.config.json
  web-common/package.json
  web-common/src/components/data-graphic/state/cascading-context-store.spec.disabled.ts
  web-common/src/runtime-client/http-request-queue/HttpRequestQueue.spec.disabled.ts
  web-common/test/global-test-setup.ts
  web-local/jest.config.json
  web-local/package.json
Labels: dependencies

#3608 Remove old dev script
  web-local/dev.ts
Labels: nit

#3600 Fix auth redirect on the Dashboard page
  web-admin/src/client/utils.ts
  web-admin/src/features/errors/error-utils.ts
Labels: Type:Bug

#3623 Fixing model table not updating after fixing the model sql
  web-common/src/features/entity-management/resource-invalidations.ts
Labels: blocker

#3627 Runtime: Reduce chance and impact of deadlocked DuckDB calls
  runtime/controller.go
  runtime/drivers/duckdb/config_test.go
  runtime/drivers/duckdb/duckdb.go
  runtime/drivers/duckdb/olap.go
  runtime/drivers/duckdb/olap_crud_test.go
  runtime/drivers/duckdb/transporter_motherduck_to_duckDB.go
  runtime/drivers/duckdb/transporter_postgres_to_duckDB_test.go
  runtime/drivers/duckdb/transporter_sqlite_to_duckDB_test.go
  runtime/drivers/duckdb/transporter_sqlstore_to_duckDB.go
  runtime/drivers/duckdb/transporter_test.go
  runtime/registry_test.go
Labels: blocker

#3634 Remove Babel from `web-local`
  package-lock.json
  web-local/.babelrc
  web-local/package.json
Labels: dependencies

#3605 User-friendly error instead of "Out of buffer" on ingesting TIME column from Snowflake
  runtime/drivers/snowflake/sql_store.go
Labels: blocker

#3590 Embedded dashboards
  admin/server/deployment.go
  cli/cmd/service/service.go
  docs/docs/integration/embedding.md
  docs/docs/reference/cli/service/create.md
  docs/docs/reference/cli/service/delete.md
  docs/docs/reference/cli/service/list.md
  docs/docs/reference/cli/service/rename.md
  docs/docs/reference/cli/service/service.md
  docs/docs/reference/cli/service/token/issue.md
  docs/docs/reference/cli/service/token/list.md
  docs/docs/reference/cli/service/token/revoke.md
  docs/docs/reference/cli/service/token/token.md
  proto/gen/rill/admin/v1/admin.swagger.yaml
  proto/gen/rill/admin/v1/api.pb.go
  proto/gen/rill/admin/v1/api.pb.gw.go
  proto/gen/rill/admin/v1/api.pb.validate.go
  proto/gen/rill/admin/v1/api_grpc.pb.go
  proto/rill/admin/v1/api.proto
  web-admin/src/client/gen/admin-service/admin-service.ts
  web-admin/src/client/gen/index.schemas.ts
  web-admin/src/routes/+layout.svelte
  web-admin/src/routes/-/embed/+layout.svelte
  web-admin/src/routes/-/embed/+page.svelte
  web-common/src/app.css
  web-common/src/proto/gen/rill/admin/v1/api_pb.ts
  web-common/src/proto/gen/rill/admin/v1/internal_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/api_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/catalog_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/colors_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/connectors_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/export_format_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/queries_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/resources_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/schema_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/time_grain_pb.ts
  web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
Labels: blocker

#3639 Only apply `overscroll-behavior: none` to Rill Developer
  web-common/src/app.css
  web-common/src/layout/RillDeveloperLayout.svelte
Labels: Team:Applications

#3638 Add last refresh time to dashboard
  web-admin/src/features/dashboards/listing/DashboardList.svelte
  web-admin/src/features/dashboards/listing/DashboardsTable.svelte
  web-admin/src/features/dashboards/listing/LastRefreshedDate.svelte
  web-admin/src/features/dashboards/listing/selectors.ts
  web-admin/src/features/navigation/Breadcrumbs.svelte
  web-admin/src/features/navigation/TopNavigationBar.svelte
  web-admin/src/features/projects/ProjectDashboardsListener.svelte
  web-admin/src/features/projects/ProjectDeploymentStatus.svelte
  web-admin/src/features/projects/ProjectDeploymentStatusChip.svelte
  web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte
Labels: Area:Dashboard

#3668 Fix text wrapping in the Imported Source dialog
  web-common/src/features/sources/modal/SourceImportedModal.svelte
Labels: Type:Bug

#3676 Adding backwards compatibility for older time comparison
  web-common/src/features/dashboards/proto-state/fromProto.ts
Labels: blocker

#3494 Adding support for daylight savings time in timeseries queries
  cli/cmd/org/org_test.go
  cli/cmd/service/service_test.go
  cli/cmd/user/user_test.go
  cli/pkg/mock/server.go
  runtime/pkg/timeutil/timeutil.go
  runtime/pkg/timeutil/timeutil_test.go
  runtime/queries/metricsview.go
  runtime/queries/metricsview_timeseries.go
  runtime/queries/metricsview_timeseries_test.go
  runtime/queries/timeutil.go
  runtime/testruntime/testdata/timeseries/dashboards/timeseries_dst_backwards.yaml
  runtime/testruntime/testdata/timeseries/dashboards/timeseries_dst_forwards.yaml
  runtime/testruntime/testdata/timeseries/models/timeseries_dst_backwards_model.sql
  runtime/testruntime/testdata/timeseries/models/timeseries_dst_forwards_model.sql
  web-common/src/features/dashboards/time-series/MeasureChart.svelte
Labels: Type:Bug, blocker

#3698 Fix theme colors and remove warning
  web-common/tailwind.config.cjs
Labels: blocker

#3719 Adding CONTINUOUS to comparison backwards compatibility code in url state loader
  web-common/src/features/dashboards/proto-state/fromProto.ts
Labels: blocker

#3736 Introduce ShadCN UI via the `DropdownMenu` component set
  package-lock.json
  web-common/components.json
  web-common/package.json
  web-common/src/app.css
  web-common/src/components/dropdown-menu/DropdownMenuCheckboxItem.svelte
  web-common/src/components/dropdown-menu/DropdownMenuContent.svelte
  web-common/src/components/dropdown-menu/DropdownMenuItem.svelte
  web-common/src/components/dropdown-menu/DropdownMenuLabel.svelte
  web-common/src/components/dropdown-menu/DropdownMenuRadioGroup.svelte
  web-common/src/components/dropdown-menu/DropdownMenuRadioItem.svelte
  web-common/src/components/dropdown-menu/DropdownMenuSeparator.svelte
  web-common/src/components/dropdown-menu/DropdownMenuShortcut.svelte
  web-common/src/components/dropdown-menu/DropdownMenuSubContent.svelte
  web-common/src/components/dropdown-menu/DropdownMenuSubTrigger.svelte
  web-common/src/components/dropdown-menu/__stories__/DropdownMenu.stories.svelte
  web-common/src/components/dropdown-menu/index.ts
  web-common/src/lib/shadcn.ts
  web-common/tailwind.config.cjs
Labels: design, dependencies

#3741 Fix "View As" functionality in Cloud UI
  web-admin/src/features/view-as-user/setViewedAsUser.ts
Labels: Type:Bug
