Repository rilldata/rill, pull requests merged in 2023-02, with the labels that each got.

#1699 Disable sync-on-navigate & sync-on-focus
  web-common/src/features/entity-management/sync-file-system.ts
Labels: _application_

#1737 adds JSON stringified copy values for nested types
  web-local/src/lib/components/column-profile/column-types/details/TopK.svelte
  web-local/src/lib/components/virtualized-table/core/Cell.svelte
Labels: bug, Blocker

#1745 Move http request queue into `runtime-client`
  web-common/src/runtime-client/http-client.ts
  web-common/src/runtime-client/http-request-queue/Heap.ts
  web-common/src/runtime-client/http-request-queue/HttpRequestQueue.spec.ts
  web-common/src/runtime-client/http-request-queue/HttpRequestQueue.ts
  web-common/src/runtime-client/http-request-queue/HttpRequestQueueTypes.ts
  web-common/src/runtime-client/http-request-queue/priorities.ts
  web-local/src/lib/components/column-profile/column-types/NumericProfile.svelte
  web-local/src/lib/components/column-profile/queries.ts
Labels: code quality

#1645 Remove old code
  web-common/src/features/dashboards/time-controls/TimeRangeNameSelector.svelte
  web-local/src/lib/temp/errors/ErrorMessages.ts
Labels: code quality

#1721 Add a custom time range option to the dashboard's time picker
  web-common/src/components/menu/core/MenuItem.svelte
  web-common/src/features/dashboards/dashboard-stores.ts
  web-common/src/features/dashboards/selectors.ts
  web-common/src/features/dashboards/time-controls/CustomTimeRangeInput.svelte
  web-common/src/features/dashboards/time-controls/CustomTimeRangeMenuItem.svelte
  web-common/src/features/dashboards/time-controls/NoTimeDimensionCTA.svelte
  web-common/src/features/dashboards/time-controls/TimeControls.svelte
  web-common/src/features/dashboards/time-controls/TimeGrainSelector.svelte
  web-common/src/features/dashboards/time-controls/TimeRangeNameSelector.svelte
  web-common/src/features/dashboards/time-controls/TimeRangeSelector.svelte
  web-common/src/features/dashboards/time-controls/time-control-types.ts
  web-common/src/features/dashboards/time-controls/time-range-utils.spec.ts
  web-common/src/features/dashboards/time-controls/time-range-utils.ts
  web-common/src/features/models/selectors.ts
Labels: _application_

#1760 Adding new fields into telemetry
  package-lock.json
  web-local/package.json
  web-local/src/lib/metrics/service/MetricsService.ts
Labels: application

#1756 Calendly integration for dashboard publish
  web-common/src/components/modal/ModalContainer.svelte
  web-common/src/components/modal/dialog/Dialog.svelte
  web-common/src/features/dashboards/Calendly.svelte
  web-common/src/features/dashboards/DashboardAssets.svelte
  web-common/src/features/dashboards/dashboard-stores.ts
  web-common/src/features/dashboards/workspace/DashboardHeader.svelte
  web-common/src/features/metrics-views/workspace/MetricsExploreMetricsButton.svelte
  web-common/src/features/models/navigation/ModelMenuItems.svelte
  web-common/src/features/models/workspace/CreateDashboardButton.svelte
  web-common/src/features/sources/embedded/EmbeddedSourceMenuItems.svelte
  web-common/src/features/sources/navigation/SourceMenuItems.svelte
  web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte
  web-common/src/layout/RillDeveloperLayout.svelte
  web-local/src/app.html
  web-local/src/lib/metrics/BehaviourEventHandler.ts
  web-local/src/lib/metrics/initMetrics.ts
  web-local/src/lib/metrics/service/BehaviourEventFactory.ts
  web-local/src/lib/metrics/service/BehaviourEventTypes.ts
Labels: application

#1800 Fix race condition when configuring a dashboard's model
  web-common/src/features/metrics-views/metrics-internal-store.ts
  web-common/src/features/metrics-views/workspace/MetricsModelSelector.svelte
Labels: bug, Blocker

#1803 fixes tooltip issue in leaderboards; refines design of leaderboard tooltips
  web-common/src/components/virtualized-table/core/Cell.svelte
  web-common/src/features/dashboards/leaderboard/DimensionLeaderboardEntry.svelte
  web-common/src/features/dashboards/leaderboard/DimensionLeaderboardEntrySet.svelte
  web-common/src/layout/config.ts
Labels: Blocker

#1727 Add default time selectors to metrics config
  web-common/src/components/floating-element/WithTogglableFloatingElement.svelte
  web-common/src/components/menu/compositions/SelectMenu.svelte
  web-common/src/components/menu/triggers/SelectButton.svelte
  web-common/src/components/menu/wrappers/WithSelectMenu.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardMeasureSelector.svelte
  web-common/src/features/dashboards/time-controls/CustomTimeRangeInput.svelte
  web-common/src/features/dashboards/time-controls/TimeControls.svelte
  web-common/src/features/dashboards/time-controls/TimeGrainSelector.svelte
  web-common/src/features/dashboards/time-controls/TimeRangeSelector.svelte
  web-common/src/features/dashboards/time-controls/time-control-types.ts
  web-common/src/features/dashboards/time-controls/time-range-utils.spec.ts
  web-common/src/features/dashboards/time-controls/time-range-utils.ts
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
  web-common/src/features/dashboards/workspace/Dashboard.svelte
  web-common/src/features/metrics-views/metrics-internal-store.ts
  web-common/src/features/metrics-views/workspace/MetricsDisplayNameInput.svelte
  web-common/src/features/metrics-views/workspace/MetricsExploreMetricsButton.svelte
  web-common/src/features/metrics-views/workspace/MetricsModelSelector.svelte
  web-common/src/features/metrics-views/workspace/MetricsTimeColumnSelector.svelte
  web-common/src/features/metrics-views/workspace/MetricsWorkspace.svelte
  web-common/src/features/metrics-views/workspace/config-parameters/ConfigParameters.svelte
  web-common/src/features/metrics-views/workspace/config-parameters/DefaultTimeRangeSelector.svelte
  web-common/src/features/metrics-views/workspace/config-parameters/DisplayNameInput.svelte
  web-common/src/features/metrics-views/workspace/config-parameters/FormattedSelectorText.svelte
  web-common/src/features/metrics-views/workspace/config-parameters/ModelSelector.svelte
  web-common/src/features/metrics-views/workspace/config-parameters/QuickStartButton.svelte
  web-common/src/features/metrics-views/workspace/config-parameters/SmallestTimeGrainSelector.svelte
  web-common/src/features/metrics-views/workspace/config-parameters/TimeColumnSelector.svelte
  web-common/src/features/metrics-views/workspace/styles.ts
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.ts
Labels: application
