Repository rilldata/rill, pull requests merged in 2023-08, with the labels that each got.

#2859 issue while list service
  admin/server/service.go
Labels: _platform_

#2902 Fixing http used for dashboard redirect
  web-common/src/lib/url-utils.spec.ts
  web-common/src/lib/url-utils.ts
Labels: Blocker

#2892 Cloud UI: move Project logs to a dedicated page
  web-admin/src/components/navigation/Breadcrumbs.svelte
  web-admin/src/components/projects/ProjectBuilding.svelte
  web-admin/src/components/projects/ProjectDeploymentStatus.svelte
  web-admin/src/components/projects/ProjectErrored.svelte
  web-admin/src/routes/[organization]/[project]/+page.svelte
  web-admin/src/routes/[organization]/[project]/-/logs/+page.svelte
  web-common/src/components/tag/Tag.svelte
  web-common/src/components/tag/index.ts
Labels: Blocker

#2929 Cloud UI: Project page v2
  web-admin/src/components/projects/DashboardList.svelte
  web-admin/src/components/projects/ProjectDashboards.svelte
  web-admin/src/components/projects/ProjectDeploymentStatus.svelte
  web-admin/src/components/projects/ProjectHero.svelte
  web-admin/src/components/projects/dashboards.ts
  web-admin/src/routes/[organization]/[project]/+page.svelte
  web-common/src/components/icons/DashboardIcon.svelte
Labels: Blocker

#2930 Cloud UI: better Share Organization CTA
  web-admin/src/components/home/HomeShareCTA.svelte
  web-admin/src/components/organizations/OrganizationAccessControls.svelte
  web-admin/src/components/organizations/ShareOrganizationCTA.svelte
  web-admin/src/components/projects/DashboardList.svelte
  web-admin/src/components/projects/ProjectAccessControls.svelte
  web-admin/src/components/projects/ProjectBuilding.svelte
  web-admin/src/components/projects/ProjectErrored.svelte
  web-admin/src/components/projects/ProjectHero.svelte
  web-admin/src/components/projects/ShareProjectCTA.svelte
  web-admin/src/routes/+page.svelte
  web-admin/src/routes/[organization]/+page.svelte
Labels: Blocker

#2927 added pagination for listing user/orgs/projects
  cli/cmd/org/list.go
  cli/cmd/project/list.go
  cli/cmd/user/list.go
Labels: Blocker

#2908 2849: org and project name annotations for usage tracking
  admin/deployments.go
  admin/projects.go
  admin/server/organizations.go
  proto/gen/rill/runtime/v1/api.pb.go
  proto/gen/rill/runtime/v1/api.pb.gw.go
  proto/gen/rill/runtime/v1/api.pb.validate.go
  proto/gen/rill/runtime/v1/api_grpc.pb.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/rill/runtime/v1/api.proto
  runtime/registry.go
  runtime/registry_test.go
  runtime/server/instances.go
  web-common/src/proto/gen/rill/runtime/v1/api_pb.ts
  web-common/src/runtime-client/gen/index.schemas.ts
  web-common/src/runtime-client/gen/runtime-service/runtime-service.ts
Labels: Blocker

#2932 Add leaderboard sort direction toggling
  proto/rill/ui/v1/dashboard.proto
  web-common/src/features/dashboards/dashboard-stores.ts
  web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
  web-common/src/features/dashboards/dimension-table/DimensionTable.svelte
  web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
  web-common/src/features/dashboards/leaderboard-context-column.ts
  web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardContextColumnToggle.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardListItem.svelte
  web-common/src/features/dashboards/leaderboard/__stories__/LeaderboardHeader.stories.svelte
  web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
  web-common/src/features/dashboards/proto-state/derived-types.ts
  web-common/src/features/dashboards/proto-state/fromProto.ts
  web-common/src/features/dashboards/proto-state/toProto.ts
  web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
Labels: Release Notes

#2966 docs for granular access policies
  docs/docs/develop/policies.md
  docs/docs/reference/expressions.md
  docs/docs/reference/project-files/_category_.yml
  docs/docs/reference/project-files/dashboards.md
  docs/docs/reference/templating.md
  runtime/policies_test.go
  runtime/queries/column_timeseries.go
Labels: Blocker

#2988 Fix zoom bugs
  web-common/src/features/dashboards/time-series/MeasureChart.svelte
  web-common/src/features/dashboards/time-series/MeasureScrub.svelte
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
Labels: Blocker

#3002 Adding a fallback for file extension detection
  web-common/src/features/sources/sourceUtils.ts
Labels: Blocker

#3006 Use DuckDB SQL for access policy expressions
  docs/docs/develop/policies.md
  docs/docs/reference/expressions.md
  docs/docs/reference/project-files/dashboards.md
  go.mod
  go.sum
  runtime/compilers/rillv1/template.go
  runtime/pkg/duckdbsql/ast.go
  runtime/pkg/duckdbsql/ast_rewrite.go
  runtime/pkg/duckdbsql/ast_test.go
  runtime/pkg/duckdbsql/ast_traversal.go
  runtime/pkg/duckdbsql/duckdbsql.go
  runtime/pkg/duckdbsql/expression.go
  runtime/pkg/duckdbsql/expression_test.go
  runtime/policies_test.go
Labels: Blocker
