Repository rilldata/rill, pull requests merged in 2023-01, with the labels that each got.

#1554 Move models into `web-common/features/models` directory
  web-common/src/features/models/createModel.ts
  web-common/src/features/models/index.ts
  web-common/src/features/models/navigation/ModelAssets.svelte
  web-common/src/features/models/navigation/ModelMenuItems.svelte
  web-common/src/features/models/navigation/ModelTooltip.svelte
  web-common/src/features/models/query-highlight-store.ts
  web-common/src/features/models/selectors.ts
  web-common/src/features/models/utils/Debounce.ts
  web-common/src/features/models/utils/get-table-references/get-table-references.test.ts
  web-common/src/features/models/utils/get-table-references/index.ts
  web-common/src/features/models/utils/get-table-references/test-data.ts
  web-common/src/features/models/utils/sanitize-query.test.ts
  web-common/src/features/models/utils/sanitize-query.ts
  web-common/src/features/models/workspace/CreateDashboardButton.svelte
  web-common/src/features/models/workspace/Editor.svelte
  web-common/src/features/models/workspace/ModelBody.svelte
  web-common/src/features/models/workspace/ModelWorkspace.svelte
  web-common/src/features/models/workspace/ModelWorkspaceHeader.svelte
  web-common/src/features/models/workspace/inspector/ModelInspector.svelte
  web-common/src/features/models/workspace/inspector/ModelInspectorHeader.svelte
  web-common/src/features/models/workspace/inspector/ModelInspectorModelProfile.svelte
  web-common/src/features/models/workspace/inspector/WithModelResultTooltip.svelte
  web-common/src/features/sources/add-source/FileDrop.svelte
  web-common/src/features/sources/add-source/LocalSource.svelte
  web-common/src/features/sources/createModel.ts
  web-common/src/features/sources/navigation/SourceMenuItems.svelte
  web-common/src/features/sources/navigation/TableAssets.svelte
  web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte
  web-local/src/lib/application-state-stores/initialize-node-store-contexts.ts
  web-local/src/lib/components/navigation/Navigation.svelte
  web-local/src/lib/components/navigation/models/ExportError.svelte
  web-local/src/lib/components/workspace/index.ts
  web-local/src/lib/components/workspace/metrics-def/MetricsDefModelSelector.svelte
  web-local/src/routes/(application)/model/[name]/+page.svelte
Labels: code quality

#1543 fix rill init wipes out existing .gitignore
  cli/pkg/examples/example.go
  examples/ad_bids/.gitignore
  examples/default/.gitignore
  examples/sf_props/.gitignore
  runtime/compilers/rillv1beta/project.go
Labels: community

#1572 more from `r` to `f` for integer formatting in summary numbers
  web-local/src/lib/components/column-profile/column-types/details/SummaryNumberPlot.svelte
Labels: bug

#1459 Feature: dashboards without time series
  package-lock.json
  proto/gen/rill/runtime/v1/api.pb.go
  runtime/services/catalog/migrations_test.go
  runtime/services/catalog/migrator/metricsviews/metrics_views.go
  web-common/src/features/models/navigation/ModelMenuItems.svelte
  web-common/src/features/models/selectors.ts
  web-common/src/features/models/workspace/CreateDashboardButton.svelte
  web-common/src/features/models/workspace/ModelBody.svelte
  web-common/src/features/models/workspace/inspector/ModelInspector.svelte
  web-common/src/features/sources/navigation/SourceMenuItems.svelte
  web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte
  web-local/package.json
  web-local/src/lib/application-state-stores/metrics-internal-store.ts
  web-local/src/lib/components/leaderboard/LeaderboardMeasureSelector.svelte
  web-local/src/lib/components/metrics-definition/MetricsDefinitionExploreMetricsButton.svelte
  web-local/src/lib/components/metrics-definition/MetricsDefinitionGenerateButton.svelte
  web-local/src/lib/components/navigation/RenameAssetModal.svelte
  web-local/src/lib/components/table-editable/TableCellSelector.svelte
  web-local/src/lib/components/workspace/core/WorkspaceHeader.svelte
  web-local/src/lib/components/workspace/explore/Explore.svelte
  web-local/src/lib/components/workspace/explore/ExploreContainer.svelte
  web-local/src/lib/components/workspace/explore/ExploreHeader.svelte
  web-local/src/lib/components/workspace/explore/filters/Filters.svelte
  web-local/src/lib/components/workspace/explore/leaderboards/DimensionDisplay.svelte
  web-local/src/lib/components/workspace/explore/leaderboards/Leaderboard.svelte
  web-local/src/lib/components/workspace/explore/leaderboards/LeaderboardDisplay.svelte
  web-local/src/lib/components/workspace/explore/metrics-container/MeasureBigNumber.svelte
  web-local/src/lib/components/workspace/explore/metrics-container/MeasuresContainer.svelte
  web-local/src/lib/components/workspace/explore/metrics-container/MetricsTimeSeriesCharts.svelte
  web-local/src/lib/components/workspace/explore/metrics-container/TimeAxis.Svelte
  web-local/src/lib/components/workspace/explore/metrics-container/TimeSeriesBody.svelte
  web-local/src/lib/components/workspace/explore/metrics-container/TimeSeriesChartContainer.svelte
  web-local/src/lib/components/workspace/explore/time-controls/TimeControls.svelte
  web-local/src/lib/components/workspace/explore/time-series-charts/TimeSeriesChartContainer.svelte
  web-local/src/lib/components/workspace/metrics-def/MetricsDefModelSelector.svelte
  web-local/src/lib/components/workspace/metrics-def/MetricsDefTimeColumnSelector.svelte
  web-local/src/lib/svelte-query/dashboards.ts
Labels: Blocker

#1592 glob support for local, s3 and gcs - 2
  runtime/connectors/blob/blobdownloader_test.go
  runtime/connectors/gcs/gcs.go
  runtime/connectors/localfile/file.go
  runtime/connectors/s3/s3.go
  runtime/drivers/duckdb/connectors.go
  runtime/pkg/globutil/globutil.go
  runtime/pkg/globutil/globutil_test.go
  runtime/services/catalog/artifacts/yaml/objects.go
Labels: Blocker

#1625 Create `readonly` UI
  web-common/src/features/onboarding/OnboardingWorkspace.svelte
  web-common/src/runtime-client/manual-clients.ts
  web-local/src/lib/application-state-stores/application-store.ts
  web-local/src/lib/components/layouts/RillDeveloperApplicationLayout.svelte
  web-local/src/lib/components/navigation/Navigation.svelte
  web-local/src/lib/components/navigation/NavigationHeader.svelte
  web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte
  web-local/src/lib/components/workspace/explore/ExploreHeader.svelte
  web-local/src/routes/(application)/dashboard/[name]/+page.ts
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.ts
  web-local/src/routes/(application)/model/[name]/+page.ts
  web-local/src/routes/(application)/source/[name]/+page.ts
Labels: request, _application_

#1557 Bidirectional artifact editing
  runtime/services/catalog/migration_map.go
  runtime/services/catalog/migrations.go
  runtime/services/catalog/migrations_test.go
  web-common/src/features/models/workspace/Editor.svelte
  web-common/src/features/sources/workspace/SourceWorkspace.svelte
  web-common/src/features/sources/workspace/SourceWorkspaceBody.svelte
  web-common/src/features/sources/workspace/SourceWorkspaceErrorStates.svelte
  web-local/src/lib/application-state-stores/file-artifacts-store.ts
  web-local/src/lib/application-state-stores/overlay-store.ts
  web-local/src/lib/components/layouts/RillDeveloperApplicationLayout.svelte
  web-local/src/lib/components/layouts/sync-file-system.ts
  web-local/src/lib/components/metrics-definition/DimensionColumns.ts
  web-local/src/lib/components/workspace/explore/Explore.svelte
  web-local/src/lib/components/workspace/explore/ExploreHeader.svelte
  web-local/src/lib/components/workspace/explore/filters/Filters.svelte
  web-local/src/lib/components/workspace/explore/leaderboards/Leaderboard.svelte
  web-local/src/lib/components/workspace/metrics-def/MetricsDefDisplayNameInput.svelte
  web-local/src/lib/util/entity-mappers.ts
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.ts
Labels: Blocker

#1640 Create `features/entity-management` dir
  web-common/src/features/entity-management/RenameAssetModal.svelte
  web-common/src/features/entity-management/actions.ts
  web-common/src/features/entity-management/entity-mappers.spec.ts
  web-common/src/features/entity-management/entity-mappers.ts
  web-common/src/features/entity-management/file-artifacts-store.ts
  web-common/src/features/entity-management/getArtifactErrors.ts
  web-common/src/features/entity-management/name-utils.ts
  web-common/src/features/entity-management/selectors.ts
  web-common/src/features/entity-management/sync-file-system.ts
  web-common/src/features/entity-management/types.ts
  web-common/src/features/models/createModel.ts
  web-common/src/features/models/navigation/ModelAssets.svelte
  web-common/src/features/models/navigation/ModelMenuItems.svelte
  web-common/src/features/models/utils/get-table-references/index.ts
  web-common/src/features/models/workspace/CreateDashboardButton.svelte
  web-common/src/features/models/workspace/ModelBody.svelte
  web-common/src/features/models/workspace/ModelWorkspace.svelte
  web-common/src/features/models/workspace/ModelWorkspaceHeader.svelte
  web-common/src/features/models/workspace/inspector/ModelInspectorHeader.svelte
  web-common/src/features/models/workspace/inspector/ModelInspectorModelProfile.svelte
  web-common/src/features/sources/add-source/LocalSource.svelte
  web-common/src/features/sources/add-source/RemoteSource.svelte
  web-common/src/features/sources/add-source/createSource.ts
  web-common/src/features/sources/add-source/duplicateNameUtils.ts
  web-common/src/features/sources/createModel.ts
  web-common/src/features/sources/navigation/SourceMenuItems.svelte
  web-common/src/features/sources/navigation/TableAssets.svelte
  web-common/src/features/sources/refreshSource.ts
  web-common/src/features/sources/workspace/SourceInspector.svelte
  web-common/src/features/sources/workspace/SourceWorkspace.svelte
  web-common/src/features/sources/workspace/SourceWorkspaceErrorStates.svelte
  web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte
  web-common/src/features/temp/BlockingOverlayContainer.svelte
  web-common/src/features/temp/Spinner.svelte
  web-local/src/lib/application-state-stores/app-store.ts
  web-local/src/lib/components/column-profile/ColumnProfileIcon.svelte
  web-local/src/lib/components/dimension/DimensionHeader.svelte
  web-local/src/lib/components/layouts/RillDeveloperApplicationLayout.svelte
  web-local/src/lib/components/leaderboard/LeaderboardHeader.svelte
  web-local/src/lib/components/leaderboard/LeaderboardMeasureSelector.svelte
  web-local/src/lib/components/navigation/dashboards/MetricsDefinitionAssets.svelte
  web-local/src/lib/components/table-editable/ColumnConfig.ts
  web-local/src/lib/components/workspace/core/WorkspaceHeader.svelte
  web-local/src/lib/components/workspace/core/WorkspaceHeaderStatusSpinner.svelte
  web-local/src/lib/components/workspace/explore/Explore.svelte
  web-local/src/lib/components/workspace/explore/metrics-container/MeasureBigNumber.svelte
  web-local/src/lib/components/workspace/explore/metrics-container/MeasuresContainer.svelte
  web-local/src/lib/components/workspace/explore/metrics-container/MetricsTimeSeriesCharts.svelte
  web-local/src/lib/components/workspace/metrics-def/MetricsDefWorkspace.svelte
  web-local/src/lib/components/workspace/metrics-def/MetricsDefWorkspaceHeader.svelte
  web-local/src/lib/metrics/service/MetricsTypes.ts
  web-local/src/lib/svelte-query/actions.ts
  web-local/src/lib/svelte-query/invalidation.ts
  web-local/src/lib/util/getNextEntityId.ts
  web-local/src/routes/(application)/dashboard/[name]/+page.ts
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.ts
  web-local/src/routes/(application)/model/[name]/+page.ts
  web-local/src/routes/(application)/source/[name]/+page.ts
Labels: code quality
