Repository rilldata/rill, pull requests merged in 2024-01, with the labels that each got.

#3753 Runtime: Fix missing security policy row filters for new filter expressions
  runtime/queries/metricsview.go
  runtime/queries/metricsview_aggregation.go
  runtime/queries/metricsview_comparison_toplist.go
  runtime/queries/metricsview_rows.go
  runtime/queries/metricsview_timeseries.go
  runtime/queries/metricsview_toplist.go
  runtime/queries/metricsview_totals.go
  runtime/reconcilers/metrics_view.go
Labels: blocker

#3751 Allow resizing the height of the "Model Data" dashboard module in Rill Developer
  web-common/src/features/dashboards/rows-viewer/RowsViewer.svelte
  web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte
  web-common/src/layout/drag.ts
  web-common/src/layout/navigation/Navigation.svelte
Labels: blocker, community

#3765 tweak filter clearing behavior
  web-common/src/features/dashboards/filters/Filters.svelte
  web-common/src/features/dashboards/state-managers/actions/dimension-filters.ts
Labels: blocker

#3769 Fix issues with non string dimension filters
  web-common/src/features/dashboards/filters/Filters.svelte
  web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
  web-common/src/features/dashboards/state-managers/actions/dimension-filters.ts
  web-common/src/lib/arrayUtils.ts
Labels: Type:Bug, blocker

#3762 Use visible measures for timeseries request
  web-common/src/features/dashboards/big-number/MeasuresContainer.svelte
  web-common/src/features/dashboards/dimension-table/dimension-table-export-utils.ts
  web-common/src/features/dashboards/dimension-table/export-toplist.ts
  web-common/src/features/dashboards/proto-state/dashboard-url-state.spec.ts
  web-common/src/features/dashboards/state-managers/selectors/active-measure.ts
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
  web-common/src/features/dashboards/stores/dashboard-stores-test-data.ts
  web-common/src/features/dashboards/stores/dashboard-stores.ts
  web-common/src/features/dashboards/stores/metrics-explorer-entity.ts
  web-common/src/features/dashboards/time-series/timeseries-data-store.ts
Labels: blocker

#3767 Hide "Copy to clipboard" tooltip when Clipboard API not available
  web-common/src/components/column-profile/column-types/details/TopK.svelte
  web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampBound.svelte
  web-common/src/components/data-graphic/compositions/timestamp-profile/TimestampTooltipContent.svelte
  web-common/src/components/data-types/DataTypeIcon.svelte
  web-common/src/components/virtualized-table/core/Cell.svelte
  web-common/src/components/virtualized-table/core/ColumnHeader.svelte
  web-common/src/features/dashboards/big-number/BigNumberTooltipContent.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardTooltipContent.svelte
  web-common/src/features/models/navigation/ModelTooltip.svelte
  web-common/src/features/sources/navigation/SourceTooltip.svelte
  web-common/src/lib/actions/shift-click-action.ts
Labels: blocker, community

#3786 Add ShadCN's Data Table component set
  package-lock.json
  web-common/package.json
  web-common/src/components/table-shadcn/Table.svelte
  web-common/src/components/table-shadcn/TableBody.svelte
  web-common/src/components/table-shadcn/TableCaption.svelte
  web-common/src/components/table-shadcn/TableCell.svelte
  web-common/src/components/table-shadcn/TableFooter.svelte
  web-common/src/components/table-shadcn/TableHead.svelte
  web-common/src/components/table-shadcn/TableHeader.svelte
  web-common/src/components/table-shadcn/TableRow.svelte
  web-common/src/components/table-shadcn/__stories__/Table.stories.svelte
  web-common/src/components/table-shadcn/__stories__/data.ts
  web-common/src/components/table-shadcn/index.ts
Labels: Team:Applications, design, dependencies

#3758 Introduce backend flag to indicate that a deployed project is in an a…
  admin/database/database.go
  admin/database/postgres/migrations/0019.sql
  admin/database/postgres/postgres.go
  admin/database/postgres/postgres_test.go
  admin/deployments.go
  admin/projects.go
  admin/server/projects.go
  cli/cmd/sudo/project/get.go
  cli/cmd/sudo/project/search.go
  cli/cmd/sudo/sudo.go
  cli/cmd/sudo/tags/get.go
  cli/cmd/sudo/tags/set.go
  cli/cmd/sudo/tags/tags.go
  go.mod
  proto/gen/rill/admin/v1/admin.swagger.yaml
  proto/gen/rill/admin/v1/api.pb.go
  proto/gen/rill/admin/v1/api.pb.gw.go
  proto/gen/rill/admin/v1/api.pb.validate.go
  proto/gen/rill/admin/v1/api_grpc.pb.go
  proto/gen/rill/runtime/v1/api.pb.gw.go
  proto/gen/rill/runtime/v1/connectors.pb.gw.go
  proto/gen/rill/runtime/v1/queries.pb.gw.go
  proto/rill/admin/v1/api.proto
  web-admin/src/client/gen/admin-service/admin-service.ts
  web-admin/src/client/gen/index.schemas.ts
  web-common/src/proto/gen/rill/admin/v1/api_pb.ts
  web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
  web-common/src/runtime-client/gen/connector-service/connector-service.ts
  web-common/src/runtime-client/gen/query-service/query-service.ts
  web-common/src/runtime-client/gen/runtime-service/runtime-service.ts
Labels: Area:CLI

#3781 Cloud UI: add resource-level status to the project status page
  web-admin/src/features/dashboards/listing/selectors.ts
  web-admin/src/features/projects/ProjectDeploymentStatus.svelte
  web-admin/src/features/projects/ProjectParseErrors.svelte
  web-admin/src/features/projects/ProjectTabs.svelte
  web-admin/src/features/projects/getProjectErrors.ts
  web-admin/src/features/projects/selectors.ts
  web-admin/src/features/projects/status/ProjectDeploymentStatus.svelte
  web-admin/src/features/projects/status/ProjectDeploymentStatusChip.svelte
  web-admin/src/features/projects/status/ProjectGithubConnection.svelte
  web-admin/src/features/projects/status/ProjectParseErrors.svelte
  web-admin/src/features/projects/status/ProjectResources.svelte
  web-admin/src/features/projects/status/ProjectResourcesTable.svelte
  web-admin/src/features/projects/status/ResourceErrorMessage.svelte
  web-admin/src/features/projects/status/display-utils.ts
  web-admin/src/features/projects/status/selectors.ts
  web-admin/src/routes/[organization]/[project]/-/status/+page.svelte
  web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte
  web-common/src/components/tag/Tag.svelte
  web-common/src/features/entity-management/resource-selectors.ts
Labels: Team:Applications

#3787 Add redirect from Home page to (active) Org page
  web-admin/src/features/authentication/AvatarButton.svelte
  web-admin/src/features/navigation/Breadcrumbs.svelte
  web-admin/src/features/organizations/OrganizationHero.svelte
  web-admin/src/features/organizations/OrganizationList.svelte
  web-admin/src/features/organizations/OrganizationRedirect.svelte
  web-admin/src/features/organizations/ShareOrganizationCTA.svelte
  web-admin/src/features/organizations/activeOrg.ts
  web-admin/src/routes/+page.svelte
Labels: Team:Applications

#3813 Dashboard: Replace `ColumnTimeRange` request with `MetricsViewTimeRange` request
  web-common/src/features/dashboards/dashboard-fetch-mocks.ts
  web-common/src/features/dashboards/proto-state/dashboard-url-state.spec.ts
  web-common/src/features/dashboards/selectors/index.ts
  web-common/src/features/dashboards/state-managers/selectors/index.ts
  web-common/src/features/dashboards/state-managers/selectors/types.ts
  web-common/src/features/dashboards/state-managers/state-managers.ts
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
  web-common/src/features/dashboards/stores/dashboard-stores.ts
  web-common/src/features/dashboards/time-controls/time-control-store.spec.ts
  web-common/src/features/dashboards/time-controls/time-control-store.ts
  web-common/src/features/dashboards/time-controls/time-range-store.ts
Labels: Team:Applications, Area:Dashboard

#3806 add query retries in case druid returns 429
  runtime/drivers/druid/olap.go
Labels: blocker

#3827 Fix compatibility discrepancy between metrics filter and new expressions
  runtime/queries/metricsview.go
Labels: blocker

#3828 Added types for Druid Parquet exporting
  runtime/queries/metricsview_comparison_toplist.go
  runtime/queries/metricsview_comparison_toplist_test.go
Labels: blocker

#3725 CLI: ability to check health of all projects for support users
  admin/server/projects.go
  cli/cmd/sudo/project/search.go
Labels: Area:CLI

#3843 Cloud UI: Fix scroll issues
  web-admin/src/routes/+layout.svelte
  web-admin/src/routes/+page.svelte
  web-admin/src/routes/[organization]/+page.svelte
  web-admin/src/routes/[organization]/[project]/+page.svelte
  web-admin/src/routes/[organization]/[project]/-/reports/+page.svelte
  web-admin/src/routes/[organization]/[project]/-/reports/[report]/+page.svelte
  web-admin/src/routes/[organization]/[project]/-/status/+page.svelte
  web-common/src/layout/VerticalScrollContainer.svelte
Labels: Type:Bug

#3814 Dashboard: Remove calls to `TableColumns` API
  web-common/src/features/dashboards/rows-viewer/RowsViewer.svelte
  web-common/src/features/dashboards/time-controls/NoTimeDimensionCTA.svelte
  web-common/src/features/dashboards/time-controls/TimeControls.svelte
  web-common/src/features/models/selectors.ts
Labels: Team:Applications, Area:Dashboard

#3840 fix: respect user comparison mode
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
  web-common/src/features/dashboards/stores/dashboard-stores.spec.ts
  web-common/src/features/dashboards/stores/dashboard-stores.ts
  web-common/src/features/dashboards/time-controls/TimeControls.svelte
  web-common/src/features/dashboards/time-controls/time-range-store.ts
  web-local/tests/dashboards/dashboards.spec.ts
  web-local/tests/dashboards/leaderboard-and-dim-table-sort.spec.ts
  web-local/tests/dashboards/number-formatting.spec.ts
  web-local/tests/dashboards/time-controls-from-config.spec.ts
  web-local/tests/utils/dashboardHelpers.ts
Labels: blocker

#3900 Add state managers under the key by dash name
  web-admin/src/routes/-/embed/+page.svelte
  web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte
  web-local/src/routes/(application)/dashboard/[name]/+page.svelte
Labels: blocker

#3882 Cleaning up old filters references from UI
  web-common/src/features/dashboards/actions/index.ts
  web-common/src/features/dashboards/big-number/MeasuresContainer.svelte
  web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
  web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
  web-common/src/features/dashboards/proto-state/fromProto.ts
  web-common/src/features/dashboards/rows-viewer/RowsViewer.svelte
  web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte
  web-common/src/features/dashboards/rows-viewer/export-metrics.ts
  web-common/src/features/dashboards/state-managers/actions/dimension-filters.ts
  web-common/src/features/dashboards/state-managers/selectors/dimension-filters.ts
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
  web-common/src/features/dashboards/stores/dashboard-stores.ts
  web-common/src/features/dashboards/stores/filter-utils.ts
  web-common/src/features/dashboards/stores/metrics-explorer-entity.ts
  web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
Labels: blocker

#3880 Process Kafka producer events (delivery, errors, etc)
  runtime/pkg/activity/kafka.go
Labels: blocker

#3879 MySQL connector
  cli/cmd/runtime/start.go
  go.mod
  runtime/drivers/duckdb/transporter_mysql_to_duckDB_test.go
  runtime/drivers/mysql/mysql.go
  runtime/drivers/mysql/parser.go
  runtime/drivers/mysql/sql_store.go
  web-common/src/components/icons/connectors/MySQL.svelte
  web-common/src/features/sources/modal/AddSourceModal.svelte
  web-common/src/features/sources/modal/yupSchemas.ts
Labels: blocker

#3863 Update color theme 3860
  package-lock.json
  web-admin/src/features/dashboards/listing/DashboardList.svelte
  web-admin/src/features/dashboards/listing/DashboardsTableCompositeCell.svelte
  web-admin/src/features/projects/status/ProjectDeploymentStatusChip.svelte
  web-admin/src/features/scheduled-reports/listing/ReportsTableActionCell.svelte
  web-admin/src/features/scheduled-reports/listing/ReportsTableCompositeCell.svelte
  web-admin/tailwind.config.ts
  web-auth/src/components/EmailPassForm.svelte
  web-auth/src/components/SSOForm.svelte
  web-auth/tailwind.config.ts
  web-common/components.json
  web-common/package.json
  web-common/src/app.css
  web-common/src/components/button/Switch.svelte
  web-common/src/components/button/classes.ts
  web-common/src/components/callout/Callout.svelte
  web-common/src/components/calls-to-action/CTAButton.svelte
  web-common/src/components/chip/chip-types.ts
  web-common/src/components/column-profile/column-types/details/TopK.svelte
  web-common/src/components/column-profile/column-types/details/TopKListItem.svelte
  web-common/src/components/column-profile/column-types/sparks/TimestampSpark.svelte
  web-common/src/components/data-graphic/guides/PointLabel.svelte
  web-common/src/components/data-graphic/marks/ChunkedLine.svelte
  web-common/src/components/editor/line-status/LineNumberGutterMarker.svelte
  web-common/src/components/editor/line-status/StatusGutterMarker.svelte
  web-common/src/components/forms/Input.svelte
  web-common/src/components/forms/InputArray.svelte
  web-common/src/components/forms/InputV2.svelte
  web-common/src/components/forms/MultiSelectCombobox.svelte
  web-common/src/components/icons/RillLogoSquareNegative.svelte
  web-common/src/components/search/Search.svelte
  web-common/src/components/tag/Tag.svelte
  web-common/src/features/dashboards/config.ts
  web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte
  web-common/src/features/dashboards/time-dimension-details/util.ts
  web-common/src/features/dashboards/time-series/ChartBody.svelte
  web-common/src/features/dashboards/time-series/MeasureChart.svelte
  web-common/src/features/dashboards/time-series/MeasureScrub.svelte
  web-common/src/features/dashboards/time-series/MeasureValueMouseover.svelte
  web-common/src/features/dashboards/time-series/chart-colors.ts
  web-common/src/features/sources/modal/AddSourceModal.svelte
  web-common/src/features/sources/modal/SourceImportedModal.svelte
  web-common/src/features/themes/actions.ts
  web-common/src/features/themes/color-config.ts
  web-common/src/features/welcome/TitleContent.svelte
  web-common/tailwind.config.cjs
  web-common/tailwind.config.ts
  web-local/tailwind.config.ts
Labels: blocker

#3734 debounce update model when typing in code editor
  web-common/src/features/models/utils/Debounce.ts
  web-common/src/features/models/workspace/Editor.svelte
  web-common/src/features/models/workspace/ModelBody.svelte
  web-common/src/lib/create-debouncer.ts
Labels: blocker

#3842 Add TDD export button
  web-common/src/features/dashboards/time-dimension-details/TDDExportButton.svelte
  web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte
  web-common/src/features/dashboards/time-dimension-details/export-tdd.ts
  web-common/src/features/dashboards/time-series/multiple-dimension-queries.ts
Labels: blocker, community

#3815 Frontend integration of measure filters
  proto/rill/ui/v1/dashboard.proto
  web-common/src/components/chip/chip-types.ts
  web-common/src/components/chip/removable-list-chip/RemovableListBody.svelte
  web-common/src/components/forms/InputV2.svelte
  web-common/src/components/forms/Select.svelte
  web-common/src/components/menu-v2/Menu.svelte
  web-common/src/features/dashboards/big-number/MeasuresContainer.svelte
  web-common/src/features/dashboards/dashboard-utils.ts
  web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
  web-common/src/features/dashboards/dimension-table/dimension-table-export-utils.ts
  web-common/src/features/dashboards/dimension-table/export-toplist.ts
  web-common/src/features/dashboards/filters/FilterButton.svelte
  web-common/src/features/dashboards/filters/Filters.svelte
  web-common/src/features/dashboards/filters/formatFilters.ts
  web-common/src/features/dashboards/filters/getDisplayName.ts
  web-common/src/features/dashboards/filters/measure-filters/MeasureFilter.svelte
  web-common/src/features/dashboards/filters/measure-filters/MeasureFilterBody.svelte
  web-common/src/features/dashboards/filters/measure-filters/MeasureFilterMenu.svelte
  web-common/src/features/dashboards/filters/measure-filters/measure-filter-options.ts
  web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts
  web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
  web-common/src/features/dashboards/proto-state/fromProto.ts
  web-common/src/features/dashboards/proto-state/toProto.ts
  web-common/src/features/dashboards/rows-viewer/RowsViewer.svelte
  web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte
  web-common/src/features/dashboards/rows-viewer/export-metrics.ts
  web-common/src/features/dashboards/state-managers/actions/index.ts
  web-common/src/features/dashboards/state-managers/actions/measure-filters.ts
  web-common/src/features/dashboards/state-managers/selectors/dashboard-queries.ts
  web-common/src/features/dashboards/state-managers/selectors/dimension-filters.ts
  web-common/src/features/dashboards/state-managers/selectors/index.ts
  web-common/src/features/dashboards/state-managers/selectors/measure-filters.ts
  web-common/src/features/dashboards/state-managers/selectors/types.ts
  web-common/src/features/dashboards/state-managers/state-managers.ts
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
  web-common/src/features/dashboards/stores/dashboard-stores-test-data.ts
  web-common/src/features/dashboards/stores/filter-utils.ts
  web-common/src/features/dashboards/stores/metrics-explorer-entity.ts
  web-common/src/features/dashboards/time-series/multiple-dimension-queries.ts
  web-common/src/features/dashboards/time-series/timeseries-data-store.ts
  web-common/src/features/dashboards/time-series/totals-data-store.ts
  web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
Labels: blocker

#3921 Fix filter not applying in dimension table
  web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
Labels: blocker

#3920 Fix 'Add email' button
  web-common/src/components/button/Button.svelte
  web-common/src/components/forms/InputArray.svelte
Labels: Type:Bug

#3918 Fix CTA layout bug
  web-admin/src/routes/+layout.svelte
  web-common/src/components/calls-to-action/CTALayoutContainer.svelte
Labels: Type:Bug, blocker

#3937 Update clearAllFilters for measure filters
  web-common/src/features/dashboards/state-managers/actions/filters.ts
Labels: blocker

#3938 Add safeguard to time range summary calls to support dashboards without timestamp columns
  web-common/src/features/dashboards/selectors/index.ts
  web-common/src/features/dashboards/state-managers/state-managers.ts
Labels: blocker

#3939 Update all exports in dashboards to use measure filters
  web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
  web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte
  web-common/src/features/dashboards/dimension-table/export-toplist.ts
  web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts
  web-common/src/features/dashboards/rows-viewer/ExportModelDataButton.svelte
  web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte
  web-common/src/features/dashboards/rows-viewer/export-metrics.ts
  web-common/src/features/dashboards/time-dimension-details/export-tdd.ts
Labels: blocker

#3898 optimize toplist to have only needed measures
  proto/gen/rill/runtime/v1/queries.pb.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/rill/runtime/v1/queries.proto
  runtime/queries/metricsview_comparison_toplist.go
  runtime/queries/metricsview_comparison_toplist_test.go
  runtime/server/downloads.go
  runtime/server/queries_metrics.go
  runtime/server/queries_metrics_comparison_toplist_test.go
  web-common/src/features/dashboards/dashboard-utils.ts
  web-common/src/features/dashboards/dimension-table/dimension-table-export-utils.ts
  web-common/src/features/dashboards/dimension-table/export-toplist.ts
  web-common/src/proto/gen/rill/admin/v1/api_pb.ts
  web-common/src/proto/gen/rill/admin/v1/internal_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/api_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/catalog_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/colors_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/connectors_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/export_format_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/expression_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/queries_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/resources_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/schema_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/time_grain_pb.ts
  web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
  web-common/src/runtime-client/gen/index.schemas.ts
Labels: blocker

#3894 Refactor reports to just have the queryArgs. Build the state url in the UI.
  admin/server/reports.go
  admin/server/server.go
  proto/gen/rill/admin/v1/admin.swagger.yaml
  proto/gen/rill/admin/v1/api.pb.go
  proto/gen/rill/admin/v1/api.pb.validate.go
  proto/rill/admin/v1/api.proto
  runtime/drivers/admin.go
  runtime/drivers/admin/admin_store.go
  runtime/reconcilers/report.go
  web-admin/src/client/gen/index.schemas.ts
  web-admin/src/features/scheduled-reports/get-dashboard-state-for-report.ts
  web-admin/src/routes/[organization]/[project]/-/reports/[report]/open/+page.svelte
  web-common/src/features/compound-query-result.ts
  web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
  web-common/src/features/scheduled-reports/CreateScheduledReportDialog.svelte
  web-common/src/proto/gen/rill/admin/v1/api_pb.ts
Labels: blocker

#3953 Fix bug in line charts when the time controls are not ready
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
Labels: Type:Bug, blocker
