Repository rilldata/rill, pull requests merged in 2024-06, with the labels that each got.

#4975 Connectors: Add hierarchy to Table Explorer
  web-common/src/features/connectors/ConnectorEntry.svelte
  web-common/src/features/connectors/ConnectorExplorer.svelte
  web-common/src/features/connectors/olap/DatabaseEntry.svelte
  web-common/src/features/connectors/olap/DatabaseExplorer.svelte
  web-common/src/features/connectors/olap/DatabaseSchemaEntry.svelte
  web-common/src/features/connectors/olap/TableEntry.svelte
  web-common/src/features/connectors/olap/TableMenuItems.svelte
  web-common/src/features/connectors/olap/TablePreviewWorkspace.svelte
  web-common/src/features/connectors/olap/TableSchema.svelte
  web-common/src/features/connectors/olap/TableWorkspaceHeader.svelte
  web-common/src/features/connectors/olap/UnsupportedTypesIndicator.svelte
  web-common/src/features/connectors/olap/olap-config.ts
  web-common/src/features/connectors/olap/selectors.ts
  web-common/src/features/entity-management/AddAssetButton.svelte
  web-common/src/features/metrics-views/workspace/editor/Placeholder.svelte
  web-common/src/features/tables/TableExplorer.svelte
  web-common/src/features/tables/selectors.ts
  web-local/src/routes/(application)/connector/clickhouse/[database]/[table]/+page.svelte
  web-local/src/routes/(application)/connector/druid/[schema]/[table]/+page.svelte
  web-local/src/routes/(application)/connector/duckdb/[database]/[schema]/[table]/+page.svelte
  web-local/src/routes/(application)/connector/pinot/[table]/+page.svelte
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
Labels: blocker

#4994 Fix: stale pivot data on config change
  web-common/src/features/dashboards/pivot/PivotTable.svelte
  web-common/src/features/dashboards/pivot/pivot-data-store.ts
Labels: blocker

#5000 fix: flip closed connection bool
  web-common/src/runtime-client/watch-request-client.ts
Labels: blocker

#5002 Remove empty directories from initialized projects
  runtime/compilers/rillv1/init.go
Labels: blocker

#5004 Runtime: fix granularity in `data_trunc` calls for clikchouse
  runtime/drivers/olap.go
Labels: blocker

#5005 Runtime : Cast result of `date_trunc` to timestamp
  runtime/drivers/olap.go
  runtime/queries/metricsview_timeseries.go
Labels: blocker

#4993 Comparison aggregation offset fix
  runtime/queries/metricsview_aggregation.go
  runtime/queries/metricsview_aggregation_test.go
Labels: blocker

#4995 Runtime : connector props from env
  proto/gen/rill/runtime/v1/api.pb.go
  proto/gen/rill/runtime/v1/api.pb.validate.go
  proto/gen/rill/runtime/v1/resources.pb.go
  proto/gen/rill/runtime/v1/resources.pb.validate.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/rill/runtime/v1/api.proto
  proto/rill/runtime/v1/resources.proto
  runtime/compilers/rillv1/parse_connector.go
  runtime/connections.go
  runtime/runtime.go
  web-common/src/proto/gen/rill/runtime/v1/api_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/resources_pb.ts
  web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
  web-common/src/runtime-client/gen/index.schemas.ts
Labels: blocker

#4934 Connectors: Dedicated forms for OLAP engines
  runtime/drivers/clickhouse/clickhouse.go
  runtime/drivers/druid/druid.go
  runtime/drivers/duckdb/duckdb.go
  runtime/drivers/pinot/pinot.go
  web-common/src/components/icons/connectors/ApacheDruid.svelte
  web-common/src/features/connectors/code-utils.spec.ts
  web-common/src/features/connectors/code-utils.ts
  web-common/src/features/editor/config.ts
  web-common/src/features/entity-management/AddAssetButton.svelte
  web-common/src/features/entity-management/ReconcilingSpinner.svelte
  web-common/src/features/entity-management/WatchResourcesClient.ts
  web-common/src/features/entity-management/entity-mappers.ts
  web-common/src/features/entity-management/file-artifacts.ts
  web-common/src/features/entity-management/resource-icon-mapping.ts
  web-common/src/features/entity-management/resource-selectors.ts
  web-common/src/features/entity-management/types.ts
  web-common/src/features/file-explorer/new-files.ts
  web-common/src/features/sources/modal/AddSourceModal.svelte
  web-common/src/features/sources/modal/OLAPDriverInstructions.svelte
  web-common/src/features/sources/modal/RemoteSourceForm.svelte
  web-common/src/features/sources/modal/submitRemoteSourceForm.ts
  web-common/src/features/sources/modal/yupSchemas.ts
  web-common/src/features/sources/sourceUtils.ts
  web-common/src/proto/gen/rill/runtime/v1/resources_pb.ts
  web-local/src/routes/(application)/files/[...file]/+page.svelte
Labels: blocker

#4990 Connectors: Break DSN into constituent parts
  runtime/drivers/clickhouse/clickhouse.go
  runtime/drivers/druid/druid.go
  runtime/drivers/pinot/pinot.go
  web-common/src/features/connectors/code-utils.ts
  web-common/src/features/sources/modal/yupSchemas.ts
Labels: blocker

#5010 Measure filter aggregation comparison optimization
  runtime/queries/metricsview_aggregation.go
  runtime/queries/metricsview_aggregation_test.go
Labels: blocker

#5017 fix(alert): Some spacing nits for alerts
  web-admin/src/features/alerts/metadata/AlertFilterCriteria.svelte
  web-common/src/features/alerts/criteria-tab/CriteriaForm.svelte
Labels: blocker

#5015 Connectors: Handle arbitrary names
  web-common/src/features/connectors/ConnectorExplorer.svelte
  web-common/src/features/connectors/olap/DatabaseSchemaEntry.svelte
  web-common/src/features/connectors/olap/TableEntry.svelte
  web-common/src/features/connectors/olap/TableMenuItems.svelte
  web-common/src/features/connectors/olap/TableWorkspaceHeader.svelte
  web-common/src/features/connectors/olap/olap-config.ts
  web-local/src/routes/(application)/connector/clickhouse/[name]/[database]/[table]/+page.svelte
  web-local/src/routes/(application)/connector/druid/[name]/[schema]/[table]/+page.svelte
  web-local/src/routes/(application)/connector/duckdb/[name]/[database]/[schema]/[table]/+page.svelte
  web-local/src/routes/(application)/connector/pinot/[name]/[table]/+page.svelte
Labels: blocker

#5014 Connectors: query invalidations
  web-common/src/features/connectors/olap/DatabaseExplorer.svelte
  web-common/src/features/connectors/utils.ts
  web-common/src/features/entity-management/WatchResourcesClient.ts
Labels: blocker

#5027 Connectors: Handle arbitrary names in check for modeling support
  web-common/src/features/connectors/olap/TableMenuItems.svelte
  web-common/src/features/connectors/olap/selectors.ts
  web-common/src/features/entity-management/AddAssetButton.svelte
  web-common/src/features/metrics-views/workspace/editor/Placeholder.svelte
Labels: Type:Bug

#5080 Cloud UI: Fix 401 error on the Project page due to stale JWT
  web-admin/src/features/dashboards/listing/selectors.ts
  web-admin/src/features/errors/error-utils.ts
  web-admin/src/features/projects/selectors.ts
  web-admin/src/features/projects/status/ProjectDeploymentStatusChip.svelte
  web-admin/src/routes/[organization]/[project]/+layout.svelte
  web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte
  web-common/src/runtime-client/RuntimeProvider.svelte
  web-common/src/runtime-client/runtime-store.ts
Labels: patch

#5030 feat(reports): Add Scheduled Reports support to Pivot and TDD
  web-admin/src/features/dashboards/listing/selectors.ts
  web-admin/src/features/dashboards/query-mappers/getDashboardFromAggregationRequest.ts
  web-admin/src/features/dashboards/query-mappers/mapQueryToDashboard.ts
  web-admin/src/features/dashboards/query-mappers/types.ts
  web-admin/src/features/projects/download-report.ts
  web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte
  web-admin/src/features/scheduled-reports/selectors.ts
  web-admin/src/routes/[organization]/[project]/-/alerts/[alert]/open/+page.svelte
  web-admin/src/routes/[organization]/[project]/-/reports/[report]/open/+page.svelte
  web-common/src/features/dashboards/dashboard-utils.ts
  web-common/src/features/dashboards/dimension-table/ExportDimensionTableDataButton.svelte
  web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts
  web-common/src/features/dashboards/pivot/PivotExportButton.svelte
  web-common/src/features/dashboards/pivot/PivotToolbar.svelte
  web-common/src/features/dashboards/pivot/pivot-export.ts
  web-common/src/features/dashboards/time-dimension-details/TDDExportButton.svelte
  web-common/src/features/dashboards/time-dimension-details/getTDDExportArgs.ts
  web-common/src/features/scheduled-reports/CreateScheduledReportDialog.svelte
  web-common/src/features/scheduled-reports/EditScheduledReportDialog.svelte
  web-common/src/features/scheduled-reports/utils.ts
Labels: blocker

#5135 fix(pivot): measure filter breaking sub table in pivot
  web-common/src/features/dashboards/pivot/pivot-merge-filters.ts
Labels: blocker

#5149 refactor: better logging for slots scaling
  admin/worker/run_autoscaler.go
Labels: nit, Team:Infra, Area:Telemetry

#5129 feat: alerts measure filters
  web-admin/src/features/alerts/metadata/AlertFilters.svelte
  web-admin/src/features/dashboards/query-mappers/getDashboardFromAggregationRequest.ts
  web-common/src/features/alerts/AlertPreviewTable.svelte
  web-common/src/features/alerts/CreateAlertForm.svelte
  web-common/src/features/alerts/criteria-tab/CriteriaForm.svelte
  web-common/src/features/alerts/data-tab/AlertDialogDataTab.svelte
  web-common/src/features/alerts/extract-alert-form-values.ts
  web-common/src/features/alerts/form-utils.ts
  web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts
Labels: blocker

#5147 Fix missing scrollbar
  web-common/src/components/dialog/Dialog.svelte
Labels: Type:Bug

#5156 Histogram infinity
  runtime/queries/column_desc_stats.go
  runtime/queries/column_numeric_histogram.go
  runtime/server/queries_columns_test.go
Labels: Type:Bug, blocker
