Repository rilldata/rill, pull requests merged in 2024-03, with the labels that each got.

#4217 Alerts UI: handle incomplete Criteria
  web-common/src/components/notifications/PersistedLinkNotification.svelte
  web-common/src/features/alerts/PreviewEmpty.svelte
  web-common/src/features/alerts/criteria-tab/AlertDialogCriteriaTab.svelte
  web-common/src/features/alerts/criteria-tab/AlertPreview.svelte
  web-common/src/features/alerts/criteria-tab/CriteriaForm.svelte
  web-common/src/features/alerts/data-tab/AlertDialogDataTab.svelte
  web-common/src/features/alerts/data-tab/DataPreview.svelte
  web-common/src/features/dashboards/stores/filter-utils.spec.ts
  web-common/src/features/dashboards/stores/filter-utils.ts
Labels: Area:Alerts

#4194 Rill Developer: Add Charts and Custom Dashboards to navigation sidebar
  web-common/src/features/charts/ChartAssets.svelte
  web-common/src/features/charts/ChartMenuItems.svelte
  web-common/src/features/charts/createChart.ts
  web-common/src/features/charts/selectors.ts
  web-common/src/features/custom-dashboards/CustomDashboardAssets.svelte
  web-common/src/features/custom-dashboards/CustomDashboardMenuItems.svelte
  web-common/src/features/custom-dashboards/createCustomDashboard.ts
  web-common/src/features/custom-dashboards/selectors.ts
  web-common/src/features/entity-management/entity-mappers.ts
  web-common/src/features/entity-management/file-selectors.ts
  web-common/src/features/entity-management/resource-selectors.ts
  web-common/src/features/entity-management/types.ts
  web-common/src/features/feature-flags.ts
  web-common/src/layout/RillDeveloperLayout.svelte
  web-common/src/layout/app-store.ts
  web-common/src/layout/navigation/Navigation.svelte
  web-common/src/metrics/service/MetricsTypes.ts
  web-local/src/routes/(application)/chart/+page.ts
  web-local/src/routes/(application)/chart/[name]/+page.svelte
  web-local/src/routes/(application)/custom-dashboard/+page.ts
  web-local/src/routes/(application)/custom-dashboard/[name]/+page.svelte
Labels: Custom Dashboards

#4230 Relax name constraints
  web-common/src/features/entity-management/RenameAssetModal.svelte
  web-common/src/features/entity-management/actions.ts
  web-common/src/features/entity-management/entity-mappers.ts
  web-common/src/features/entity-management/name-utils.ts
  web-common/src/features/entity-management/resources-store.ts
  web-common/src/features/entity-management/watch-files-client.ts
  web-common/src/features/generic-yaml-editor/actions/index.ts
  web-common/src/features/metrics-views/workspace/MetricsWorkspaceHeader.svelte
  web-common/src/features/models/selectors.ts
  web-common/src/features/models/utils/model-is-empty/index.ts
  web-common/src/features/models/workspace/ModelWorkspaceHeader.svelte
  web-common/src/features/sources/modal/yupSchemas.ts
  web-common/src/features/sources/workspace/SourceWorkspaceHeader.svelte
  web-common/src/runtime-client/fetchWrapper.ts
  web-common/src/runtime-client/invalidation.ts
Labels: Team:Applications, customer

#4229 Updates to ChartInteractions, time series chart layout and MeasureBigNumber
  web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
  web-common/src/features/dashboards/big-number/MeasuresContainer.svelte
  web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
  web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte
  web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte
  web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte
  web-common/src/features/dashboards/time-series/ChartInteractions.svelte
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
  web-common/src/features/dashboards/time-series/TimeSeriesChartContainer.svelte
  web-common/src/features/dashboards/workspace/Dashboard.svelte
Labels: blocker

#4286 Fix: Placement of environment variable declaration
  package.json
  web-local/package.json
Labels: Type:Bug, blocker

#4278 fix: leaderboard column alignment
  web-common/src/components/data-types/Interval.svelte
  web-common/src/components/data-types/MeasureChange.svelte
  web-common/src/components/data-types/PercentageChange.svelte
  web-common/src/components/virtualized-table/core/Cell.svelte
Labels: blocker

#4288 Fix measure filter stopped applying
  web-common/src/features/dashboards/filters/measure-filters/MeasureFilterBody.svelte
  web-common/src/features/dashboards/filters/measure-filters/measure-filter-utils.ts
Labels: blocker

#4284 Runtime: Review/refactor custom APIs
  runtime/compilers/rillv1/parse_api.go
  runtime/compilers/rillv1/parser_test.go
  runtime/compilers/rillv1/template.go
  runtime/drivers/olap.go
  runtime/reconcilers/migration.go
  runtime/reconcilers/model.go
  runtime/reconcilers/project_parser.go
  runtime/reconcilers/util.go
  runtime/resolver.go
  runtime/resolvers/api.go
  runtime/resolvers/metrics_sql.go
  runtime/resolvers/metrics_sql_test.go
  runtime/resolvers/metricsview_sql.go
  runtime/resolvers/sql.go
  runtime/resolvers/sql_test.go
  runtime/resolvers/util.go
  runtime/resources.go
  runtime/server/api.go
  runtime/server/charts.go
  runtime/server/server.go
  runtime/testruntime/testdata/ad_bids/apis/mv_sql_policy_api.yaml
  runtime/testruntime/testdata/ad_bids/apis/simple_mv_sql_api.yaml
  runtime/testruntime/testdata/ad_bids/apis/simple_sql_api.yaml
  runtime/testruntime/testdata/ad_bids/apis/templated_mv_sql_api.yaml
  runtime/testruntime/testdata/ad_bids/apis/templated_sql_api.yaml
  runtime/testruntime/testdata/ad_bids/apis/templated_sql_api_2.yaml
Labels: blocker

#4236 Offer CLI flags for serving Rill Developer over HTTPS
  admin/server/server.go
  admin/worker/worker.go
  cli/cmd/start/start.go
  cli/pkg/local/app.go
  runtime/pkg/debugserver/debugserver.go
  runtime/pkg/graceful/http.go
  runtime/server/server.go
Labels: Type:Feature, blocker, Area:CLI

#4282 Fix: Measure overflow reversion
  web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
Labels: Type:Bug

#4289 Fix: Disable chart keydown ops on input fields
  web-common/src/features/dashboards/time-series/ChartInteractions.svelte
Labels: blocker

#4283 Refactor workspace layout
  web-common/src/features/generic-yaml-editor/YamlWorkspace.svelte
  web-common/src/features/generic-yaml-editor/YamlWorkspaceHeader.svelte
  web-common/src/features/metrics-views/workspace/MetricsWorkspace.svelte
  web-common/src/features/models/workspace/ModelBody.svelte
  web-common/src/features/models/workspace/ModelWorkspace.svelte
  web-common/src/features/models/workspace/ModelWorkspaceHeader.svelte
  web-common/src/features/onboarding/OnboardingWorkspace.svelte
  web-common/src/features/sources/workspace/SourceWorkspace.svelte
  web-common/src/features/sources/workspace/SourceWorkspaceBody.svelte
  web-common/src/features/tables/TableWorkspaceHeader.svelte
  web-common/src/layout/Resizer.svelte
  web-common/src/layout/workspace/HorizontalSplitter.svelte
  web-common/src/layout/workspace/Inspector.svelte
  web-common/src/layout/workspace/WorkspaceContainer.svelte
  web-common/src/layout/workspace/WorkspaceEditorContainer.svelte
  web-common/src/layout/workspace/WorkspaceHeader.svelte
  web-common/src/layout/workspace/WorkspaceTableContainer.svelte
  web-common/src/layout/workspace/workspace-stores.ts
  web-local/src/routes/(application)/chart/[name]/+page.svelte
  web-local/src/routes/(application)/dashboard/[name]/+page.svelte
  web-local/src/routes/(application)/table/[name]/+page.svelte
Labels: Area:Performance, Type:Improvement

#4285 Update menus in Dashboard body
  web-common/src/components/button/Button.svelte
  web-common/src/components/menu/shadcn/SearchableMenu.svelte
  web-common/src/components/menu/shadcn/SearchableMenuContent.svelte
  web-common/src/components/menu/shadcn/SelectMenu.svelte
  web-common/src/components/menu/shadcn/SelectMenuContent.svelte
  web-common/src/components/searchable-filter-menu/SearchableFilterButton.svelte
  web-common/src/components/tooltip/TooltipTitle.svelte
  web-common/src/features/dashboards/big-number/MeasuresContainer.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardContextColumnMenu.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
  web-local/tests/dashboards/leaderboard-context-column.spec.ts
  web-local/tests/dashboards/number-formatting.spec.ts
Labels: blocker, Type:Improvement, Area:Dashboard

#4296 Telemetry for success/failure of AI-based metrics view generation
  runtime/pkg/activity/event.go
  runtime/pkg/middleware/activity.go
  runtime/server/generate_metrics_view.go
Labels: blocker

#4281 Rework duplicate source modal
  web-common/src/features/onboarding/OnboardingWorkspace.svelte
  web-common/src/features/sources/modal/AddSourceModal.svelte
  web-common/src/features/sources/modal/DuplicateSource.svelte
  web-common/src/features/sources/modal/add-source-visibility.ts
  web-common/src/features/sources/navigation/SourceAssets.svelte
  web-common/src/features/welcome/TitleContent.svelte
  web-common/src/layout/RillDeveloperLayout.svelte
Labels: blocker

#4303 Remove z-index class on Workspace Header
  web-common/src/layout/workspace/WorkspaceContainer.svelte
Labels: Type:Bug

#4305 Disable chart pan on cmd/alt + arrow key
  web-common/src/features/dashboards/time-series/ChartInteractions.svelte
Labels: blocker

#4304 Make dimension/measure in dashboard config insensitive
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
Labels: blocker

#4306 Fix format of ducksql sample select query
  runtime/pkg/duckdbsql/ast_rewrite.go
  runtime/pkg/duckdbsql/ast_test.go
  runtime/pkg/duckdbsql/ast_traversal.go
  runtime/pkg/duckdbsql/ast_values.go
  runtime/pkg/duckdbsql/corrections.go
Labels: blocker

#4207 Refactor: Pivot drag and drop
  package-lock.json
  web-common/package.json
  web-common/src/features/dashboards/pivot/AddField.svelte
  web-common/src/features/dashboards/pivot/DragList.svelte
  web-common/src/features/dashboards/pivot/PivotChip.svelte
  web-common/src/features/dashboards/pivot/PivotDrag.svelte
  web-common/src/features/dashboards/pivot/PivotDragItem.svelte
  web-common/src/features/dashboards/pivot/PivotHeader.svelte
  web-common/src/features/dashboards/pivot/PivotPortalItem.svelte
  web-common/src/features/dashboards/pivot/swapListener.ts
Labels: Type:Bug, blocker

#4326 Fix: enable vertical scrolling of inspector
  web-common/src/layout/workspace/Inspector.svelte
Labels: Type:Bug

#4330 Runtime: clickhouse fix for information_schema all method
  runtime/drivers/clickhouse/information_schema.go
  runtime/drivers/clickhouse/information_schema_test.go
Labels: blocker

#4324 Remove Alerts feature flag
  web-admin/src/features/projects/ProjectTabs.svelte
  web-admin/src/routes/+layout.svelte
  web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
  web-common/src/features/feature-flags.ts
Labels: blocker

#4337 Fix race condition in Tables list
  web-common/src/features/tables/TableAssets.svelte
  web-common/src/features/tables/selectors.ts
Labels: Type:Bug

#4339 Fix: Pivot row totals data inconsistency
  web-common/src/features/dashboards/pivot/pivot-data-store.ts
  web-common/src/features/dashboards/pivot/pivot-queries.ts
  web-common/src/features/dashboards/pivot/pivot-table-transformations.ts
  web-common/src/features/dashboards/pivot/pivot-utils.ts
Labels: Type:Bug, blocker

#4340 Bugfix follow-up to #4337
  web-common/src/features/tables/TableAssets.svelte
Labels: blocker

#3818 Add kubernetes provisioner and provisioner set support
  admin/admin.go
  admin/database/database.go
  admin/database/postgres/migrations/0022.sql
  admin/database/postgres/postgres.go
  admin/deployments.go
  admin/projects.go
  admin/provisioner/README.md
  admin/provisioner/kubernetes.go
  admin/provisioner/provisioner.go
  admin/provisioner/static.go
  admin/provisioner/static_test.go
  admin/server/admin_rbac_test.go
  admin/server/projects.go
  admin/worker/check_provisioner_capacity.go
  admin/worker/check_slots.go
  admin/worker/reset_all_deployments.go
  admin/worker/upgrade_latest_version_projects.go
  admin/worker/worker.go
  cli/cmd/admin/start.go
  cli/cmd/deploy/deploy.go
  cli/cmd/project/edit.go
  cli/cmd/sudo/lookup.go
  cli/cmd/sudo/project/get.go
  cli/pkg/mock/server.go
  go.mod
  go.sum
  proto/gen/rill/admin/v1/admin.swagger.yaml
  proto/gen/rill/admin/v1/api.pb.go
  proto/gen/rill/admin/v1/api.pb.validate.go
  proto/rill/admin/v1/api.proto
  web-admin/src/client/gen/index.schemas.ts
  web-common/src/proto/gen/rill/admin/v1/api_pb.ts
Labels: Team:Infra

#4367 Embed: Add ability to navigate a project's dashboards
  admin/server/deployment.go
  web-admin/src/components/table/Table.svelte
  web-admin/src/features/dashboards/listing/DashboardList.svelte
  web-admin/src/features/dashboards/listing/DashboardsTable.svelte
  web-admin/src/features/dashboards/listing/DashboardsTableCompositeCell.svelte
  web-admin/src/features/dashboards/listing/LastRefreshedDate.svelte
  web-admin/src/features/embeds/DashboardEmbed.svelte
  web-admin/src/features/embeds/TopNavigationBarEmbed.svelte
  web-admin/src/features/navigation/TopNavigationBar.svelte
  web-admin/src/routes/-/embed/+page.svelte
  web-admin/src/routes/[organization]/[project]/+page.svelte
Labels: blocker, patch

#4375 Fix: Dimension Table critical short term fixes
  web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
  web-common/src/features/dashboards/dimension-table/DimensionTable.svelte
  web-common/src/features/dashboards/dimension-table/dimension-table-utils.ts
Labels: Type:Bug, blocker, patch

#4342 Feat: Infinite row scrolling for Pivot
  web-common/src/features/dashboards/pivot/PivotTable.svelte
  web-common/src/features/dashboards/pivot/pivot-data-store.ts
  web-common/src/features/dashboards/pivot/pivot-infinite-scroll.ts
  web-common/src/features/dashboards/pivot/pivot-queries.ts
  web-common/src/features/dashboards/pivot/pivot-table-transformations.ts
  web-common/src/features/dashboards/pivot/types.ts
  web-common/src/features/dashboards/proto-state/fromProto.ts
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
  web-common/src/features/dashboards/stores/dashboard-stores.ts
Labels: patch

#4377 Runtime: Clickhouse information schema calls should use currentdatabase
  runtime/drivers/clickhouse/information_schema.go
Labels: patch

#4383 Fix: Key ShadCN MenuItem on disabled prop
  web-common/src/layout/navigation/NavigationMenuItem.svelte
Labels: patch

#4384 Fix: Explicitly pass queryClient to Feature Flags store
  web-admin/src/routes/+layout.svelte
  web-common/src/features/feature-flags.ts
  web-common/src/lib/svelte-query/globalQueryClient.ts
  web-local/src/routes/(application)/+layout.svelte
Labels: Type:Bug, patch

#4389 Nav: styling fixes
  web-common/src/features/charts/ChartAssets.svelte
  web-common/src/features/tables/TableAssets.svelte
  web-common/src/layout/navigation/NavigationEntry.svelte
Labels: Type:Bug

#4392 Rill Developer: Fix dashboard's "Edit model" button
  web-admin/src/features/dashboards/listing/selectors.ts
  web-admin/src/features/embeds/TopNavigationBarEmbed.svelte
  web-admin/src/features/navigation/Breadcrumbs.svelte
  web-common/src/features/dashboards/DashboardAssets.svelte
  web-common/src/features/dashboards/selectors.ts
Labels: Type:Bug

#4406 fix: disable bookmark for anonymous users
  web-admin/src/features/bookmarks/selectors.ts
  web-admin/src/features/dashboards/DashboardBookmarksStateProvider.svelte
  web-admin/src/features/navigation/TopNavigationBar.svelte
  web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte
Labels: patch

#4390 Refactor: Simplify sidebar layout and related positioning
  web-common/src/app.css
  web-common/src/features/dashboards/workspace/Dashboard.svelte
  web-common/src/features/onboarding/OnboardingWorkspace.svelte
  web-common/src/layout/BasicLayout.svelte
  web-common/src/layout/config.ts
  web-common/src/layout/navigation/Navigation.svelte
  web-common/src/layout/navigation/SurfaceControlButton.svelte
  web-common/src/layout/workspace/WorkspaceContainer.svelte
  web-common/src/layout/workspace/WorkspaceHeader.svelte
  web-local/src/routes/(application)/+error.svelte
  web-local/src/routes/(application)/dashboard/[name]/+page.svelte
  web-local/tests/dashboards/leaderboard-context-column.spec.ts
  web-local/tests/dashboards/metrics-editor.spec.ts
Labels: Type:Improvement, Area:Dashboard

#4408 Updagraded gosnowflake as v1.8.0 has an issue with arrow batches
  go.mod
  go.sum
  runtime/drivers/snowflake/sql_store.go
Labels: patch

#4397 Druid Explore Exactify mode
  runtime/queries/metricsview_comparison_toplist.go
Labels: patch

#4391 Feat: Add auto-save toggle to model workspace
  web-common/src/components/forms/Switch.svelte
  web-common/src/features/models/workspace/Editor.svelte
  web-common/src/features/models/workspace/ModelBody.svelte
  web-common/src/features/sources/editor/UnsavedSourceDialog.svelte
  web-common/src/layout/workspace/workspace-stores.ts
  web-local/src/routes/(application)/model/[name]/+page.svelte
Labels: Area:Performance

#4423 Fix: Sidebar scroll and title cutoff
  web-common/src/features/project/ProjectTitle.svelte
  web-common/src/layout/navigation/Navigation.svelte
Labels: Type:Bug, blocker

#4453 Runtime: Ignore unsupported OLAP engine types
  proto/gen/rill/runtime/v1/connectors.pb.go
  proto/gen/rill/runtime/v1/connectors.pb.validate.go
  proto/gen/rill/runtime/v1/queries.pb.go
  proto/gen/rill/runtime/v1/queries.pb.validate.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/rill/runtime/v1/connectors.proto
  proto/rill/runtime/v1/queries.proto
  runtime/drivers/clickhouse/information_schema.go
  runtime/drivers/clickhouse/olap.go
  runtime/drivers/olap.go
  runtime/queries/table_columns.go
  runtime/queries/table_head.go
  runtime/server/connectors.go
  runtime/server/queries_tables.go
  web-common/src/proto/gen/rill/runtime/v1/connectors_pb.ts
  web-common/src/proto/gen/rill/runtime/v1/queries_pb.ts
  web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
  web-common/src/runtime-client/gen/index.schemas.ts
Labels: blocker

#4455 Fix: Welcome page layout
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
  web-common/src/features/dashboards/time-series/TimeSeriesChartContainer.svelte
  web-common/src/features/dashboards/workspace/Dashboard.svelte
  web-common/src/features/generic-yaml-editor/YamlWorkspaceBody.svelte
  web-common/src/features/welcome/BackgroundImage.svelte
  web-common/src/features/welcome/ProjectCards.svelte
  web-common/src/features/welcome/UserTestCTA.svelte
  web-common/src/features/welcome/Welcome.svelte
  web-common/src/layout/BasicLayout.svelte
  web-common/src/layout/navigation/Navigation.svelte
  web-local/src/routes/(application)/welcome/+page.svelte
Labels: Type:Bug, blocker

#4457 Fix: Mock user JWT invalidation and queryClient access
  web-common/src/features/dashboards/granular-access-policies/resetSelectedMockUserAfterNavigate.ts
  web-common/src/features/dashboards/granular-access-policies/updateDevJWT.ts
  web-common/src/features/dashboards/selectors/index.ts
  web-common/src/runtime-client/http-client.ts
Labels: Type:Bug, blocker

#4463 Admin: Add DB migration and docs for create_alerts and manage_alerts permissions
  admin/database/postgres/migrations/0023.sql
  docs/docs/manage/roles-permissions.md
Labels: blocker

#4462 Show a warning indicator for Tables with unsupported data types
  web-common/src/features/tables/TableAssets.svelte
  web-common/src/features/tables/UnsupportedTypesIndicator.svelte
  web-common/src/features/tables/selectors.ts
  web-common/src/layout/navigation/NavigationEntry.svelte
Labels: blocker

#4465 Fix: Perpetual loading state and infinite loop query
  web-common/src/features/dashboards/selectors/index.ts
  web-common/src/features/dashboards/stores/DashboardStateProvider.svelte
  web-common/src/features/dashboards/stores/syncDashboardState.ts
  web-common/src/runtime-client/invalidation.ts
Labels: Type:Bug, blocker, Area:Dashboard

#4474 Fix: cap max menu size
  web-common/src/components/menu/shadcn/SelectMenuContent.svelte
Labels: Type:Bug, blocker

#4475 Use specific `queryKey` for managing the project runtime
  web-admin/src/features/errors/error-utils.ts
  web-admin/src/features/projects/selectors.ts
  web-admin/src/features/view-as-user/clearViewedAsUser.ts
Labels: Type:Bug

#4478 Reduce number of values fetched in topN for leaderboards
  web-common/src/features/dashboards/dashboard-utils.ts
  web-common/src/features/dashboards/state-managers/selectors/dashboard-queries.ts
Labels: patch
