Repository rilldata/rill, pull requests merged in 2024-04, with the labels that each got.

#4464 Runtime: Apply access policies to alerts returned in ListResources
  runtime/server/controller.go
Labels: blocker

#4485 Fix: SvelteKit configuration and lack of ambient types
  tsconfig.json
  web-admin/src/components/table/Table.svelte
  web-admin/src/features/alerts/history/AlertHistoryStatusChip.svelte
  web-admin/src/features/alerts/history/AlertHistoryTable.svelte
  web-admin/src/features/alerts/history/AlertHistoryTableHeader.svelte
  web-admin/src/features/alerts/listing/AlertsTable.svelte
  web-admin/src/features/dashboards/listing/DashboardsTable.svelte
  web-admin/src/features/dashboards/listing/DashboardsTableHeader.svelte
  web-admin/src/features/organizations/OrganizationAccessControls.svelte
  web-admin/src/features/projects/ProjectAccessControls.svelte
  web-admin/src/features/scheduled-reports/history/ReportHistoryTable.svelte
  web-admin/src/features/scheduled-reports/history/ReportHistoryTableHeader.svelte
  web-admin/src/features/scheduled-reports/listing/ReportsTable.svelte
  web-admin/src/features/scheduled-reports/listing/ReportsTableHeader.svelte
  web-admin/src/features/view-as-user/ViewAsUserPopover.svelte
  web-admin/tsconfig.json
  web-auth/tsconfig.json
  web-common/src/features/dashboards/pivot/pivot-data-store.ts
  web-common/src/features/dashboards/proto-state/filter-converter.ts
  web-local/tsconfig.json
Labels: Type:Bug

#4482 Fix: Pivot expansion on infinite scroll
  web-common/src/features/dashboards/pivot/pivot-data-store.ts
  web-common/src/features/dashboards/pivot/pivot-expansion.ts
  web-common/src/features/dashboards/pivot/pivot-table-transformations.ts
Labels: blocker

#4489 Fix type imports in Cloud UI
  web-admin/src/features/errors/error-store.ts
  web-admin/src/features/errors/error-utils.ts
  web-admin/src/features/view-as-user/setViewedAsUser.ts
Labels: Type:Bug

#4471 Refac: Replace TDD multiple timeseries API with Aggregation API
  web-common/src/features/dashboards/time-controls/time-control-store.ts
  web-common/src/features/dashboards/time-dimension-details/TDDTable.svelte
  web-common/src/features/dashboards/time-series/multiple-dimension-queries.ts
  web-common/src/features/dashboards/time-series/timeseries-data-store.ts
  web-common/src/features/dashboards/time-series/utils.spec.ts
  web-common/src/features/dashboards/time-series/utils.ts
Labels: Area:Performance, blocker

#4499 Register the telemetry service for cloud
  admin/server/server.go
Labels: blocker

#4507 Cloud UI: Fix bug in "View as" popover
  package-lock.json
  web-admin/package.json
  web-admin/src/features/view-as-user/ViewAsUserChip.svelte
Labels: Type:Bug

#4494 Telemetry and source rename fixes
  web-common/src/features/dashboards/tab-bar/TabBar.svelte
  web-common/src/features/entity-management/file-artifacts.ts
  web-common/src/features/entity-management/resource-invalidations.ts
  web-common/src/features/tables/TableAssets.svelte
  web-common/src/features/tables/selectors.ts
Labels: blocker

#4515 UI to support multiple schemas in an OLAP engine
  runtime/drivers/druid/olap.go
  web-common/src/components/preview-table/ConnectedPreviewTable.svelte
  web-common/src/features/metrics-views/ai-generation/generateMetricsView.ts
  web-common/src/features/models/navigation/ModelMenuItems.svelte
  web-common/src/features/models/workspace/CreateDashboardButton.svelte
  web-common/src/features/sources/modal/SourceImportedModal.svelte
  web-common/src/features/sources/navigation/SourceMenuItems.svelte
  web-common/src/features/tables/TableAssets.svelte
  web-common/src/features/tables/TableMenuItems.svelte
  web-common/src/features/tables/TablePreviewWorkspace.svelte
  web-common/src/features/tables/TableWorkspaceHeader.svelte
  web-common/src/features/tables/UnsupportedTypesIndicator.svelte
  web-common/src/features/tables/config.ts
  web-common/src/features/tables/olap-config.ts
  web-common/src/features/tables/selectors.ts
  web-common/src/layout/RillDeveloperLayout.svelte
  web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
  web-local/src/routes/(application)/connector/clickhouse/+page.ts
  web-local/src/routes/(application)/connector/clickhouse/[database]/[table]/+page.svelte
  web-local/src/routes/(application)/connector/druid/+page.ts
  web-local/src/routes/(application)/connector/druid/[schema]/[table]/+page.svelte
  web-local/src/routes/(application)/connector/duckdb/+page.ts
  web-local/src/routes/(application)/connector/duckdb/[database]/[schema]/[table]/+page.svelte
  web-local/src/routes/(application)/table/[name]/+page.svelte
Labels: customer

#4509 Alerts slack integration UI
  admin/server/alerts.go
  web-admin/src/features/alerts/history/AlertHistoryTableCompositeCell.svelte
  web-admin/src/features/alerts/metadata/AlertMetadata.svelte
  web-admin/src/features/scheduled-reports/metadata/MetadataList.svelte
  web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte
  web-admin/src/features/scheduled-reports/metadata/notifiers-utils.ts
  web-common/src/components/forms/FormSection.svelte
  web-common/src/components/forms/InputArray.svelte
  web-common/src/features/alerts/BaseAlertForm.svelte
  web-common/src/features/alerts/CreateAlertDialog.svelte
  web-common/src/features/alerts/EditAlertDialog.svelte
  web-common/src/features/alerts/delivery-tab/AlertDialogDeliveryTab.svelte
  web-common/src/features/alerts/delivery-tab/notifiers-utils.ts
  web-common/src/features/alerts/extract-alert-form-values.ts
  web-common/src/features/alerts/form-utils.ts
  web-common/src/features/scheduled-reports/BaseScheduledReportForm.svelte
  web-common/src/features/scheduled-reports/RecipientsInputArray.svelte
Labels: Area:Alerts

#4535 Fixed Slack form visibility and edit alert form
  web-common/src/features/alerts/CreateAlertDialog.svelte
  web-common/src/features/alerts/delivery-tab/AlertDialogDeliveryTab.svelte
  web-common/src/features/alerts/delivery-tab/notifiers-utils.ts
  web-common/src/features/alerts/extract-alert-form-values.ts
Labels: blocker

#4532 Fix bug when clearing the "View as" pill
  web-admin/src/routes/[organization]/[project]/[dashboard]/+page.svelte
Labels: Type:Bug

#4549 Adjusting the spacing in slack notification section to match other sections
  web-common/src/components/forms/FormSection.svelte
  web-common/src/features/alerts/delivery-tab/AlertDialogDeliveryTab.svelte
Labels: blocker

#4559 Runtime: Add missing dry run support in `Exec` method of clickhouse driver
  runtime/drivers/clickhouse/information_schema_test.go
  runtime/drivers/clickhouse/olap.go
Labels: blocker

#4578 Fix bug that crashes the Scheduled Report detail page
  web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte
Labels: Type:Bug, blocker

#4580 old_implicit_casting to cast numbers to strings while table union by name
  runtime/drivers/duckdb/duckdb.go
Labels: blocker

#4584 github.com/aws/aws-sdk-go-v2/service/athena v1.40.4
  go.mod
  go.sum
Labels: blocker

#4588 Returned TIMESTAMP WITH TIME ZONE as a timestamp type
  web-common/src/lib/duckdb-data-types.ts
Labels: blocker

#4590 Runtime : Detach duckdb files with `tx` lock
  runtime/drivers/duckdb/olap.go
  runtime/drivers/duckdb/transporter_duckDB_to_duckDB.go
  runtime/reconcilers/model.go
  runtime/reconcilers/source.go
  runtime/reconcilers/util.go
Labels: blocker

#4597 Fix: Workspace reconnection
  web-common/src/features/generic-yaml-editor/YamlWorkspaceBody.svelte
  web-common/src/features/metrics-views/workspace/editor/MetricsEditor.svelte
  web-common/src/runtime-client/watch-request-client.ts
  web-local/src/routes/(application)/+layout.svelte
  web-local/src/routes/(application)/dashboard/[name]/edit/+page@dashboard.svelte
Labels: blocker

#4604 Admin: Fix version missing error for "rill deploy" from old versions
  admin/deployments.go
  admin/server/projects.go
Labels: blocker

#4610 Fix: Reset pivot drag state
  web-common/src/features/dashboards/pivot/DragList.svelte
  web-common/src/features/dashboards/pivot/PivotPortalItem.svelte
  web-common/src/features/dashboards/pivot/swapListener.ts
Labels: Type:Bug, Area:Pivot

#4612 Runtime: Fix virtual files being deleted on git pull
  runtime/drivers/admin/admin.go
Labels: blocker

#4613 Update AI feature flag scope
  web-common/src/features/feature-flags.ts
Labels: blocker

#4592 Fix: Scrub range not resetting on back navigation
  web-common/src/features/dashboards/proto-state/fromProto.ts
Labels: Type:Bug

#4618 Fix: Custom Dashboard component assignment name
  web-local/src/routes/(application)/custom-dashboard/[name]/+page.svelte
Labels: Type:Bug

#4531 Cloud UI: Surface Custom Dashboards in navigation
  scripts/tsc-with-whitelist.sh
  web-admin/src/features/dashboards/listing/DashboardsTable.svelte
  web-admin/src/features/dashboards/listing/DashboardsTableCompositeCell.svelte
  web-admin/src/features/dashboards/listing/NoDashboardsCTA.svelte
  web-admin/src/features/dashboards/listing/selectors.ts
  web-admin/src/features/embeds/TopNavigationBarEmbed.svelte
  web-admin/src/features/errors/error-utils.ts
  web-admin/src/features/navigation/TopNavigationBar.svelte
  web-admin/src/features/navigation/nav-utils.ts
  web-admin/src/routes/+layout.svelte
  web-admin/src/routes/[organization]/[project]/-/dashboards/+page.ts
  web-admin/src/routes/[organization]/[project]/-/dashboards/[dashboard]/+page.svelte
  web-common/src/components/dropdown-menu/__stories__/DropdownMenu.stories.svelte
  web-common/src/components/icons/CustomDashboardIcon.svelte
  web-common/src/components/icons/MetricsExplorerIcon.svelte
  web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte
  web-common/src/features/custom-dashboards/Chart.svelte
  web-common/src/features/dashboards/selectors.ts
  web-common/src/features/entity-management/resource-icon-mapping.ts
Labels: Custom Dashboards

#4622 Fix/Feat: Resizable Pivot measure columns
  web-common/src/features/dashboards/pivot/PivotTable.svelte
  web-common/src/layout/Resizer.svelte
Labels: Type:Bug

#4624 Fix: Post reorg tweaks
  web-local/src/routes/(application)/+layout.svelte
  web-local/src/routes/+layout.svelte
  web-local/src/routes/welcome/+page.svelte
  web-local/src/routes/welcome/+page.ts
Labels: Type:Bug

#4628 Fix: prevent the `ListProjectsForOrganization` request from firing before the `organization` is defined
  web-admin/src/features/navigation/TopNavigationBar.svelte
Labels: Type:Bug

#4641 Set app wrapper to absolute positioning
  web-local/src/routes/+layout.svelte
Labels: Type:Bug, blocker

#4648 Fix Amazon Redshift icon in Safari
  web-common/src/components/icons/connectors/AmazonRedshift.svelte
Labels: Type:Bug

#4653 Rows Accordion: use Resizer, remove drag action
  web-common/src/components/preview-table/PreviewTable.svelte
  web-common/src/components/virtualized-table/VirtualTable.svelte
  web-common/src/features/dashboards/rows-viewer/RowsViewer.svelte
  web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte
  web-common/src/layout/Resizer.svelte
  web-common/src/layout/drag.ts
Labels: Area:Dashboard

#4676 File Explorer: Fix new file names
  web-common/src/features/entity-management/file-selectors.spec.ts
  web-common/src/features/entity-management/file-selectors.ts
  web-common/src/features/entity-management/resource-selectors.ts
  web-common/src/features/file-explorer/FileExplorer.svelte
  web-common/src/features/file-explorer/new-files.ts
  web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
Labels: Type:Bug

#4385 Update bits-ui version
  package-lock.json
  web-common/package.json
Labels: dependencies

#4698 Fix loading state of Source/Model preview table
  web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
Labels: Type:Bug

#4719 Fix missing project title icon
  web-common/src/features/project/ProjectTitle.svelte
  web-common/src/features/project/selectors.ts
Labels: Type:Bug

#4721 Fix: Move /welcome route to application group
  web-local/src/routes/(application)/+layout.svelte
  web-local/src/routes/(application)/welcome/+page.svelte
  web-local/src/routes/(application)/welcome/+page.ts
Labels: Type:Bug, blocker

#4739 Fix: Test reliability
  web-local/tests/dashboards/dashboard-flow-test-setup.ts
  web-local/tests/dashboards/dashboards.spec.ts
  web-local/tests/dashboards/leaderboard-context-column.spec.ts
  web-local/tests/dashboards/metrics-editor.spec.ts
  web-local/tests/dashboards/number-formatting.spec.ts
  web-local/tests/utils/commonHelpers.ts
Labels: Type:Bug, blocker

#4749 File Explorer: Fix 404 error from renaming a file in the root directory
  web-common/src/features/entity-management/RenameAssetModal.svelte
Labels: Type:Bug, blocker

#4715 Cleanup old usage of ListFiles and using the folder name to identify entities
  web-common/src/features/alerts/selectors.ts
  web-common/src/features/apis/selectors.ts
  web-common/src/features/charts/ChartMenuItems.svelte
  web-common/src/features/charts/ChartsHeader.svelte
  web-common/src/features/charts/selectors.ts
  web-common/src/features/custom-dashboards/AddChartMenu.svelte
  web-common/src/features/custom-dashboards/CustomDashboardMenuItems.svelte
  web-common/src/features/custom-dashboards/selectors.ts
  web-common/src/features/dashboards/selectors.ts
  web-common/src/features/editor/FileWorkspaceHeader.svelte
  web-common/src/features/entity-management/file-artifacts.ts
  web-common/src/features/entity-management/file-selectors.ts
  web-common/src/features/entity-management/resource-selectors.ts
  web-common/src/features/entity-management/ui-actions.ts
  web-common/src/features/file-explorer/new-files.ts
  web-common/src/features/metrics-views/ai-generation/generateMetricsView.ts
  web-common/src/features/models/selectors.ts
  web-common/src/features/reports/selectors.ts
  web-common/src/features/sources/createModel.ts
  web-common/src/features/sources/modal/FileDrop.svelte
  web-common/src/features/sources/modal/LocalSourceUpload.svelte
  web-common/src/features/sources/modal/file-upload.ts
  web-common/src/features/sources/navigation/SourceMenuItems.svelte
  web-common/src/features/sources/selectors.ts
  web-common/src/features/tables/TableMenuItems.svelte
  web-common/src/features/themes/selectors.ts
  web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
  web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
Labels: blocker

#4762 Fix admin repo startup deadlock because of rill.yaml read
  runtime/drivers/admin/admin.go
Labels: blocker

#4774 Use `type:` instead of `kind:` for resource types
  admin/server/alerts.go
  admin/server/reports.go
  cli/cmd/project/describe.go
  cli/cmd/project/status.go
  runtime/compilers/rillv1/connectors_test.go
  runtime/compilers/rillv1/parse_node.go
  runtime/compilers/rillv1/parse_source.go
  runtime/compilers/rillv1/parser.go
  runtime/compilers/rillv1/parser_test.go
  runtime/controller.go
  runtime/controller_test.go
  runtime/reconcilers/alert_test.go
  runtime/server/generate_metrics_view.go
  runtime/testruntime/testdata/ad_bids/dashboards/ad_bids_metrics_view.yaml
  runtime/testruntime/testdata/ad_bids/sources/ad_bids_mini_source.yaml
  runtime/testruntime/testdata/ad_bids/sources/ad_bids_source.yaml
  runtime/testruntime/testdata/ad_bids_2rows/sources/ad_bids_source.yaml
Labels: blocker

#4775 Fix: Unfocus YAML Editor on file change
  web-common/src/components/editor/YAMLEditor.svelte
  web-common/src/components/editor/__stories__/YAMLEditor.stories.svelte
  web-common/src/features/charts/editor/ChartsEditor.svelte
  web-common/src/features/custom-dashboards/CustomDashboardEditor.svelte
  web-common/src/features/generic-yaml-editor/YamlWorkspaceBody.svelte
  web-common/src/features/metrics-views/workspace/editor/MetricsEditor.svelte
  web-common/src/features/sources/editor/SourceEditor.svelte
  web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
  web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
Labels: Type:Bug, blocker

#4772 Hide modeling for Pinot projects
  web-common/src/features/tables/olap-config.ts
Labels: blocker
