Repository rilldata/rill, pull requests merged in 2024-10, with the labels that each got.

#5820 Fix two casing bugs in breadcrumbs
  web-admin/src/features/embeds/TopNavigationBarEmbed.svelte
  web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte
Labels: Type:Bug

#5828 fix: explore's default visible dimensions and measures
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
Labels: blocker

#5831 Fix (Alerts / Reports): ensure queries are refetched after invalidation
  web-admin/src/features/alerts/selectors.ts
  web-admin/src/features/scheduled-reports/selectors.ts
Labels: Type:Bug

#5838 fix: reconnect resource watcher on project unpack
  web-common/src/features/entity-management/ResourceWatcher.svelte
  web-common/src/runtime-client/watch-request-client.ts
Labels: Type:Bug

#5833 Fix (Autogenerate Explore): ensure Metrics View exists before proceeding with Explore generation
  web-common/src/features/metrics-views/ai-generation/generateMetricsView.ts
Labels: Type:Bug

#5834 Fix (Embeds): two navigation bugs due to the MetricsView-Explore split
  web-admin/src/features/embeds/TopNavigationBarEmbed.svelte
  web-admin/src/routes/-/embed/+page.svelte
  web-common/src/features/dashboards/selectors.ts
Labels: Type:Bug

#5848 Implement `defaults:` for `Explore` resources
  proto/gen/rill/runtime/v1/resources.pb.go
  proto/gen/rill/runtime/v1/resources.pb.validate.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/rill/runtime/v1/resources.proto
  runtime/compilers/rillv1/parse_explore.go
  runtime/compilers/rillv1/parse_metrics_view.go
  runtime/compilers/rillv1/parser_test.go
  runtime/controller_test.go
  runtime/reconcilers/explore.go
  runtime/server/controller.go
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
  web-common/src/features/dashboards/stores/dashboard-stores.spec.ts
  web-common/src/features/dashboards/time-controls/super-pill/SuperPill.svelte
  web-common/src/features/dashboards/time-controls/time-control-store.spec.ts
  web-common/src/features/dashboards/time-controls/time-control-store.ts
  web-common/src/features/dashboards/time-controls/time-range-mappers.ts
  web-common/src/features/dashboards/time-controls/time-range-store.ts
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
  web-common/src/proto/gen/rill/runtime/v1/resources_pb.ts
  web-common/src/runtime-client/gen/index.schemas.ts
  web-local/tests/explores/time-controls-from-config.spec.ts
Labels: blocker

#5860 fix: explore with security policy only on metrics view not showing the `View As` button
  web-common/src/features/explores/ExplorePreviewCTAs.svelte
Labels: blocker

#5857 fix: explore state on rill developer not reset with explicit name on edit
  web-common/src/features/entity-management/infer-resource-kind.ts
  web-common/src/features/workspaces/ExploreWorkspace.svelte
Labels: blocker

#5858 fix: inferred resource kind for explore under dashboards folder
  web-common/src/features/entity-management/file-artifact.ts
Labels: blocker

#5859 fix: explore to/from pivot navigation in tabs
  web-common/src/features/dashboards/tab-bar/TabBar.svelte
Labels: blocker

#5869 Refactor: Re-use function to create-and-preview an Explore dashboard
  web-common/src/features/canvas/AddComponentMenu.svelte
  web-common/src/features/entity-management/AddAssetButton.svelte
  web-common/src/features/file-explorer/new-files.ts
  web-common/src/features/metrics-views/CreateExploreDashboardButton.svelte
  web-common/src/features/metrics-views/GoToDashboardButton.svelte
  web-common/src/features/metrics-views/MetricsViewMenuItems.svelte
  web-common/src/features/metrics-views/ai-generation/generateMetricsView.ts
  web-common/src/features/metrics-views/create-and-preview-explore.ts
  web-local/tests/explores/explores.spec.ts
  web-local/tests/utils/exploreHelpers.ts
Labels: blocker

#5877 fix: inferred resource behavior
  web-common/src/features/entity-management/entity-mappers.ts
  web-common/src/features/entity-management/file-artifact.ts
  web-common/src/features/visual-metrics-editing/lib.ts
  web-common/src/features/workspaces/VisualMetrics.svelte
Labels: Type:Bug

#5885 codemirror updates and fixes
  package-lock.json
  web-common/package.json
  web-common/src/components/editor/presets/base.ts
  web-common/src/components/editor/presets/yaml.ts
  web-common/src/components/editor/presets/yamlWithJsonAndSql.ts
  web-common/src/features/editor/getExtensionsForFile.ts
  web-common/src/features/explores/ExploreEditor.svelte
Labels: Type:Bug

#5900 Fix OLAP connector form
  web-common/src/features/connectors/code-utils.ts
  web-common/src/features/sources/modal/AddDataForm.svelte
  web-common/src/features/sources/modal/submitAddDataForm.ts
  web-common/src/features/sources/modal/yupSchemas.ts
  web-common/src/features/sources/sourceUtils.ts
Labels: blocker

#5898 fix context button hover state
  web-common/src/components/button/ContextButton.svelte
  web-local/tests/file-explorer.spec.ts
Labels: Type:Bug

#5913 fix default prop in AvatarCircleList
  web-admin/src/features/organizations/users/AvatarCircleList.svelte
Labels: Type:Bug

#5897 fix: layout of connector items in Safari
  web-common/src/components/icons/connectors/AmazonAthena.svelte
  web-common/src/components/icons/connectors/AmazonRedshift.svelte
  web-common/src/components/icons/connectors/AmazonS3.svelte
  web-common/src/components/icons/connectors/ApacheDruid.svelte
  web-common/src/components/icons/connectors/ApachePinot.svelte
  web-common/src/components/icons/connectors/ClickHouse.svelte
  web-common/src/components/icons/connectors/DuckDB.svelte
  web-common/src/components/icons/connectors/GoogleBigQuery.svelte
  web-common/src/components/icons/connectors/GoogleCloudStorage.svelte
  web-common/src/components/icons/connectors/MicrosoftAzureBlobStorage.svelte
  web-common/src/components/icons/connectors/MotherDuck.svelte
  web-common/src/components/icons/connectors/MySQL.svelte
  web-common/src/components/icons/connectors/Postgres.svelte
  web-common/src/components/icons/connectors/SQLite.svelte
  web-common/src/components/icons/connectors/Salesforce.svelte
  web-common/src/components/icons/connectors/Snowflake.svelte
  web-common/src/features/sources/modal/AddDataModal.svelte
Labels: Type:Bug

#5909 fix: alternate connector support for visual metrics
  web-common/src/components/forms/Input.svelte
  web-common/src/components/forms/InputLabel.svelte
  web-common/src/components/tag/Tag.svelte
  web-common/src/features/connectors/ConnectorEntry.svelte
  web-common/src/features/connectors/ConnectorExplorer.svelte
  web-common/src/features/connectors/connector-explorer-store.ts
  web-common/src/features/connectors/olap/DatabaseEntry.svelte
  web-common/src/features/connectors/olap/DatabaseExplorer.svelte
  web-common/src/features/connectors/olap/DatabaseSchemaEntry.svelte
  web-common/src/features/connectors/olap/TableEntry.svelte
  web-common/src/features/connectors/olap/TableMenuItems.svelte
  web-common/src/features/visual-metrics-editing/AlertConfirmation.svelte
  web-common/src/features/visual-metrics-editing/lib.ts
  web-common/src/features/workspaces/VisualMetrics.svelte
  web-common/src/layout/navigation/Navigation.svelte
Labels: blocker

#5921 fix: issues with bookmarks selection and deletion
  web-admin/src/features/bookmarks/Bookmarks.svelte
  web-admin/src/features/bookmarks/applyBookmark.ts
Labels: patch

#5923 fix: hide grains smaller than smallest_time_grain from pivot sidebar
  web-common/src/features/dashboards/pivot/PivotSidebar.svelte
Labels: patch

#5924 fix: measure filter short labels
  web-common/src/features/dashboards/filters/measure-filters/MeasureFilterBody.svelte
Labels: patch

#5925 fix: usage of metrics view name instead of explore name in pivots
  web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
  web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
  web-common/src/features/dashboards/pivot/AddField.svelte
  web-common/src/features/dashboards/pivot/PivotDisplay.svelte
  web-common/src/features/dashboards/pivot/PivotHeader.svelte
  web-common/src/features/dashboards/pivot/PivotTable.svelte
  web-common/src/features/dashboards/pivot/PivotToolbar.svelte
Labels: patch

#5941 refactor: welcome redirect flow
  .github/workflows/web-test-code-quality.yml
  scripts/tsc-with-whitelist.sh
  web-admin/src/features/projects/ProjectCard.svelte
  web-common/src/components/card/Card.svelte
  web-common/src/features/welcome/EmptyProject.svelte
  web-common/src/features/welcome/ProjectCards.svelte
  web-common/src/features/welcome/is-project-initialized.ts
  web-local/package.json
  web-local/src/routes/(application)/(workspace)/+layout.svelte
  web-local/src/routes/(application)/(workspace)/+page.svelte
  web-local/src/routes/(application)/(workspace)/files/[...file]/+page.ts
  web-local/src/routes/(application)/welcome/+page.svelte
  web-local/src/routes/+layout.svelte
  web-local/src/routes/+layout.ts
  web-local/vite.config.ts
Labels: Type:Bug, patch
