Repository rilldata/rill, pull requests merged in 2024-08, with the labels that each got.

#5367 fix: Avoid showing the spinner on the avatar every time the page is focused.
  web-common/src/features/authentication/LocalAvatarButton.svelte
Labels: blocker

#5369 fix: Non git project crashing on status page on rill cloud
  web-admin/src/features/projects/github/github-utils.ts
Labels: blocker

#5371 fix: remove z-index for leaderboard rows
  web-common/src/components/dialog-v2/dialog-overlay.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte
Labels: blocker

#5370 fix: update row height for filter bar
  web-common/src/features/dashboards/filters/Filters.svelte
Labels: blocker

#5381 fix: Add author details for commits during project github connection update
  admin/server/github.go
Labels: blocker

#5368 fix: backwards compatibility for alerts
  proto/buf.gen.ui.yaml
  proto/buf.gen.yaml
  proto/gen/rill/admin/v1/ai.pb.gw.go
  proto/gen/rill/admin/v1/ai_grpc.pb.go
  proto/gen/rill/admin/v1/api.pb.gw.go
  proto/gen/rill/admin/v1/api_grpc.pb.go
  proto/gen/rill/admin/v1/telemetry.pb.gw.go
  proto/gen/rill/admin/v1/telemetry_grpc.pb.go
  proto/gen/rill/local/v1/api.pb.gw.go
  proto/gen/rill/local/v1/api_grpc.pb.go
  proto/gen/rill/runtime/v1/api.pb.gw.go
  proto/gen/rill/runtime/v1/api_grpc.pb.go
  proto/gen/rill/runtime/v1/connectors.pb.gw.go
  proto/gen/rill/runtime/v1/connectors_grpc.pb.go
  proto/gen/rill/runtime/v1/queries.pb.gw.go
  proto/gen/rill/runtime/v1/queries_grpc.pb.go
  proto/gen/rill/runtime/v1/resources.pb.go
  proto/gen/rill/runtime/v1/resources.pb.validate.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/rill/runtime/v1/resources.proto
  web-admin/src/features/alerts/metadata/AlertMetadata.svelte
  web-admin/src/features/alerts/selectors.ts
  web-admin/src/routes/[organization]/[project]/-/alerts/[alert]/open/+page.svelte
  web-common/src/features/alerts/EditAlertForm.svelte
  web-common/src/proto/gen/rill/runtime/v1/resources_pb.ts
  web-common/src/runtime-client/gen/index.schemas.ts
Labels: blocker

#5395 fix alert snoozes only honoured till alert history remains
  proto/gen/rill/runtime/v1/resources.pb.go
  proto/gen/rill/runtime/v1/resources.pb.validate.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/rill/runtime/v1/resources.proto
  runtime/reconcilers/alert.go
  web-common/src/proto/gen/rill/runtime/v1/resources_pb.ts
  web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
  web-common/src/runtime-client/gen/index.schemas.ts
Labels: blocker

#5389 slack alert viewable by all project users
  docs/docs/explore/alerts/slack.md
  runtime/security.go
Labels: Type:Bug, blocker

#5404 fix: Block user from deploying when deployed project is connected to github
  cli/pkg/local/server.go
  proto/gen/rill/local/v1/api.pb.go
  proto/gen/rill/local/v1/api.pb.gw.go
  proto/gen/rill/local/v1/api.pb.validate.go
  proto/gen/rill/local/v1/api_grpc.pb.go
  proto/gen/rill/local/v1/localv1connect/api.connect.go
  proto/rill/local/v1/api.proto
  web-admin/src/features/projects/github/GithubOverwriteConfirmationDialog.svelte
  web-admin/src/features/projects/github/GithubRepoInline.svelte
  web-admin/src/features/projects/github/GithubRepoSelectionDialog.svelte
  web-admin/src/features/projects/github/ProjectGithubConnection.svelte
  web-common/src/components/commands/CLICommandDisplay.svelte
  web-common/src/features/authentication/LocalAvatarButton.svelte
  web-common/src/features/dashboards/workspace/DeployDashboardCTA.svelte
  web-common/src/features/project/ProjectDeployer.ts
  web-common/src/features/project/PushToGitForDeployDialog.svelte
  web-common/src/features/project/github-utils.ts
  web-common/src/proto/gen/rill/local/v1/api_connect.ts
  web-common/src/proto/gen/rill/local/v1/api_pb.ts
  web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
  web-common/src/runtime-client/local-service.ts
  web-local/src/routes/(misc)/deploy/+page.svelte
Labels: blocker

#5426 remove progress interface completely
  runtime/drivers/duckdb/transporter_duckDB_to_duckDB_test.go
  runtime/drivers/duckdb/transporter_filestore_to_duckDB.go
  runtime/drivers/duckdb/transporter_motherduck_to_duckDB.go
  runtime/drivers/duckdb/transporter_mysql_to_duckDB_test.go
  runtime/drivers/duckdb/transporter_objectStore_to_duckDB.go
  runtime/drivers/duckdb/transporter_postgres_to_duckDB_test.go
  runtime/drivers/duckdb/transporter_sqlite_to_duckDB_test.go
  runtime/drivers/duckdb/transporter_test.go
  runtime/drivers/snowflake/sql_store.go
  runtime/drivers/transporter.go
  runtime/reconcilers/source.go
Labels: blocker

#5445 fix: disable api comparison when ui comparison is disabled
  web-common/src/features/dashboards/dashboard-utils.ts
Labels: Type:Bug

#5516 feat: add support for linux aarch64
  .goreleaser.yaml
  runtime/drivers/duckdb/extensions/embed/linux_arm64/.gitkeep
  runtime/drivers/duckdb/extensions/extensions_linux_arm64.go
  scripts/embed_duckdb_ext/main.go
  scripts/install.sh
Labels: Area:CLI
