Repository rilldata/rill, pull requests merged in 2024-09, with the labels that each got.

#5558 Fix (Alerts): Handle a missing Metrics View on the Alert page
  web-admin/src/features/alerts/metadata/AlertMetadata.svelte
  web-admin/src/features/errors/error-utils.ts
  web-common/src/runtime-client/is-runtime-query.ts
  web-common/src/runtime-client/query-matcher.ts
Labels: Type:Bug

#5587 support for tuple and geometric types for clickhouse
  go.mod
  runtime/drivers/clickhouse/olap.go
  runtime/pkg/jsonval/jsonval.go
  runtime/pkg/pbutil/pbutil.go
Labels: blocker

#5550 postgres column encryption for sensitive data
  admin/admin.go
  admin/database/database.go
  admin/database/postgres/migrations/0043.sql
  admin/database/postgres/postgres.go
  admin/database/postgres/postgres_test.go
  admin/provisioner/static_test.go
  admin/server/admin_rbac_test.go
  cli/cmd/admin/start.go
  scripts/generate_enc_keyring/main.go
Labels: blocker

#5559 Fix: Account for multi-OLAP paradigm when checking for OLAP modeling support
  web-common/src/features/connectors/olap/TableMenuItems.svelte
  web-common/src/features/connectors/olap/selectors.ts
  web-common/src/features/entity-management/AddAssetButton.svelte
  web-common/src/features/metrics-views/MetricsInspector.svelte
  web-common/src/features/metrics-views/workspace/editor/Placeholder.svelte
  web-common/src/features/workspaces/MetricsWorkspace.svelte
Labels: blocker

#4997 pivot: resize column ux
  web-common/src/components/button/Button.svelte
  web-common/src/features/dashboards/pivot/PivotDisplay.svelte
  web-common/src/features/dashboards/pivot/PivotExportButton.svelte
  web-common/src/features/dashboards/pivot/PivotHeader.svelte
  web-common/src/features/dashboards/pivot/PivotTable.svelte
  web-common/src/features/dashboards/pivot/PivotToolbar.svelte
  web-common/src/features/dashboards/pivot/pivot-column-definition.ts
  web-common/src/features/dashboards/rows-viewer/RowsViewerAccordion.svelte
  web-common/src/features/dashboards/rows-viewer/row-viewer-store.ts
  web-common/src/layout/Resizer.svelte
Labels: blocker

#5540 fix: User invite not working for a single pill
  web-admin/src/features/projects/user-invite/UserInviteAllowlist.svelte
  web-admin/src/features/projects/user-invite/UserInviteForm.svelte
  web-admin/src/routes/[organization]/[project]/-/invite/+page.svelte
Labels: blocker

#5121 fix: pretty AI generated yaml
  runtime/server/generate_metrics_view.go
  runtime/server/generate_metrics_view_test.go
  web-local/tests/dashboards/dashboards.spec.ts
  web-local/tests/dashboards/leaderboard-and-dim-table-sort.spec.ts
Labels: blocker

#5548 tweak: remote content warning conditional
  web-common/src/features/editor/Codespace.svelte
Labels: blocker

#5566 fix: infinite query glitch on invalid spec
  web-common/src/features/charts/prompt/ChartDataDisplay.svelte
  web-common/src/features/workspaces/ChartWorkspace.svelte
Labels: blocker

#5573 feat: enable time comparison for time dimension in pivot
  web-common/src/features/dashboards/pivot/pivot-infinite-scroll.ts
  web-common/src/features/dashboards/pivot/pivot-utils.ts
Labels: blocker

#5643 Fix (Pivot Export): Use dimension `alias` in `sort` clause
  web-common/src/features/dashboards/pivot/pivot-export.ts
Labels: Type:Bug

#5602 fix: Revert rill deploy command to be a wrapper around upload and github repo flows
  cli/cmd/deploy/deploy.go
  cli/cmd/project/connect_github.go
  cli/cmd/project/deploy.go
  cli/cmd/project/project.go
  cli/pkg/local/server.go
  cli/pkg/local/slots.go
Labels: blocker

#5446 Prevent API requests from firing when no measures
  web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte
  web-common/src/features/dashboards/time-series/timeseries-data-store.ts
  web-common/src/features/entity-management/resource-selectors.ts
  web-common/src/lib/event-bus/event-bus.ts
  web-local/src/routes/(viz)/dashboard/[name]/+page.svelte
  web-local/src/routes/+layout.svelte
Labels: blocker

#5661 Fix (URL state): capitalization bug
  web-common/src/features/dashboards/proto-state/dashboard-url-state.ts
Labels: Type:Bug, patch

#5649 Design: new dashboard icons
  web-common/src/components/icons/CanvasDashboardIcon.svelte
  web-common/src/components/icons/MetricsExplorerIcon.svelte
  web-common/src/features/file-explorer/NavFile.svelte
Labels: design

#5671 fix: skip if slot scale matches recommends
  admin/worker/run_autoscaler.go
  admin/worker/run_autoscaler_test.go
Labels: Type:Bug

#5668 Fix search for Custom Dashboards
  web-admin/src/features/dashboards/listing/DashboardsTable.svelte
Labels: Type:Bug

#5572 Refactor `WatchResourcesClient` response handler
  web-common/src/features/connectors/utils.ts
  web-common/src/features/entity-management/WatchResourcesClient.ts
  web-common/src/features/entity-management/file-artifact.ts
  web-common/src/features/entity-management/file-artifacts.ts
  web-common/src/features/entity-management/resource-selectors.ts
Labels: blocker

#5673 fix: alerts without an associated dashboard
  web-admin/src/features/alerts/metadata/AlertMetadata.svelte
  web-admin/src/routes/[organization]/[project]/-/alerts/[alert]/open/+page.svelte
Labels: blocker

#5689 Fix analyze connectors for email notifier
  cli/cmd/env/configure.go
  runtime/compilers/rillv1/connectors.go
Labels: blocker

#5685 fix: alert dialog not getting updated measures and dimensions on switching dashbaords
  web-admin/src/features/navigation/TopNavigationBar.svelte
Labels: blocker

#5696 Fix (Alerts): Remove constraint on percent change
  web-common/src/features/alerts/form-utils.ts
Labels: Type:Bug, patch

#5705 fix: account for time zone in zoom button
  web-common/src/features/dashboards/time-series/ChartInteractions.svelte
Labels: Type:Bug

#5600 Docs deploy change
  docs/blog/0.26.md
  docs/blog/0.42.md
  docs/blog/0.43.md
  docs/blog/0.44.md
  docs/blog/0.45.md
  docs/blog/0.46.md
  docs/blog/0.47.md
  docs/blog/0.48.md
  docs/blog/0.49.md
  docs/docs/build/connect/connect.md
  docs/docs/build/connect/multiple-connectors.md
  docs/docs/build/connect/source-refresh.md
  docs/docs/concepts/developerVsCloud.md
  docs/docs/deploy/deploy-dashboard/_category_.yml
  docs/docs/deploy/deploy-dashboard/deploy-dashboard.md
  docs/docs/deploy/deploy-dashboard/deploy-from-ci.md
  docs/docs/deploy/deploy-dashboard/github-101.md
  docs/docs/deploy/existing-project/existing-project.md
  docs/docs/deploy/project-errors.md
  docs/docs/deploy/templating.md
  docs/docs/explore/dashboard-101.md
  docs/docs/home/get-started.md
  docs/docs/home/install.md
  docs/docs/reference/project-files/index.md
  docs/docs/reference/project-files/sources.md
  docs/static/img/deploy/existing-project/cli-upload.png
  docs/static/img/deploy/existing-project/connect-github.png
  docs/static/img/deploy/existing-project/create-new-repo.png
  docs/static/img/deploy/existing-project/finished.png
  docs/static/img/deploy/existing-project/github-app-permissions.png
  docs/static/img/deploy/existing-project/install-rill-cloud.png
  docs/static/img/deploy/existing-project/select-repo.png
  docs/static/img/deploy/existing-project/status.png
  web-admin/src/features/projects/github/DisconnectProjectConfirmDialog.svelte
  web-admin/src/features/projects/github/ProjectGithubConnection.svelte
  web-common/src/features/project/PushToGitForDeployDialog.svelte
Labels: Type:Documentation

#5739 fix: navigation store missing set function
  web-common/src/layout/navigation/Navigation.svelte
Labels: Type:Bug

#5759 fix: explore flashes on breadcrumb interaction
  web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte
Labels: Type:Bug

#5777 update calendar component api
  web-common/src/components/date-picker/Calendar.svelte
  web-common/src/components/date-picker/Day.svelte
  web-common/src/components/date-picker/Month.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/CalendarPlusDateInput.svelte
Labels: blocker

#5781 broaden conditional for readonly filter chips
  web-common/src/features/dashboards/filters/FilterChipsReadOnly.svelte
Labels: Type:Bug

#5796 fix: not all sources are named hee haw
  web-common/src/features/sources/modal/SourceImportedModal.svelte
Labels: Type:Bug
