Repository rilldata/rill, pull requests merged in 2024-12, with the labels that each got.

#6190 fix: uncaught error in header
  web-common/src/layout/workspace/WorkspaceHeader.svelte
Labels: Type:Bug

#6192 fix: visual explore theme editing
  web-common/src/components/color-picker/ColorInput.svelte
Labels: Type:Bug

#6168 Allow variable creation with different target environments
  web-admin/src/features/projects/environment-variables/ActionsCell.svelte
  web-admin/src/features/projects/environment-variables/ActivityCell.svelte
  web-admin/src/features/projects/environment-variables/AddDialog.svelte
  web-admin/src/features/projects/environment-variables/EditDialog.svelte
  web-admin/src/features/projects/environment-variables/EnvironmentVariablesTable.svelte
  web-admin/src/features/projects/environment-variables/KeyCell.svelte
  web-admin/src/features/projects/environment-variables/types.ts
  web-admin/src/features/projects/environment-variables/utils.ts
  web-admin/src/routes/[organization]/[project]/-/settings/environment-variables/+page.svelte
Labels: blocker

#6193 fix: refetch explore resource
  web-common/src/features/entity-management/WatchResourcesClient.ts
Labels: Type:Bug

#6195 fix: comparison calendar not showing
  web-common/src/components/date-picker/Calendar.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/CalendarPlusDateInput.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte
Labels: Type:Bug

#6211 Hide all "Start pivot" buttons when `embeds.hide_pivot: true`
  web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
  web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
  web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte
  web-common/src/features/dashboards/time-dimension-details/TimeDimensionDisplay.svelte
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
  web-common/src/features/dashboards/workspace/Dashboard.svelte
Labels: Type:Bug

#6207 fix: conditionally export comparison data in dimension table
  web-common/src/features/dashboards/dimension-table/export-toplist.ts
Labels: Type:Bug

#6176 Integrate PostHog session replay
  .github/workflows/cli-release.yml
  .github/workflows/rill-ui.yml
  package-lock.json
  web-admin/src/features/authentication/AvatarButton.svelte
  web-admin/src/routes/+layout.svelte
  web-admin/src/routes/+layout.ts
  web-common/package.json
  web-common/src/features/project/ProjectDeployer.ts
  web-common/src/lib/analytics/posthog.ts
  web-common/src/vite-env.d.ts
  web-local/src/routes/+layout.svelte
Labels: blocker

#6209 Fix "Select all" buttons
  web-common/src/features/dashboards/dimension-table/DimensionHeader.svelte
  web-common/src/features/dashboards/time-dimension-details/TDDHeader.svelte
Labels: Type:Bug, blocker

#6229 fix: displayname returned as empty string when undefined
  web-common/src/features/dashboards/big-number/MeasuresContainer.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardControls.svelte
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
Labels: Type:Bug

#6149 docs / metrics view locale_d3 example
  docs/docs/reference/project-files/metrics-view.md
Labels: Type:Documentation

#6237 fix: default timezone when timezones is not defined in yaml config
  web-common/src/features/dashboards/time-controls/super-pill/SuperPill.svelte
  web-common/src/features/dashboards/url-state/defaults.ts
  web-common/src/features/dashboards/url-state/getDefaultExplorePreset.ts
Labels: Type:Bug, blocker

#6236 fix(Welcome screen): Avoid race condition after unpacking an empty project
  web-common/src/features/sources/modal/FileDrop.svelte
  web-common/src/features/sources/modal/LocalSourceUpload.svelte
  web-common/src/features/sources/modal/submitAddDataForm.ts
Labels: Type:Bug, patch

#6151 docs/ add examples for expr explore yaml
  docs/docs/reference/project-files/explore-dashboards.md
Labels: Type:Documentation

#6189 docs/ Update Env Variable UI (Docs / Tutorial)
  docs/docs/build/credentials/credentials.md
  docs/docs/deploy/deploy-credentials.md
  docs/docs/manage/variables-and-credentials.md
  docs/docs/tutorials/administration/project/credentials-env-variable-management.md
  docs/docs/tutorials/administration/project/env-var-ui.png
  docs/docs/tutorials/other/component-variable-freedom.md
  docs/static/img/manage/var-and-creds/add-variable.png
  docs/static/img/tutorials/admin/env-var-ui.png
  web-admin/src/routes/[organization]/[project]/-/settings/environment-variables/+page.svelte
Labels: Type:Documentation

#6235 Fix "Source imported successfully" modal
  web-common/src/features/entity-management/WatchResourcesClient.ts
  web-common/src/features/sources/modal/FileDrop.svelte
  web-common/src/features/sources/modal/LocalSourceUpload.svelte
  web-common/src/features/sources/modal/submitAddDataForm.ts
  web-common/src/features/sources/source-imported-utils.ts
Labels: Type:Bug, patch

#6223 Env Var Feedback
  web-admin/src/features/projects/environment-variables/ActionsCell.svelte
  web-admin/src/features/projects/environment-variables/AddDialog.svelte
  web-admin/src/features/projects/environment-variables/EditDialog.svelte
  web-admin/src/features/projects/environment-variables/EnvironmentVariablesTable.svelte
  web-admin/src/features/projects/environment-variables/ValueCell.svelte
  web-admin/src/features/projects/environment-variables/utils.ts
  web-admin/src/routes/[organization]/[project]/-/settings/environment-variables/+page.svelte
  web-common/src/components/dropdown-menu/DropdownMenuContent.svelte
  web-common/src/components/icons/Eye.svelte
  web-common/src/components/icons/EyeInvisible.svelte
  web-common/src/components/table/BasicTable.svelte
Labels: blocker

#6251 fix: alert edit using metrics view name instead of explore name
  web-common/src/features/alerts/EditAlertForm.svelte
Labels: Type:Bug, blocker

#6263 fix: 500 error when visiting hibernating projects
  web-admin/src/routes/+layout.ts
Labels: blocker

#6275 fix: default value for valid_percent_of_total in visual metrics editing
  web-common/src/features/visual-metrics-editing/lib.ts
Labels: Type:Bug

#6260 Don't show the "Source imported successfully" modal when unpacking example projects
  web-common/src/features/entity-management/AddAssetButton.svelte
  web-common/src/features/entity-management/WatchResourcesClient.ts
  web-common/src/features/entity-management/dag-utils.ts
  web-common/src/features/welcome/ProjectCards.svelte
Labels: patch

#6269 fix: non-timestamp explore component mounting and unmounting during load
  web-common/src/features/dashboards/workspace/Dashboard.svelte
Labels: blocker

#6270 fix: comparison time ranges resetting when switching time ranges
  web-common/src/components/forms/Select.svelte
  web-common/src/features/dashboards/url-state/convertPresetToExploreState.ts
Labels: blocker

#6286 Disable control-plane features for embedded dashboards
  web-admin/src/routes/-/embed/+page.svelte
Labels: Type:Bug

#6284 Fix: Prevent unintended data preloading when hovering project links in the breadcrumb menu
  web-admin/src/features/navigation/TopNavigationBar.svelte
  web-common/src/components/dropdown-menu/DropdownMenuCheckboxItem.svelte
  web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte
  web-common/src/components/navigation/breadcrumbs/types.ts
Labels: blocker

#6288 Fix: full width for TDD charts
  web-common/src/features/dashboards/workspace/Dashboard.svelte
Labels: blocker

#6238 fix: session storage retrieval for url messes with the url history
  web-admin/src/features/bookmarks/BookmarksDropdownMenuContent.svelte
  web-admin/src/features/bookmarks/selectors.ts
  web-admin/src/features/dashboards/query-mappers/mapQueryToDashboard.ts
  web-admin/src/routes/[organization]/[project]/-/share/[token]/+layout.ts
  web-admin/src/routes/[organization]/[project]/-/share/[token]/+page.svelte
  web-admin/src/routes/[organization]/[project]/-/share/[token]/+page.ts
  web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+layout.ts
  web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte
  web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.ts
  web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
  web-common/src/features/dashboards/proto-state/fromProto.ts
  web-common/src/features/dashboards/proto-state/proto.spec.ts
  web-common/src/features/dashboards/proto-state/sparse-proto.spec.ts
  web-common/src/features/dashboards/state-managers/StateManagersProvider.svelte
  web-common/src/features/dashboards/state-managers/state-managers.ts
  web-common/src/features/dashboards/stores/AdvancedMeasureCorrector.spec.ts
  web-common/src/features/dashboards/stores/DashboardStateProvider.svelte
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
  web-common/src/features/dashboards/stores/dashboard-stores.spec.ts
  web-common/src/features/dashboards/stores/dashboard-stores.ts
  web-common/src/features/dashboards/stores/persistent-dashboard-state.ts
  web-common/src/features/dashboards/stores/syncDashboardState.ts
  web-common/src/features/dashboards/stores/test-data/helpers.ts
  web-common/src/features/dashboards/tab-bar/TabBar.svelte
  web-common/src/features/dashboards/time-series/BackToExplore.svelte
  web-common/src/features/dashboards/url-state/DashboardURLStateSync.svelte
  web-common/src/features/dashboards/url-state/DashboardURLStateSyncWrapper.svelte
  web-common/src/features/dashboards/url-state/convertExploreStateToPreset.ts
  web-common/src/features/dashboards/url-state/convertExploreStateToURLSearchParams.ts
  web-common/src/features/dashboards/url-state/convertPresetToExploreState.ts
  web-common/src/features/dashboards/url-state/convertURLToExplorePreset.ts
  web-common/src/features/dashboards/url-state/explore-web-view-store.spec.ts
  web-common/src/features/dashboards/url-state/explore-web-view-store.ts
  web-common/src/features/dashboards/url-state/getExploreStateFromSessionStorage.ts
  web-common/src/features/dashboards/url-state/getUpdatedUrlForExploreState.ts
  web-common/src/features/dashboards/url-state/invalid-url-state-variations.spec.ts
  web-common/src/features/dashboards/url-state/mappers.ts
  web-common/src/features/dashboards/url-state/url-state-variations.spec.ts
  web-common/src/features/explores/ExploreEditor.svelte
  web-common/src/features/explores/PreviewButton.svelte
  web-common/src/features/explores/selectors.ts
  web-common/src/features/metrics-views/editor/MetricsEditor.svelte
  web-local/src/routes/(viz)/explore/[name]/+layout.ts
  web-local/src/routes/(viz)/explore/[name]/+page.svelte
  web-local/src/routes/(viz)/explore/[name]/+page.ts
Labels: blocker

#6272 fix: file conflict resolution
  package-lock.json
  web-common/package.json
  web-common/src/components/button/Button.svelte
  web-common/src/components/forms/FieldSwitcher.svelte
  web-common/src/components/icons/LoadingSpinner.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte
  web-common/src/features/editor/Codespace.svelte
  web-common/src/features/editor/DiffBar.svelte
  web-common/src/features/editor/Editor.svelte
  web-common/src/features/editor/config.ts
  web-common/src/features/entity-management/async-save-state.ts
  web-common/src/features/entity-management/file-artifact.ts
  web-common/src/features/entity-management/file-artifacts.ts
  web-common/src/features/explores/ExploreEditor.svelte
  web-common/src/features/file-explorer/NavFile.svelte
  web-common/src/features/metrics-views/editor/MetricsEditor.svelte
  web-common/src/features/sources/editor/SourceEditor.svelte
  web-common/src/features/visual-metrics-editing/Sidebar.svelte
  web-common/src/features/workspaces/CanvasDashboardWorkspace.svelte
  web-common/src/features/workspaces/ExploreWorkspace.svelte
  web-common/src/features/workspaces/SourceWorkspace.svelte
  web-common/src/features/workspaces/VisualExploreEditing.svelte
  web-common/src/features/workspaces/VisualMetrics.svelte
  web-common/src/layout/ApplicationHeader.svelte
  web-common/src/layout/workspace/WorkspaceEditorContainer.svelte
  web-local/tests/explores/time-controls-from-config.spec.ts
  web-local/tests/sources.spec.ts
  web-local/tests/utils/commonHelpers.ts
Labels: Type:Bug, blocker

#6204 0.52 release notes
  docs/blog/0.52.md
Labels: Type:Documentation

#6314 fix: time ranges missing from bookmarks
  web-admin/src/features/bookmarks/BookmarksDropdownMenuContent.svelte
  web-admin/src/features/bookmarks/selectors.ts
Labels: Type:Bug, patch

#6315 fix: time range params vanishing on reloading
  web-common/src/features/dashboards/url-state/DashboardURLStateSync.svelte
Labels: Type:Bug, patch

#6319 fix: query cancellation issue
  web-common/src/features/dashboards/workspace/Dashboard.svelte
Labels: Type:Bug, patch

#6318 fix: bookmark interaction with url params
  web-admin/src/features/bookmarks/Bookmarks.svelte
  web-admin/src/features/bookmarks/BookmarksDropdownMenuContent.svelte
  web-admin/src/features/bookmarks/BookmarksDropdownMenuItem.svelte
  web-admin/src/features/bookmarks/selectors.ts
  web-common/src/features/dashboards/url-state/DashboardURLStateSync.svelte
Labels: Type:Bug
