Repository rilldata/rill, pull requests merged in 2024-11, with the labels that each got.

#6026 fix: remove global preventDefault calls
  web-common/src/components/data-graphic/actions/scrub-action-factory.ts
  web-common/src/features/file-explorer/nav-entry-drag-drop-store.ts
Labels: Type:Bug

#6057 fix: line error boundaries
  web-common/src/features/metrics-views/errors.ts
Labels: Type:Bug

#6035 Billing UI follow ups
  cli/pkg/local/server.go
  netlify.toml
  proto/gen/rill/local/v1/api.pb.go
  proto/gen/rill/local/v1/api.pb.validate.go
  proto/rill/local/v1/api.proto
  web-admin/orval.config.ts
  web-admin/src/client/gen/admin-service/admin-service.ts
  web-admin/src/features/billing/issues/getMessageForTrialPlan.ts
  web-admin/src/features/billing/plans/CancelledTeamPlan.svelte
  web-admin/src/features/billing/plans/EnterprisePlan.svelte
  web-admin/src/features/billing/plans/POCPlan.svelte
  web-admin/src/features/billing/plans/Plan.svelte
  web-admin/src/features/billing/plans/PlanQuotas.svelte
  web-admin/src/features/billing/plans/TeamPlan.svelte
  web-admin/src/features/billing/plans/TrialPlan.svelte
  web-admin/src/features/billing/plans/selectors.ts
  web-admin/src/features/billing/plans/utils.ts
  web-admin/src/features/organizations/settings/OrgDomainAllowListSettings.svelte
  web-admin/src/routes/+layout.svelte
  web-admin/src/routes/+layout.ts
  web-common/src/features/dashboards/workspace/DeployProjectCTA.svelte
  web-common/src/features/organization/utils.ts
  web-common/src/features/project/OrgSelector.svelte
  web-common/src/features/project/ProjectDeployer.ts
  web-common/src/features/project/deploy-errors.ts
  web-common/src/lib/number-formatting/memory-size.ts
  web-common/src/proto/gen/rill/local/v1/api_pb.ts
  web-local/src/routes/(misc)/deploy/+page.svelte
Labels: blocker

#6079 Fix: handle `null` response from `TimeRangeSummary` API
  web-common/src/features/dashboards/proto-state/DashboardURLStateProvider.svelte
Labels: Type:Bug

#6082 Rill E2E setup
  cli/cmd/devtool/data/cloud-deps.docker-compose.yml
  cli/cmd/devtool/data/otel-collector-config.yaml
  cli/cmd/devtool/dotenv.go
  cli/cmd/devtool/seed.go
  cli/cmd/devtool/start.go
Labels: blocker

#6093 fix: bookmark query by doing a case insensitive query
  admin/database/postgres/migrations/0053.sql
  admin/database/postgres/postgres.go
Labels: blocker

#6098 fix: billing UI minor issues
  web-admin/src/features/billing/issues/getMessageForCancelledIssue.ts
  web-admin/src/features/billing/plans/CancelledTeamPlan.svelte
  web-admin/src/features/billing/plans/TeamPlan.svelte
  web-admin/src/features/billing/plans/TrialPlan.svelte
  web-admin/src/features/organizations/settings/OrgNameSettings.svelte
  web-admin/src/routes/[organization]/-/upgrade-callback/+page.svelte
  web-common/src/components/forms/Input.svelte
  web-common/src/features/project/DeployError.svelte
  web-common/src/lib/time/ranges/iso-ranges.ts
  web-local/src/routes/(misc)/deploy/+page.svelte
Labels: blocker

#6099 fix: scroll position in pivot
  web-common/src/features/dashboards/pivot/PivotTable.svelte
  web-common/src/features/dashboards/pivot/pivot-data-store.ts
Labels: blocker

#6102 fix : remove table directory while holding tx lock
  runtime/drivers/duckdb/olap.go
Labels: blocker

#6091 fix: autogenerate metrics indentation
  runtime/server/generate_metrics_view.go
Labels: blocker

#6115 Billing UI: Hide modules from Orgs on Enterprise plans
  scripts/tsc-with-whitelist.sh
  web-admin/src/features/billing/Payment.svelte
  web-admin/src/routes/[organization]/-/settings/+layout.svelte
  web-admin/src/routes/[organization]/-/settings/+layout.ts
  web-admin/src/routes/[organization]/-/settings/billing/+page.svelte
  web-admin/src/routes/[organization]/-/settings/usage/+page.svelte
  web-admin/src/routes/[organization]/-/settings/usage/+page.ts
Labels: blocker

#6106 feat: big num new formatting rules
  web-common/src/lib/number-formatting/format-measure-value.ts
  web-common/src/lib/number-formatting/humanizer-types.ts
  web-common/src/lib/number-formatting/strategies/per-range-bignum-options.ts
  web-common/src/lib/number-formatting/utils/count-digits.ts
  web-local/tests/explores/dimension-and-measure-selection.spec.ts
  web-local/tests/explores/explores.spec.ts
  web-local/tests/explores/number-formatting.spec.ts
  web-local/tests/explores/time-controls-from-config.spec.ts
  web-local/tests/metrics-editor.spec.ts
Labels: blocker

#6125 fix: leaderboard column sorting behavior
  web-common/src/features/dashboards/dimension-table/DimensionDisplay.svelte
  web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
  web-common/src/features/dashboards/leaderboard/leaderboard-utils.ts
  web-common/src/features/dashboards/time-controls/comparison-pill/ComparisonPill.svelte
Labels: patch

#6126 Fix (Public URLs): state initialization
  web-admin/src/features/public-urls/DashboardPublicURLStateProvider.svelte
  web-admin/src/routes/[organization]/[project]/-/share/[token]/+page.svelte
Labels: Type:Bug, patch

#6139 fix: exclude mode handling
  web-common/src/features/visual-editing/SelectionDropdown.svelte
  web-common/src/features/workspaces/VisualExploreEditing.svelte
Labels: Type:Bug

#6166 Project Status: "Refresh" button should do incremental refreshes, if possible
  web-admin/src/features/projects/status/ProjectResources.svelte
Labels: patch

#6177 fix: logged out users getting a login page for public projects
  web-admin/src/features/navigation/TopNavigationBar.svelte
  web-admin/src/routes/+layout.ts
Labels: Type:Bug, patch

#6178 fix: issues with managed plan and sub/trial ended handing revert
  web-admin/src/features/billing/Payment.svelte
  web-admin/src/features/billing/plans/POCPlan.svelte
  web-admin/src/features/billing/plans/Plan.svelte
  web-admin/src/features/billing/plans/utils.ts
  web-admin/src/routes/[organization]/-/settings/+layout.svelte
Labels: Type:Bug, patch
