Repository rilldata/rill, pull requests merged in 2024-05, with the labels that each got.

#4781 Fix URL decoding already decoded state
  web-common/src/features/dashboards/proto-state/fromProto.ts
Labels: blocker

#4785 fix missing argument in select context
  admin/database/postgres/postgres.go
Labels: Type:Bug

#4769 Custom comparison chart in TDD
  web-common/src/features/charts/templates/build-template.ts
  web-common/src/features/charts/templates/grouped-bar.ts
  web-common/src/features/charts/templates/simple-bar.ts
  web-common/src/features/charts/templates/stacked-bar.ts
  web-common/src/features/dashboards/time-dimension-details/charts/TDDAlternateChart.svelte
  web-common/src/features/dashboards/time-dimension-details/charts/tdd-tooltip-formatter.ts
  web-common/src/features/dashboards/time-dimension-details/charts/utils.ts
  web-common/src/features/dashboards/time-series/MetricsTimeSeriesCharts.svelte
Labels: blocker

#4782 Add back reconnection to watch request client
  web-common/src/features/sources/source-imported-utils.ts
  web-common/src/runtime-client/watch-request-client.ts
Labels: blocker

#4790 Runtime: Don't expand the path in the URL of the file APIs
  proto/gen/rill/admin/v1/ai.pb.go
  proto/gen/rill/admin/v1/api.pb.go
  proto/gen/rill/admin/v1/internal.pb.go
  proto/gen/rill/admin/v1/telemetry.pb.go
  proto/gen/rill/runtime/v1/api.pb.go
  proto/gen/rill/runtime/v1/api.pb.gw.go
  proto/gen/rill/runtime/v1/colors.pb.go
  proto/gen/rill/runtime/v1/connectors.pb.go
  proto/gen/rill/runtime/v1/export_format.pb.go
  proto/gen/rill/runtime/v1/expression.pb.go
  proto/gen/rill/runtime/v1/queries.pb.go
  proto/gen/rill/runtime/v1/resources.pb.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/gen/rill/runtime/v1/schema.pb.go
  proto/gen/rill/runtime/v1/time_grain.pb.go
  proto/rill/runtime/v1/api.proto
  web-common/src/features/charts/editor/ChartsEditor.svelte
  web-common/src/features/charts/prompt/generateChart.ts
  web-common/src/features/dashboards/granular-access-policies/useDashboardPolicyCheck.ts
  web-common/src/features/dashboards/granular-access-policies/useMockUsers.ts
  web-common/src/features/entity-management/AddAssetButton.svelte
  web-common/src/features/entity-management/actions.ts
  web-common/src/features/entity-management/file-artifacts.ts
  web-common/src/features/entity-management/file-selectors.ts
  web-common/src/features/entity-management/watch-files-client.ts
  web-common/src/features/feature-flags.ts
  web-common/src/features/file-explorer/NavDirectoryEntry.svelte
  web-common/src/features/file-explorer/new-files.ts
  web-common/src/features/generic-yaml-editor/YamlWorkspaceBody.svelte
  web-common/src/features/metrics-views/ai-generation/generateMetricsView.ts
  web-common/src/features/metrics-views/workspace/editor/Placeholder.svelte
  web-common/src/features/metrics-views/workspace/editor/update-metrics.ts
  web-common/src/features/metrics-views/workspace/inspector/MetricsInspector.svelte
  web-common/src/features/models/utils/model-is-empty/index.ts
  web-common/src/features/project/selectors.ts
  web-common/src/features/sources/createModel.ts
  web-common/src/features/sources/modal/createSource.ts
  web-common/src/features/sources/modal/submitRemoteSourceForm.ts
  web-common/src/features/sources/refreshSource.ts
  web-common/src/features/sources/selectors.ts
  web-common/src/runtime-client/gen/index.schemas.ts
  web-common/src/runtime-client/gen/runtime-service/runtime-service.ts
  web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
  web-local/src/routes/(application)/chart/[name]/+page.svelte
  web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
  web-local/src/routes/(application)/dashboard/[name]/edit/+page.svelte
  web-local/src/routes/(application)/files/[...file]/+page.svelte
  web-local/tests/utils/commonHelpers.ts
  web-local/tests/utils/sourceHelpers.ts
Labels: blocker

#4792 fix: suppress tooltip on navigation to tdd
  web-common/src/features/dashboards/big-number/MeasureBigNumber.svelte
Labels: blocker

#4791 Fix redirect on folder rename
  web-common/src/features/entity-management/RenameAssetModal.svelte
  web-common/src/features/models/workspace/ModelWorkspaceCTAs.svelte
Labels: blocker

#4788 File explorer - Invalidation issues when source's table query has errored or is deleted
  web-common/src/features/entity-management/file-artifacts.ts
  web-common/src/features/entity-management/resource-invalidations.ts
  web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
Labels: blocker

#4799 Fix project title for a blank `rill.yaml`
  web-common/src/features/project/selectors.ts
Labels: Type:Bug

#4802 Admin: Prevent panic in permission check when ctx is cancelled
  admin/server/auth/claims.go
Labels: blocker

#4811 Change "kind" to "type" in user-facing error messages
  runtime/compilers/rillv1/parse_node.go
  runtime/compilers/rillv1/parser.go
  runtime/controller.go
  runtime/drivers/duckdb/catalogv2.go
  runtime/reconcilers/migration.go
  runtime/reconcilers/model.go
  runtime/reconcilers/project_parser.go
  runtime/reconcilers/util.go
  runtime/resources.go
Labels: blocker

#4815 Fix 500 error on application startup
  web-common/src/features/feature-flags.ts
Labels: Type:Bug

#4823 Fix bug in conditional for OLAP instructions
  web-common/src/features/sources/modal/AddSourceModal.svelte
Labels: Type:Bug, blocker

#4826 Fix breadcrumbs case-sensitivity bug
  web-admin/src/features/navigation/TopNavigationBar.svelte
  web-common/src/components/navigation/breadcrumbs/BreadcrumbItem.svelte
  web-local/src/routes/(viz)/+layout.svelte
Labels: blocker

#4847 Fix: Add chart when no items set
  web-local/src/routes/(application)/custom-dashboards/[name]/+page.svelte
Labels: Type:Bug

#4903 Chart Editor: Left align table
  web-local/src/routes/(application)/chart/[name]/+page.svelte
Labels: Type:Bug

#4902 Fix: Autosave
  web-common/src/features/editor/Editor.svelte
  web-common/src/features/models/workspace/ModelEditor.svelte
  web-common/src/features/sources/editor/SourceEditor.svelte
  web-common/src/features/sources/workspace/SourceCTAs.svelte
  web-local/src/routes/(application)/[type=workspace]/[name]/+page.svelte
  web-local/src/routes/(application)/files/[...file]/+page.svelte
Labels: Type:Bug, patch

#4916 Fix: Model editor revert button
  web-common/src/features/models/workspace/ModelEditor.svelte
Labels: Type:Bug, blocker

#4920 fix: Custom picker focus handling
  web-common/src/components/date-picker/Litepicker.svelte
  web-common/src/components/date-picker/custom-picker.js
Labels: Type:Bug

#4923 fix: Clearing a dashboard yaml stops updating errors
  web-admin/src/features/dashboards/listing/selectors.ts
  web-common/src/features/entity-management/resource-invalidations.ts
  web-local/tests/dashboards/dashboards.spec.ts
  web-local/tests/dashboards/leaderboard-context-column.spec.ts
  web-local/tests/dashboards/number-formatting.spec.ts
  web-local/tests/utils/ResourceWatcher.ts
Labels: Type:Bug, blocker

#4925 Upgrade to DuckDB 0.10.2
  go.mod
  go.sum
  runtime/controller_test.go
Labels: blocker

#4927 Runtime: Fix renaming a reconciling resource
  runtime/controller.go
  runtime/controller_test.go
Labels: blocker

#4919 Embed DuckDB extensions in the Rill binary
  .gitignore
  Makefile
  runtime/drivers/duckdb/duckdb.go
  runtime/drivers/duckdb/extensions/embed/.gitkeep
  runtime/drivers/duckdb/extensions/extensions.go
  runtime/pkg/duckdbsql/duckdbsql.go
  scripts/embed_duckdb_ext/main.go
Labels: blocker

#4945 Tweak/Fix: Tracker reconnection timing/cancellation
  web-common/src/features/entity-management/ResourceWatcher.svelte
  web-common/src/runtime-client/exponential-backoff-tracker.ts
  web-common/src/runtime-client/watch-request-client.ts
Labels: Type:Bug, patch

#4932 chore: enrich scaling log
  admin/worker/run_autoscaler.go
Labels: Team:Infra, Area:Telemetry

#4936 Time comparison for Pivot
  proto/rill/ui/v1/dashboard.proto
  web-common/src/components/data-types/PercentageChange.svelte
  web-common/src/features/dashboards/pivot/PivotTable.svelte
  web-common/src/features/dashboards/pivot/PivotToolbar.svelte
  web-common/src/features/dashboards/pivot/pivot-column-definition.ts
  web-common/src/features/dashboards/pivot/pivot-data-store.ts
  web-common/src/features/dashboards/pivot/pivot-queries.ts
  web-common/src/features/dashboards/pivot/pivot-table-transformations.ts
  web-common/src/features/dashboards/pivot/pivot-utils.ts
  web-common/src/features/dashboards/pivot/types.ts
  web-common/src/features/dashboards/proto-state/fromProto.ts
  web-common/src/features/dashboards/proto-state/toProto.ts
  web-common/src/features/dashboards/stores/dashboard-store-defaults.ts
  web-common/src/features/dashboards/stores/dashboard-stores.ts
  web-common/src/proto/gen/rill/ui/v1/dashboard_pb.ts
Labels: blocker

#4984 Remove font style declaration from `PercentageChange`
  web-common/src/components/data-types/PercentageChange.svelte
Labels: blocker

#4980 fix: First source import modal opening before ingestion is completed
  web-common/src/features/entity-management/resource-status-utils.ts
  web-common/src/features/sources/source-imported-utils.ts
Labels: blocker

#4956 Dedicated connectors
  cli/cmd/project/describe.go
  proto/gen/rill/admin/v1/admin.swagger.yaml
  proto/gen/rill/runtime/v1/resources.pb.go
  proto/gen/rill/runtime/v1/resources.pb.validate.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/rill/runtime/v1/resources.proto
  runtime/compilers/rillv1/connectors.go
  runtime/compilers/rillv1/connectors_test.go
  runtime/compilers/rillv1/parse_connector.go
  runtime/compilers/rillv1/parse_node.go
  runtime/compilers/rillv1/parser.go
  runtime/compilers/rillv1/parser_test.go
  runtime/controller_test.go
  runtime/reconcilers/connector.go
  runtime/reconcilers/project_parser.go
  runtime/registry.go
  runtime/resources.go
  runtime/runtime.go
  web-admin/src/client/gen/index.schemas.ts
  web-common/src/proto/gen/rill/runtime/v1/resources_pb.ts
  web-common/src/runtime-client/gen/index.schemas.ts
Labels: blocker

#4998 Runtime: Fix environment-specific YAML overrides not working for `sql:`
  runtime/compilers/rillv1/parse_node.go
  runtime/compilers/rillv1/parser_test.go
Labels: blocker

#4968 fix: change summable function check to regex
  web-common/src/features/dashboards/dashboard-utils.ts
Labels: Type:Bug
