Repository rilldata/rill, pull requests merged in 2025-04, with the labels that each got.

#7024 fix: alert edit crashiing the app
  web-common/src/features/alerts/EditAlertForm.svelte
Labels: Type:Bug, blocker

#7039 fix: watermark field is converted to string when using `transform_sql`
  runtime/reconcilers/model.go
  runtime/resolvers/glob.go
  runtime/resolvers/glob_test.go
Labels: patch

#7037 Fix leaderboard bg gradients
  web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardHeader.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte
Labels: patch

#7155 fix: respect leaderboard measure names based on visible measures
  web-common/src/features/dashboards/state-managers/actions/measures.ts
  web-common/src/features/dashboards/state-managers/selectors/leaderboard.ts
  web-common/src/features/dashboards/url-state/url-state-variations.spec.ts
Labels: blocker

#6879 feat: Simplify rill time syntax
  proto/gen/rill/runtime/v1/queries.pb.go
  proto/gen/rill/runtime/v1/queries.pb.validate.go
  proto/gen/rill/runtime/v1/runtime.swagger.yaml
  proto/rill/runtime/v1/queries.proto
  runtime/metricsview/executor_rewrite_time.go
  runtime/pkg/metricssql/parser_test.go
  runtime/pkg/metricssql/time_range_parser.go
  runtime/pkg/rilltime/rilltime.go
  runtime/pkg/rilltime/rilltime_test.go
  runtime/pkg/timeutil/timeutil.go
  runtime/pkg/timeutil/timeutil_test.go
  runtime/queries/metricsview_timeseries.go
  runtime/queries/timeutil.go
  runtime/resolvers/testdata/metrics_comparisons.yaml
  runtime/server/queries_metrics.go
  web-common/src/proto/gen/rill/runtime/v1/queries_pb.ts
  web-common/src/runtime-client/gen/index.schemas.ts
Labels: blocker

#7164 tweak: add leaderboard icon for canvas
  web-common/src/features/canvas/AddComponentDropdown.svelte
  web-common/src/features/canvas/icons/LeaderboardIcon.svelte
Labels: blocker

#7176 Fix dimension and measure gradients in single measure selection
  web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte
Labels: blocker

#7171 fix(canvas): pivot cell interactivity
  web-common/src/features/dashboards/pivot/NestedTable.svelte
  web-common/src/features/dashboards/pivot/PivotExpandableCell.svelte
  web-common/src/features/dashboards/pivot/PivotTable.svelte
Labels: blocker

#7184 fix: edge cases with dimension search
  web-common/src/components/search/Search.svelte
  web-common/src/features/dashboards/filters/dimension-filters/DimensionFilter.svelte
  web-common/src/features/dashboards/filters/dimension-filters/dimension-search-text-utils.ts
  web-common/src/features/dashboards/filters/dimension-filters/split-dimension-search-text.spec.ts
Labels: blocker

#7197 fix(canvas): row item limit
  web-common/src/features/canvas/CanvasBuilder.svelte
  web-common/src/features/canvas/EditableCanvasRow.svelte
  web-common/src/features/canvas/layout-util.ts
Labels: Type:Bug, patch

#7208 fix (Pinot): Update client-side `yup` schema
  runtime/drivers/athena/athena.go
  runtime/drivers/azure/azure.go
  runtime/drivers/bigquery/bigquery.go
  runtime/drivers/clickhouse/clickhouse.go
  runtime/drivers/druid/druid.go
  runtime/drivers/duckdb/duckdb.go
  runtime/drivers/gcs/gcs.go
  runtime/drivers/https/https.go
  runtime/drivers/mysql/mysql.go
  runtime/drivers/pinot/pinot.go
  runtime/drivers/postgres/postgres.go
  runtime/drivers/redshift/redshift.go
  runtime/drivers/s3/s3.go
  runtime/drivers/salesforce/salesforce.go
  runtime/drivers/snowflake/snowflake.go
  runtime/drivers/sqlite/sqlite.go
  web-common/src/features/sources/modal/yupSchemas.ts
Labels: patch

#7220 fix(canvas): moving items while editing
  web-common/src/features/canvas/CanvasBuilder.svelte
  web-common/src/features/canvas/EditableCanvasRow.svelte
  web-common/src/features/canvas/layout-util.ts
Labels: Type:Bug, patch

#7143 feat: most recent explore state
  web-common/src/features/dashboards/state-managers/loaders/DashboardStateDataLoader.ts
  web-common/src/features/dashboards/state-managers/loaders/DashboardStateManager.spec.ts
  web-common/src/features/dashboards/state-managers/loaders/DashboardStateSync.ts
  web-common/src/features/dashboards/state-managers/loaders/most-recent-explore-state.ts
  web-common/src/features/dashboards/state-managers/most-recent-explore-state.spec.ts
  web-common/src/features/dashboards/stores/validate-and-clean-explore-state.spec.ts
  web-common/src/features/dashboards/stores/validate-and-clean-explore-state.ts
  web-common/src/features/dashboards/url-state/url-state-variations.spec.ts
  web-common/src/features/explores/ExploreEditor.svelte
  web-common/src/features/explores/PreviewButton.svelte
  web-common/src/features/metrics-views/editor/MetricsEditor.svelte
Labels: blocker
