Repository rilldata/rill, pull requests merged in 2025-02, with the labels that each got.

#6487 feat: file upload input
  web-common/src/components/forms/FileInput.svelte
  web-common/src/components/icons/Attachment.svelte
Labels: blocker

#6521 feat: Custom logo UI support
  web-admin/src/features/organizations/settings/LogoSettings.svelte
  web-admin/src/features/organizations/settings/SettingsContainer.svelte
  web-admin/src/routes/[organization]/-/settings/+page.svelte
  web-common/src/components/forms/FileInput.svelte
  web-common/src/components/icons/Rill.svelte
Labels: blocker

#6573 fix: metrics table reordering
  web-common/src/features/workspaces/VisualMetrics.svelte
Labels: Type:Bug

#6621 fix (Explore): Check both `MetricsView` and `Explore` resources for a `validSpec` and `reconcileError`
  web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte
Labels: Type:Bug, patch

#6645 fix: tab background
  web-common/src/components/dialog/tabs/TabsTrigger.svelte
Labels: patch

#6662 fix (Column Profiling): zero records triggered a histogram bug
  web-common/src/components/data-graphic/utils.ts
Labels: Type:Bug

#6670 Reports UI: Handle missing dashboard
  web-admin/src/features/scheduled-reports/metadata/ReportMetadata.svelte
Labels: Type:Bug

#6726 fix: org invalidation after logo/favicon upload
  web-admin/src/features/organizations/settings/FaviconSettings.svelte
  web-admin/src/features/organizations/settings/LogoSettings.svelte
  web-admin/src/routes/+layout.ts
Labels: blocker

#6673 Canvas: add support for local time filters
  web-common/src/features/canvas/Canvas.svelte
  web-common/src/features/canvas/CanvasComponent.svelte
  web-common/src/features/canvas/ComponentHeader.svelte
  web-common/src/features/canvas/LocalFiltersHeader.svelte
  web-common/src/features/canvas/components/BaseCanvasComponent.ts
  web-common/src/features/canvas/components/ComponentRenderer.svelte
  web-common/src/features/canvas/components/charts/Chart.svelte
  web-common/src/features/canvas/components/charts/selector.ts
  web-common/src/features/canvas/components/kpi-grid/KPIGrid.svelte
  web-common/src/features/canvas/components/kpi/KPI.svelte
  web-common/src/features/canvas/components/kpi/selector.ts
  web-common/src/features/canvas/components/kpi/util.ts
  web-common/src/features/canvas/components/table/TableTemplate.svelte
  web-common/src/features/canvas/components/table/index.ts
  web-common/src/features/canvas/components/table/selector.ts
  web-common/src/features/canvas/components/types.ts
  web-common/src/features/canvas/components/util.ts
  web-common/src/features/canvas/filters/CanvasComparisonPill.svelte
  web-common/src/features/canvas/filters/CanvasFilters.svelte
  web-common/src/features/canvas/inspector/filters/DimensionFiltersInput.svelte
  web-common/src/features/canvas/inspector/filters/FiltersMapper.svelte
  web-common/src/features/canvas/inspector/filters/TimeFiltersInput.svelte
  web-common/src/features/canvas/inspector/types.ts
  web-common/src/features/canvas/stores/canvas-component.ts
  web-common/src/features/canvas/stores/canvas-entity.ts
  web-common/src/features/canvas/stores/filters.ts
  web-common/src/features/canvas/stores/time-control.ts
  web-common/src/features/canvas/stores/types.ts
  web-common/src/features/dashboards/time-controls/TimeGrainSelector.svelte
  web-common/src/features/dashboards/time-controls/comparison-pill/ComparisonPill.svelte
  web-common/src/features/dashboards/time-controls/super-pill/SuperPill.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/RangeDisplay.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/RangePicker.svelte
  web-common/src/features/dashboards/url-state/convertPresetToExploreState.ts
  web-common/src/features/dashboards/url-state/convertURLToExplorePreset.ts
Labels: blocker

#6730 tweak: rewrite kpi component, canvas cleanup
  web-common/src/components/time-series-chart/Chart.svelte
  web-common/src/components/time-series-chart/Crosshairs.svelte
  web-common/src/components/time-series-chart/Line.svelte
  web-common/src/components/time-series-chart/Point.svelte
  web-common/src/features/canvas/Canvas.svelte
  web-common/src/features/canvas/CanvasDashboardEmbed.svelte
  web-common/src/features/canvas/CanvasDashboardPreview.svelte
  web-common/src/features/canvas/RowBasedCanvas.svelte
  web-common/src/features/canvas/RowWrapper.svelte
  web-common/src/features/canvas/SvelteGridStack.svelte
  web-common/src/features/canvas/components/BaseCanvasComponent.ts
  web-common/src/features/canvas/components/charts/Chart.svelte
  web-common/src/features/canvas/components/kpi-grid/KPIGrid.svelte
  web-common/src/features/canvas/components/kpi/KPI.svelte
  web-common/src/features/canvas/components/kpi/KPISparkline.svelte
  web-common/src/features/canvas/components/kpi/selector.ts
  web-common/src/features/canvas/inspector/filters/TimeFiltersInput.svelte
  web-common/src/features/entity-management/file-artifact.ts
Labels: blocker

#6766 fix (Cloud UI): Always redirect to login when auth token expires
  web-admin/src/client/redirect-utils.ts
  web-admin/src/routes/+layout.ts
Labels: patch

#6777 fix: bits ui checkbox display bug
  web-common/src/components/dropdown-menu/DropdownMenuCheckboxItem.svelte
  web-common/src/features/visual-editing/SelectionDropdown.svelte
  web-common/src/features/workspaces/VisualExploreEditing.svelte
Labels: patch

#6776 tweak: display measure error
  web-common/src/components/forms/Input.svelte
  web-common/src/features/dashboards/filters/measure-filters/MeasureFilterForm.svelte
Labels: patch

#6775 fix: persistent search text
  web-common/src/components/search/Search.svelte
Labels: patch

#6791 fix: monthly parsing of report cron
  web-common/src/features/scheduled-reports/time-utils.ts
  web-common/src/features/scheduled-reports/utils.ts
Labels: Type:Bug, patch
