Repository rilldata/rill, pull requests merged in 2025-01, with the labels that each got.

#6317 fix: redirect loop when home bookmark has missing compare dimension
  web-common/src/features/dashboards/url-state/DashboardURLStateSync.svelte
Labels: Type:Bug

#6385 Add help command grouping and org display name editing
  cli/cmd/admin/admin.go
  cli/cmd/devtool/devtool.go
  cli/cmd/org/edit.go
  cli/cmd/org/org_test.go
  cli/cmd/root.go
  cli/cmd/runtime/runtime.go
  cli/cmd/sudo/sudo.go
  cli/cmd/verify_install.go
  cli/pkg/cmdutil/group.go
Labels: Area:CLI, Type:Improvement

#6379 fix: delayed save issue
  web-common/src/features/entity-management/async-save-state.ts
  web-common/src/features/entity-management/file-artifact.ts
Labels: Type:Bug, patch

#6393 Estimate tar sizes for rill deploy command
  admin/server/assets.go
  cli/pkg/cmdutil/archive.go
  runtime/pkg/archive/archive.go
Labels: Area:CLI, Type:Improvement

#6421 Fix initial load of Cloud dashboard
  web-admin/src/routes/[organization]/[project]/explore/[dashboard]/+page.svelte
Labels: Type:Bug, patch

#6387 Add positional argument to `env` commands for project
  cli/cmd/env/configure.go
  cli/cmd/env/env.go
  cli/cmd/env/pull.go
  cli/cmd/env/push.go
  cli/cmd/env/rm.go
  cli/cmd/env/set.go
  cli/cmd/env/show.go
  cli/pkg/printer/printer.go
  runtime/pkg/env/env.go
Labels: Area:CLI

#6427 fix: save content method
  web-common/src/features/entity-management/file-artifact.ts
  web-common/src/features/visual-metrics-editing/EditControls.svelte
  web-common/src/features/visual-metrics-editing/MetricsTableRow.svelte
  web-common/src/features/workspaces/VisualExploreEditing.svelte
  web-common/src/features/workspaces/VisualMetrics.svelte
  web-local/tests/metrics-editor.spec.ts
Labels: blocker

#6430 tweak: resource table column sizing
  web-admin/src/features/projects/status/ProjectResourcesTable.svelte
  web-admin/src/features/projects/status/RefreshCell.svelte
  web-admin/src/features/projects/status/ResourceErrorMessage.svelte
  web-common/src/components/table/BasicTable.svelte
Labels: blocker

#6439 fix : certain db level settings in duckdb can't be set again
  runtime/drivers/duckdb/duckdb.go
  runtime/pkg/rduckdb/db.go
Labels: blocker

#6337 2 phase comparison query
  runtime/drivers/olap.go
  runtime/drivers/registry.go
  runtime/metricsview/ast.go
  runtime/metricsview/astsql.go
  runtime/metricsview/executor.go
  runtime/metricsview/executor_rewrite_approx_comparisons.go
  runtime/metricsview/executor_rewrite_druid_exactify.go
  runtime/metricsview/executor_rewrite_percent_of_totals.go
  runtime/metricsview/executor_rewrite_two_phase_comparisons.go
  runtime/testruntime/testdata/ad_bids/metrics/ad_bids_metrics_view.yaml
Labels: blocker

#6152 docs/ advanced measures window
  docs/docs/build/metrics-view/customize.md
  docs/docs/build/metrics-view/expressions.md
  docs/docs/reference/project-files/metrics-view.md
  docs/docs/tutorials/rill_advanced_features/incremental_models/3-data-warehouse-partitions.md
  docs/sidebars.js
Labels: Type:Documentation

#6437 fix: array and object filter values
  web-common/src/features/dashboards/url-state/filters/converters.ts
  web-common/src/features/dashboards/url-state/filters/expression.cjs
  web-common/src/features/dashboards/url-state/filters/expression.ne
  web-common/src/features/dashboards/url-state/filters/expression.spec.ts
  web-common/src/features/dashboards/url-state/filters/post-processors.ts
Labels: Type:Bug

#6445 fix : cleanup old version of the new table in cloud storage when renaming a table
  runtime/pkg/rduckdb/db.go
Labels: blocker

#6444 Add feature flag for Canvas dashboard menu option
  web-common/src/features/entity-management/AddAssetButton.svelte
Labels: blocker

#6406 fix: measure filter dismiss flow
  web-common/src/features/dashboards/filters/measure-filters/MeasureFilter.svelte
  web-common/src/features/dashboards/filters/measure-filters/MeasureFilterForm.svelte
Labels: blocker

#6462 fix: compare time and dimension conflicts in url param
  web-common/src/features/dashboards/url-state/convertExploreStateToPreset.ts
  web-common/src/features/dashboards/url-state/convertPresetToExploreState.ts
Labels: Type:Bug

#6473 fix : postgres sources fail if database_url is set via connector configs
  runtime/drivers/duckdb/duckdb.go
  runtime/drivers/duckdb/transporter_duckDB_to_duckDB.go
  runtime/drivers/duckdb/transporter_duckDB_to_duckDB_test.go
  runtime/drivers/duckdb/transporter_postgres_to_duckDB_test.go
  runtime/drivers/duckdb/transporter_sqlite_to_duckDB_test.go
Labels: blocker

#6478 Set `rill env pull` to resolve variables for the `dev` environment
  cli/cmd/env/pull.go
Labels: blocker

#6469 fix: reconnect to a different github failing with `remote already exists`
  admin/server/assets.go
  admin/server/github.go
  runtime/drivers/admin/admin.go
  runtime/pkg/archive/archive.go
Labels: blocker

#6496 fix: embedded dashboards without time series
  web-common/src/features/dashboards/url-state/DashboardURLStateSyncWrapper.svelte
Labels: Type:Bug

#6513 Set max date for public url form
  web-admin/src/features/dashboards/share/ShareDashboardPopover.svelte
  web-admin/src/features/public-urls/CreatePublicURLForm.svelte
Labels: patch

#6533 fix (Breadcrumbs): Missing label for projects outside the first page
  web-admin/src/features/navigation/TopNavigationBar.svelte
Labels: patch
