Repository rilldata/rill, pull requests merged in 2025-09, with the labels that each got.

#7874 fix(rill dev): out of view throttle timeout being incorrect
  web-common/src/runtime-client/watch-request-client.ts
Labels: Bug

#7985 fix: display ranges as inclusive
  web-common/src/lib/time/ranges/formatter.spec.ts
  web-common/src/lib/time/ranges/formatter.ts
Labels: patch

#7984 fix(rilltime): ceil legacy iso instead of truncating
  runtime/pkg/rilltime/rilltime.go
  runtime/pkg/rilltime/rilltime_test.go
Labels: blocker, Bug

#7996 chore: rilltime tweaks
  web-common/src/features/dashboards/time-controls/super-pill/components/RangeDisplay.svelte
  web-common/src/features/dashboards/time-controls/super-pill/new-time-dropdown/RangePickerV2.svelte
  web-common/src/lib/time/ranges/formatter.ts
Labels: blocker

#8002 fix: all time behavior
  runtime/metricsview/executor_rewrite_time.go
  runtime/pkg/metricssql/time_range_parser.go
  runtime/pkg/rilltime/rilltime.go
  runtime/server/queries_metrics.go
  web-admin/tests/alerts.spec.ts
  web-common/src/features/canvas/stores/time-control.ts
  web-common/src/features/dashboards/filters/Filters.svelte
  web-common/src/features/dashboards/state-managers/selectors/time-range.ts
  web-common/src/features/dashboards/time-controls/new-time-controls.ts
  web-common/src/features/dashboards/time-controls/rill-time-ranges.ts
  web-common/src/features/dashboards/time-controls/time-control-store.ts
  web-common/src/features/dashboards/url-state/convertURLToExplorePreset.ts
  web-common/src/features/dashboards/url-state/time-ranges/parser.ts
  web-common/src/features/scheduled-reports/FiltersForm.svelte
  web-common/src/lib/time/ranges/index.ts
Labels: blocker
