Repository rilldata/rill, pull requests merged in 2025-05, with the labels that each got.

#7301 fix: yaml defaults not loaded in embed
  web-common/src/features/dashboards/state-managers/loaders/DashboardStateDataLoader.ts
  web-common/src/features/dashboards/url-state/clean-url-params.ts
  web-common/src/features/dashboards/url-state/get-cleaned-url-params-for-goto.ts
Labels: patch

#7303 fix (Incremental models): don't pass invalid `pageToken` on first load of partitions
  web-common/orval.config.ts
  web-common/src/features/models/partitions/PartitionsTable.svelte
  web-common/src/runtime-client/fetchWrapper.ts
  web-common/src/runtime-client/gen/runtime-service/runtime-service.ts
  web-local/tests/models/incremental.spec.ts
  web-local/tests/models/models.spec.ts
Labels: patch

#7308 fix: grain not persisting when it is the only thing in url
  web-common/src/features/dashboards/stores/test-data/store-mutations.ts
  web-common/src/features/dashboards/url-state/convertPresetToExploreState.ts
  web-common/src/features/dashboards/url-state/url-state-variations.spec.ts
Labels: blocker, patch

#7298 fix: heatmap aggregation queries
  web-common/src/components/vega/util.ts
  web-common/src/features/canvas/components/charts/builder.ts
  web-common/src/features/canvas/components/charts/cartesian-charts/CartesianChart.ts
  web-common/src/features/canvas/components/charts/circular-charts/CircularChart.ts
  web-common/src/features/canvas/components/charts/heatmap-charts/HeatmapChart.ts
  web-common/src/features/canvas/components/charts/heatmap-charts/spec.ts
  web-common/src/features/canvas/components/charts/query-utils.ts
  web-common/src/features/canvas/components/charts/types.ts
  web-common/src/features/canvas/components/charts/util.ts
Labels: blocker

#7284 tweak: default to donut instead of pie chart
  docs/docs/reference/project-files/canvas-dashboards.md
  web-common/src/features/canvas/components/charts/circular-charts/CircularChart.ts
  web-common/src/features/canvas/components/charts/index.ts
  web-common/src/features/canvas/components/charts/types.ts
  web-common/src/features/canvas/components/charts/util.ts
  web-common/src/features/canvas/components/util.ts
  web-common/src/features/canvas/inspector/chart/ChartTypeSelector.svelte
  web-common/src/features/canvas/layout-util.ts
  web-local/tests/canvas/charts.spec.ts
Labels: blocker

#7369 fix: alerts and reports not honouring execution time when "Opened in browser"
  web-admin/src/features/dashboards/query-mappers/utils.ts
Labels: Type:Bug, patch

#7382 fix: dashboard settings persisting across page loads in embed
  web-admin/src/features/embeds/ExploreEmbed.svelte
  web-admin/src/routes/-/embed/+page.svelte
  web-common/src/features/dashboards/state-managers/loaders/DashboardStateDataLoader.ts
  web-common/src/features/dashboards/state-managers/loaders/DashboardStateManager.svelte
  web-common/src/features/dashboards/state-managers/loaders/DashboardStateSync.ts
Labels: Type:Bug, patch
