Repository rilldata/rill, pull requests merged in 2025-07, with the labels that each got.

#7549 fix: feature flag new palette generation
  web-common/src/components/color-picker/ColorInput.svelte
  web-common/src/features/dashboards/time-series/MeasureValueMouseover.svelte
  web-common/src/features/themes/actions.ts
  web-common/src/features/themes/color-config.ts
  web-common/src/features/themes/palette-generator.ts
  web-common/src/features/visual-editing/ThemeInput.svelte
Labels: Type:Bug, patch

#7594 fix install script failing for downloading latest
  cli/pkg/installscript/installscript.go
Labels: patch

#7572 feat: edit alert dashboard filters
  .gitignore
  web-admin/src/features/alerts/CreateAlert.svelte
  web-admin/src/features/alerts/metadata/AlertFilterCriteria.svelte
  web-admin/src/features/alerts/metadata/AlertFilters.svelte
  web-admin/src/features/alerts/metadata/AlertMetadata.svelte
  web-admin/src/routes/[organization]/[project]/-/alerts/[alert]/open/+page.svelte
  web-admin/tests/alerts.spec.ts
  web-admin/tests/public-urls.spec.ts
  web-common/src/components/chip/core/Chip.svelte
  web-common/src/components/forms/Input.svelte
  web-common/src/components/forms/Select.svelte
  web-common/src/components/notifications/Notification.svelte
  web-common/src/features/alerts/AlertForm.svelte
  web-common/src/features/alerts/AlertPreviewTable.svelte
  web-common/src/features/alerts/alert-preview-data.ts
  web-common/src/features/alerts/create-alert-utils.ts
  web-common/src/features/alerts/criteria-tab/AlertDialogCriteriaTab.svelte
  web-common/src/features/alerts/criteria-tab/AlertPreview.svelte
  web-common/src/features/alerts/criteria-tab/CriteriaForm.svelte
  web-common/src/features/alerts/criteria-tab/CriteriaGroup.svelte
  web-common/src/features/alerts/criteria-tab/getTypeOptions.ts
  web-common/src/features/alerts/data-tab/AlertDialogDataTab.svelte
  web-common/src/features/alerts/data-tab/DataPreview.svelte
  web-common/src/features/alerts/delivery-tab/AlertDialogDeliveryTab.svelte
  web-common/src/features/alerts/extract-alert-form-values.ts
  web-common/src/features/alerts/form-utils.ts
  web-common/src/features/alerts/utils.spec.ts
  web-common/src/features/alerts/utils.ts
  web-common/src/features/canvas/filters/CanvasComparisonPill.svelte
  web-common/src/features/canvas/filters/util.ts
  web-common/src/features/dashboards/dimension-table/dimension-table-export.ts
  web-common/src/features/dashboards/pivot/pivot-export.ts
  web-common/src/features/dashboards/state-managers/selectors/measures.ts
  web-common/src/features/dashboards/stores/ExploreMetricsViewMetadata.ts
  web-common/src/features/dashboards/stores/Filters.ts
  web-common/src/features/dashboards/stores/TimeControls.ts
  web-common/src/features/dashboards/stores/dashboard-stores.ts
  web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/RangePicker.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/Zone.svelte
  web-common/src/features/dashboards/time-controls/time-range-mappers.ts
  web-common/src/features/dashboards/time-dimension-details/tdd-export.ts
  web-common/src/features/dashboards/url-state/convertPresetToExploreState.ts
  web-common/src/features/explore-mappers/map-to-explore.ts
  web-common/src/features/explore-mappers/utils.ts
  web-common/src/features/scheduled-reports/FiltersForm.svelte
  web-common/src/features/scheduled-reports/utils.ts
  web-common/src/lib/arrayUtils.ts
  web-common/tests/utils/explore-interactions.ts
  web-local/tests/canvas/filters.spec.ts
Labels: blocker

#7615 fix: Misc UXQA alert/reprot filter edit issues
  web-common/src/components/searchable-filter-menu/SearchableMenuContent.svelte
  web-common/src/features/alerts/AlertForm.svelte
  web-common/src/features/canvas/filters/CanvasComparisonPill.svelte
  web-common/src/features/dashboards/filters/FilterButton.svelte
  web-common/src/features/dashboards/filters/dimension-filters/DimensionFilter.svelte
  web-common/src/features/dashboards/filters/measure-filters/MeasureFilter.svelte
  web-common/src/features/dashboards/filters/measure-filters/MeasureFilterForm.svelte
  web-common/src/features/dashboards/time-controls/TimeGrainSelector.svelte
  web-common/src/features/dashboards/time-controls/comparison-pill/ComparisonPill.svelte
  web-common/src/features/dashboards/time-controls/super-pill/SuperPill.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/RangePicker.svelte
  web-common/src/features/dashboards/time-controls/super-pill/components/Zone.svelte
  web-common/src/features/scheduled-reports/BaseScheduledReportForm.svelte
  web-common/src/features/scheduled-reports/FiltersForm.svelte
  web-common/src/features/scheduled-reports/ScheduledReportDialog.svelte
Labels: blocker

#7465 fix: min time grain derivation
  web-common/src/features/canvas/stores/time-control.ts
Labels: Bug

#7680 fix: ghost tooltips from time dimension detail charts
  web-common/src/components/vega/VegaLiteRenderer.svelte
  web-common/src/components/vega/VegaRenderer.svelte
  web-common/src/components/vega/vega-tooltip.ts
Labels: blocker

#7663 fix: disable alert time drop down when rill time is enabled
  web-common/src/features/alerts/alert-preview-data.ts
  web-common/src/features/dashboards/filters/TimeRangeReadOnly.svelte
  web-common/src/features/dashboards/time-controls/time-range-mappers.ts
  web-common/src/features/dashboards/url-state/time-ranges/parser.ts
  web-common/src/features/dashboards/url-state/time-ranges/rill-time.cjs
  web-common/src/features/scheduled-reports/FiltersForm.svelte
Labels: blocker

#7704 fix: missing grain for time pivot chips
  web-common/src/features/dashboards/pivot/time-pill-store.ts
Labels: blocker
