Repository rilldata/rill, pull requests merged in 2025-03, with the labels that each got.

#6845 tweak: remove components from breadcrumbs
  web-common/src/features/workspaces/WorkspaceCrumb.svelte
Labels: patch

#6865 fix : clickhouse query settings should be set to write operations as well
  runtime/drivers/clickhouse/olap.go
Labels: blocker

#6862 fix: motherduck connector failing due to lock configuration setting
  runtime/drivers/duckdb/transporter_motherduck_to_duckDB.go
  runtime/pkg/rduckdb/db.go
Labels: blocker

#6869 fix : remove secret directory config
  runtime/drivers/duckdb/duckdb.go
Labels: blocker

#6905 fix: incorrect url path for canvas hrefs
  web-common/src/features/dashboards/dashboard-utils.ts
Labels: Type:Bug, patch

#6947 chore: lift canvas feature flag
  web-common/src/features/entity-management/AddAssetButton.svelte
  web-common/src/features/feature-flags.ts
  web-common/src/features/metrics-views/MetricsViewMenuItems.svelte
Labels: patch

#6945 fix: comparison fallbacks
  web-common/src/features/dashboards/time-controls/super-pill/components/Comparison.svelte
  web-common/src/features/dashboards/time-controls/time-range-store.ts
  web-common/src/lib/time/types.ts
Labels: Type:Bug, blocker, patch

#6948 fix: use multiline input for advanced dimension expressions
  web-common/src/features/visual-metrics-editing/Sidebar.svelte
Labels: patch

#6954 fix (Connector Explorer): Don't hide OLAP tables when there's no explicit `database`
  web-common/src/features/connectors/olap/DatabaseExplorer.svelte
  web-common/src/features/connectors/olap/selectors.ts
Labels: blocker

#6941 canvas: mar 20 uxqa
  web-common/src/components/time-series-chart/Chart.svelte
  web-common/src/features/canvas/AddComponentDropdown.svelte
  web-common/src/features/canvas/CanvasComponent.svelte
  web-common/src/features/canvas/CanvasDashboardWrapper.svelte
  web-common/src/features/canvas/RowBasedCanvas.svelte
  web-common/src/features/canvas/components/ComponentRenderer.svelte
  web-common/src/features/canvas/components/kpi-grid/KPIGrid.svelte
  web-common/src/features/canvas/components/kpi/KPI.svelte
  web-common/src/features/canvas/components/pivot/CanvasPivotDisplay.svelte
  web-common/src/features/canvas/components/pivot/CanvasPivotRenderer.svelte
  web-common/src/features/canvas/components/table/CanvasTableDisplay.svelte
  web-common/src/features/canvas/filters/CanvasFilters.svelte
  web-common/src/features/canvas/stores/canvas-entity.ts
  web-common/src/features/canvas/stores/types.ts
  web-common/src/features/dashboards/pivot/PivotTable.svelte
  web-common/src/features/metrics-views/MetricsViewMenuItems.svelte
  web-common/src/layout/workspace/WorkspaceEditorContainer.svelte
Labels: patch

#6985 Hotfix: measures formatter
  web-common/src/features/dashboards/leaderboard/Leaderboard.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardDisplay.svelte
  web-common/src/features/dashboards/leaderboard/LeaderboardRow.svelte
  web-common/src/features/dashboards/state-managers/selectors/data-formatting.ts
Labels: patch

#6981 fix: incorrect as of reference
  web-common/src/features/dashboards/filters/Filters.svelte
Labels: Type:Bug, blocker, patch
